### PR TITLE
[BUG] extend_right/left() needs `char const *` overload

### LINKED ISSUE #1473: extend_right/left() needs `char const *` overload.
`extend_right()` in the index module does not handle null-terminated strings properly:

```cpp
#include <seqan3/search/fm_index/all.hpp>
#include <seqan3/core/debug_stream.hpp>

using namespace seqan3;

int main()
{
std::string text = "How much wood would a woodchuck chuck?";
fm_index index{text};

auto it = index.begin();

if (it.extend_right("wood"))
    debug_stream << it.locate() << '\n';
}
```
Outputs no results, but wrapping `"wood"` into `std::string` produces correct behaviour.

### PR DESCRIPTION
**Pull request by Irallia**
Resolves #1473.

Test case added.

### CODE REVIEW

File: include/seqan3/search/fm_index/bi_fm_index_cursor.hpp [hunk 1]
```diff
@@ -437,6 +437,41 @@ class bi_fm_index_cursor
         return false;
     }
 
+    //!\overload
+    template <typename char_t>
+    bool extend_right(char_t* const c) noexcept
```
Comment (marehr) [inline include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: can you try if this works with `std::string_view` instead?

Comment (eseiler) [reply include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: Actually, for `std::string_view` the range overload of `extend_right` works; so we could also do
```cpp
    bool extend_right(char const * c) noexcept
    {
        return extend_right(std::string_view{c});
    }
```
And be done with it (because the actual problem is the `\0` of the input)

Comment (marehr) [reply include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: Oh you can do this?

The wouldn't be

```cpp
    bool extend_right(std::string_view sv) noexcept
    {
        return extend_right(sv);
    }
```

possible?

File: CHANGELOG.md [hunk 2]
```diff
@@ -245,6 +245,8 @@ Note that 3.1.0 will be the first API stable release and interfaces in this rele
   The same applies for the `seqan3::bi_fm_index_cursor`
   ([\#1433](https://github.com/seqan/seqan3/pull/1433)).
 
+*  The `extend_right()` function can now also handle `char const *`.
```
Comment (marehr) [inline CHANGELOG.md]: can you add the PR link?

**Comment by SGSSGene** [comment]
Wow, any one knows why `std::ranges::range` includes the `\0` at the end of a `char*`?

Also I wanted to point out that the same issue should exists with  `bi_fm_index_cursor`.

**Comment by eseiler** [comment]
> Wow, any one knows why `std::ranges::range` includes the `\0` at the end of a `char*`?
`char const *` models `std::ranges::range` and it always includes a `\0` as terminator (C-Style string). Also, the size of the `char const *` includes the terminator, so it's natural to include the terminator when you look at it as a range. If you do not want the terminator, you need to explicitly do something to get rid of it. For example, constructing a `string_view` which is aware that the `\0` isn't part of the acutal string, but more like an implementation detail, and acts this way, i.e. as a range it does not include the `\0` and the size also does not include the terminator.

> 
> Also I wanted to point out that the same issue should exists with `bi_fm_index_cursor`.

Yes it should; for `extend_left` and `extend_right`

File: test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp [hunk 3]
```diff
@@ -328,6 +328,30 @@ TYPED_TEST_P(fm_index_cursor_collection_test, lazy_locate)
     EXPECT_TRUE(std::ranges::equal(it.locate(), it.lazy_locate()));
 }
 
+TYPED_TEST_P(fm_index_cursor_collection_test, locate_char_string)
+{
+    std::string text = "How much wood would a woodchuck chuck?";
+    std::string wood = "wood";
```
Comment (marehr) [inline test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp]:
```suggestion
    char const * wood = "wood";
```

File: test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp [hunk 4]
```diff
@@ -328,6 +328,30 @@ TYPED_TEST_P(fm_index_cursor_collection_test, lazy_locate)
     EXPECT_TRUE(std::ranges::equal(it.locate(), it.lazy_locate()));
 }
 
+TYPED_TEST_P(fm_index_cursor_collection_test, locate_char_string)
+{
+    std::string text = "How much wood would a woodchuck chuck?";
```
Comment (marehr) [inline test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp]:
```suggestion
    // test case for reported bug https://github.com/seqan/seqan3/issues/1473
    std::string text = "How much wood would a woodchuck chuck?";
```

**Comment by SGSSGene** [comment]
> > Wow, any one knows why `std::ranges::range` includes the `\0` at the end of a `char*`?
> 
> `char const *` models `std::ranges::range` and it always includes a `\0` as terminator (C-Style string). Also, the size of the `char const *` includes the terminator, so it's natural to include the terminator when you look at it as a range. If you do not want the terminator, you need to explicitly do something to get rid of it. For example, constructing a `string_view` which is aware that the `\0` isn't part of the acutal string, but more like an implementation detail, and acts this way, i.e. as a range it does not include the `\0` and the size also does not include the terminator.
I know that `std::ranges::range` includes the `\0` ;-) I was more wondering, why does it?
If I look at C and functions like `strlen` it doesn't include the `\0`. Also `std::ranges::range` assumes that a `char const*` is a C-Style string.  This seems counter intuitive since `char const*` is often used for just data. But even assuming it is a C-Style string, in which cases do I want to manipulate the terminator? I can think of many cases were are `\0` should be ignored, but non were it could be useful.

**Comment by marehr** [comment]
> I know that `std::ranges::range` includes the `\0` ;-) I was more wondering, why does it?
> If I look at C and functions like `strlen` it doesn't include the `\0`. Also `std::ranges::range` assumes that a `char const*` is a C-Style string. This seems counter intuitive since `char const*` is often used for just data. But even assuming it is a C-Style string, in which cases do I want to manipulate the terminator? I can think of many cases were are `\0` should be ignored, but non were it could be useful.

In this case the string is not of type `char const *` (char pointer, which is not a range), but of type `char []` (bounded char array, which is a range). (See https://en.cppreference.com/w/cpp/language/array)

Only a bounded array can be a range, because it knows its start and its end position (start + array size). Here an example: https://godbolt.org/z/zt-Aga

You can argue why `char[]` should be always a range with size - 1, but I guess that this is more error prone (on some platforms is `uint8_t = char` so sequence of number might be misinterpreted as a string and truncate data) than to accept that char literals always include `\0`. An easy fix to convert a classic cstr is to use `string_view`.

**Comment by SGSSGene** [comment]
> > I know that `std::ranges::range` includes the `\0` ;-) I was more wondering, why does it?
> > If I look at C and functions like `strlen` it doesn't include the `\0`. Also `std::ranges::range` assumes that a `char const*` is a C-Style string. This seems counter intuitive since `char const*` is often used for just data. But even assuming it is a C-Style string, in which cases do I want to manipulate the terminator? I can think of many cases were are `\0` should be ignored, but non were it could be useful.
> 
> In this case the string is not of type `char const *` (char pointer, which is not a range), but of type `char []` (bounded char array, which is a range). (See https://en.cppreference.com/w/cpp/language/array)
> 
> Only a bounded array can be a range, because it knows its start and its end position (start + array size). Here an example: https://godbolt.org/z/zt-Aga

Ah it is a `char []`, I wasn't aware of that. Now the puzzle comes together. I have no experience with ranges and couldn't find anything on this particular issue. Thank you

File: CHANGELOG.md [hunk 5]
```diff
@@ -35,6 +35,11 @@ Note that 3.1.0 will be the first API stable release and interfaces in this rele
 * Add top-level `CMakeLists.txt`
   ([\#1475](https://github.com/seqan/seqan3/pull/1475)).
 
+#### Search
+
+*  The `extend_right()` function can now also handle `char const *`.
```
Comment (smehringer) [inline CHANGELOG.md]:
```suggestion
*  The `seqan3::fm_index_cursor::extend_right()`, `seqan3::bi_fm_index_cursor::extend_right()` and
   `seqan3::bi_fm_index_cursor::extend_left()` functions handle c-style strings without including the null character 
```

And please put this under Bug fixes instead :)

File: include/seqan3/search/fm_index/bi_fm_index_cursor.hpp [hunk 6]
```diff
@@ -437,6 +437,12 @@ class bi_fm_index_cursor
         return false;
     }
 
+    //!\overload
+    bool extend_right(char const * c) noexcept
```
Comment (smehringer) [inline include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: this should work for all char types:

```cpp
    template <typename char_type>
    //!\cond
        requires detail::is_char_adaptation_v<char_type>
    //!\endcond
    bool extend_right(char_type const * cstring) noexcept
    {
        return extend_right(std::string_view{cstring});
    }
```
same for all the other overloads

Comment (marehr) [reply include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: If we go this route:
1) discuss the name and the location of `is_char_adaptation_v` in the core-team (this concept is private for our adaptation of chars for alphabets)
2) ```c++
    return extend_right(std::string_view{cstring});
    // -> should be
    return extend_right(std::basic_string_view<char_type>{cstring});
    ```

Comment (smehringer) [reply include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: > 1. discuss the name and the location of is_char_adaptation_v in the core-team (this concept is private for our adaptation of chars for alphabets)

This can be part of another PR

> 2. ...

Yes! Thanks

Comment (Irallia) [reply include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: 2. I have rewritten the function as mentioned, but it does not find ```is_char_adaptation_v```.
```bash
In file included from ...seqan3/include/seqan3/search/fm_index/fm_index.hpp:26,
                 ...seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:20,
                 ...seqan3/include/seqan3/search/fm_index/all.hpp:48,
                 ...seqan3/include/seqan3/search/algorithm/search.hpp:19,
                 ...seqan3/include/seqan3/search/algorithm/all.hpp:67,
                 ...seqan3/test/unit/search/search_test.cpp:11:
...seqan3/include/seqan3/search/fm_index/fm_index_cursor.hpp:288:26: error: 'is_char_adaptation_v' is not a member of 'seqan3::detail'
  288 |         requires detail::is_char_adaptation_v<char_type>
      |                          ^~~~~~~~~~~~~~~~~~~~
...seqan3/include/seqan3/search/fm_index/fm_index_cursor.hpp:288:56: error: expected primary-expression before '>' token
  288 |         requires detail::is_char_adaptation_v<char_type>
      |                                                        ^
...seqan3/include/seqan3/search/fm_index/fm_index_cursor.hpp:290:5: error: expected primary-expression before 'bool'
  290 |     bool extend_right(char_type const * cstring) noexcept
      |     ^~~~
```

Comment (marehr) [reply include/seqan3/search/fm_index/bi_fm_index_cursor.hpp]: use: `#include <seqan3/alphabet/adaptation/char.hpp>`

File: CHANGELOG.md [hunk 7]
```diff
@@ -37,6 +37,12 @@ Note that 3.1.0 will be the first API stable release and interfaces in this rele
 * We now use Doxygen version 1.8.17 to build our documentation
   ([\#1500](https://github.com/seqan/seqan3/pull/1500)).
 
+#### Search
+
+* The `seqan3::fm_index_cursor::extend_right()`, `seqan3::bi_fm_index_cursor::extend_right()` and
```
Comment (smehringer) [inline CHANGELOG.md]: This is still under `New features` but should be under `notable bug fixes` :)

Comment (Irallia) [reply CHANGELOG.md]: Thx, did I place the test in the right place?

File: CHANGELOG.md [hunk 8]
```diff
@@ -37,10 +37,16 @@ Note that 3.1.0 will be the first API stable release and interfaces in this rele
 * We now use Doxygen version 1.8.17 to build our documentation
   ([\#1500](https://github.com/seqan/seqan3/pull/1500)).
 
+#### Search
+
 ## API changes
 
 ## Notable Bug-fixes
 
+* The `seqan3::fm_index_cursor::extend_right()`, `seqan3::bi_fm_index_cursor::extend_right()` and
```
[the remark this answers is not in the document]
Comment (Irallia) [reply CHANGELOG.md]: sorry 🙈

**Comment by Irallia** [comment]
@smehringer after this long time, I had some merging problems. I solved everything, but some includes poped up witch are not mine I think.. Can you please check with me again if there are still open comments and if these includes are useful?

File: CHANGELOG.md [hunk 9]
```diff
@@ -56,6 +56,8 @@ Note that 3.1.0 will be the first API stable release and interfaces in this rele
 
 * Added `seqan3::interleaved_bloom_filter`, a data structure that efficiently answers set-membership queries for
   multiple bins ([\#920](https://github.com/seqan/seqan3/pull/920)).
+*  The `extend_right()` function can now also handle `char const *`.
```
Comment (smehringer) [inline CHANGELOG.md:59]: this can be removed because there is a note under bug fixes below

File: test/unit/search/fm_index/bi_fm_index_aa27_test.cpp [hunk 10]
```diff
@@ -10,6 +10,8 @@
 #include "fm_index_collection_test_template.hpp"
 #include "fm_index_test_template.hpp"
 
+#include <seqan3/alphabet/aminoacid/aa27.hpp>
```
Comment (smehringer) [inline test/unit/search/fm_index/bi_fm_index_aa27_test.cpp:13]: remove this

File: test/unit/search/fm_index/bi_fm_index_char_test.cpp [hunk 11]
```diff
@@ -8,6 +8,8 @@
 #include "fm_index_collection_test_template.hpp"
 #include "fm_index_test_template.hpp"
 
+#include <seqan3/alphabet/adaptation/uint.hpp>
```
Comment (smehringer) [inline test/unit/search/fm_index/bi_fm_index_char_test.cpp:11]: remove this

File: test/unit/search/fm_index/bi_fm_index_dna4_test.cpp [hunk 12]
```diff
@@ -10,6 +10,8 @@
 #include "fm_index_collection_test_template.hpp"
 #include "fm_index_test_template.hpp"
 
+#include <seqan3/alphabet/nucleotide/dna4.hpp>
```
Comment (smehringer) [inline test/unit/search/fm_index/bi_fm_index_dna4_test.cpp:13]: remove this

File: test/unit/search/fm_index/fm_index_dna4_test.cpp [hunk 13]
```diff
@@ -11,6 +11,9 @@
 #include "fm_index_collection_test_template.hpp"
 #include "fm_index_test_template.hpp"
 
+#include <seqan3/alphabet/nucleotide/dna4.hpp>
```
Comment (smehringer) [inline test/unit/search/fm_index/fm_index_dna4_test.cpp:14]: remove this

File: test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp [hunk 14]
```diff
@@ -321,6 +321,45 @@ TYPED_TEST_P(fm_index_cursor_collection_test, lazy_locate)
     EXPECT_TRUE(std::ranges::equal(it.locate(), it.lazy_locate()));
 }
 
+TYPED_TEST_P(fm_index_cursor_collection_test, locate_char_string)
```
Comment (smehringer) [inline test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp:324]: I thought after restructuring the text you can add this test in a different way (by a new fixture)?

File: test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test_template.hpp [hunk 15]
```diff
@@ -222,5 +222,38 @@ TYPED_TEST_P(bi_fm_index_cursor_collection_test, to_rev_cursor)
     }
 }
 
+TYPED_TEST_P(bi_fm_index_cursor_collection_test, locate_char_string)
```
Comment (smehringer) [inline test/unit/search/fm_index_cursor/bi_fm_index_cursor_collection_test_template.hpp:225]:
```suggestion
TYPED_TEST_P(bi_fm_index_cursor_collection_test, extend_const_char_pointer)
```
:nail_care: Since it is not about locate but about extend_left/right :)

**Comment by marehr** [comment]
Travis fails:

```
In file included from /home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/fm_index.hpp:24,

                 from /home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:20,

                 from /home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/all.hpp:48,

                 from /home/travis/build/seqan/seqan3/test/unit/search/fm_index_cursor/fm_index_cursor_collection_test_template.hpp:12,

                 from /home/travis/build/seqan/seqan3/test/unit/search/fm_index_cursor/fm_index_cursor_collection_test.cpp:16:

/home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/fm_index_cursor.hpp: In member function ‘void gtest_suite_fm_index_cursor_collection_test_::locate_char_string<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::fm_index_cursor<seqan3::fm_index<char, (seqan3::text_layout)1> >]’:

/home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/fm_index_cursor.hpp:331:19: error: ‘it1.seqan3::fm_index_cursor<seqan3::fm_index<char, (seqan3::text_layout)1> >::parent_lb’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

         size_type new_parent_lb = parent_lb, new_parent_rb = parent_rb;

                   ^~~~~~~~~~~~~

/home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/fm_index_cursor.hpp:331:46: error: ‘it1.seqan3::fm_index_cursor<seqan3::fm_index<char, (seqan3::text_layout)1> >::parent_rb’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

         size_type new_parent_lb = parent_lb, new_parent_rb = parent_rb;

                                              ^~~~~~~~~~~~~

cc1plus: all warnings being treated as errors
```

**Comment by rrahn** [comment]
It seems that these here are not initialised:

https://github.com/seqan/seqan3/blob/332f4b3749f7baeee1efb6e1e2cd310df0f2fdc0/include/seqan3/search/fm_index/fm_index_cursor.hpp#L91-L93

**Comment by Irallia** [comment]
@rrahn, thanks for your help! It seems that your suggestion helped a bit. Travis is running through now, but Jenkins still shows some problems with the ```osx_g++-9_cereal-true_Release```:
99% tests passed, 3 tests failed out of 6419
The following tests FAILED:
	5930 - search_collection_test_NOT_BUILT (Not Run)
	5963 - search_scheme_algorithm_test_NOT_BUILT (Not Run)
	5964 - search_scheme_test_NOT_BUILT (Not Run)

I still cannot reconstruct the errors. 
Log file:
```log
[ 91%] Linking CXX executable search_collection_test
g++-9: error: CMakeFiles/search_collection_test.dir/search_collection_test.cpp.o: No such file or directory
CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/GoogleTestAddTests.cmake:26 (message):
  Specified test executable does not exist.

    Path: '/Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/build/search/search_collection_test'

[ 91%] Built target search_collection_test
```

**Comment by marehr** [comment]
Current build failure:

```c++
[ 89%] Building CXX object search/CMakeFiles/search_scheme_test.dir/search_scheme_test.cpp.o
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/wait.h:110,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:66,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cstdlib:75,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/stl_algo.h:59,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:62,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/resource.h:443:34: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  443 | int     getiopolicy_np(int, int) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/resource.h:449:39: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  449 | int     setiopolicy_np(int, int, int) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:128,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cstdlib:75,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/stl_algo.h:59,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:62,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/malloc/_malloc.h:52:74: error: expected initializer before '__OSX_AVAILABLE_STARTING'
   52 | int   posix_memalign(void **__memptr, size_t __alignment, size_t __size) __OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_3_0);
      |                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cstdlib:75,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/stl_algo.h:59,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:62,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:270:53: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  270 | void  arc4random_buf(void * __buf, size_t __nbytes) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:273:46: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  273 |   arc4random_uniform(uint32_t __upper_bound) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cstdlib:75,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/stl_algo.h:59,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:62,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:292:45: error: expected initializer before '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
  292 | int  daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:325:6: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  325 |      __OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_3_2);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:333:6: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  333 |      __OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_3_2);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:79,
                 from /usr/local/Cellar/gcc/9.3.0/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/include-fixed/stdio.h:78,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:90,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cwchar:44,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/postypes.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/char_traits.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/string:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/stdexcept:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/array:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/tuple:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/functional:54,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/pstl/glue_algorithm_defs.h:13,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:71,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stdio.h:39:56: error: expected initializer before '__OSX_AVAILABLE_STARTING'
   39 | int     renameat(int, const char *, int, const char *) __OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:90,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cwchar:44,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/postypes.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/char_traits.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/string:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/stdexcept:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/array:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/tuple:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/functional:54,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/pstl/glue_algorithm_defs.h:13,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:71,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/usr/local/Cellar/gcc/9.3.0/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/include-fixed/stdio.h:366:67: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  366 | int dprintf(int, const char * __restrict, ...) __printflike(2, 3) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/gcc/9.3.0/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/include-fixed/stdio.h:367:79: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  367 | int vdprintf(int, const char * __restrict, __gnuc_va_list) __printflike(2, 0) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:90,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cwchar:44,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/postypes.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/char_traits.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/string:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/stdexcept:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/array:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/tuple:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/functional:54,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/pstl/glue_algorithm_defs.h:13,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:71,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/usr/local/Cellar/gcc/9.3.0/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/include-fixed/stdio.h:368:123: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  368 | ssize_t getdelim(char ** __restrict __linep, size_t * __restrict __linecapp, int __delimiter, FILE * __restrict __stream) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/gcc/9.3.0/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/include-fixed/stdio.h:369:105: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  369 | ssize_t getline(char ** __restrict __linep, size_t * __restrict __linecapp, FILE * __restrict __stream) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cwchar:44,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/postypes.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/bits/char_traits.h:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/string:40,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/stdexcept:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/array:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/tuple:39,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/functional:54,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/pstl/glue_algorithm_defs.h:13,
                 from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/algorithm:71,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:197:67: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  197 | wchar_t *wcpcpy(wchar_t * __restrict, const wchar_t * __restrict) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:198:76: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  198 | wchar_t *wcpncpy(wchar_t * __restrict, const wchar_t * __restrict, size_t) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:199:34: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  199 | wchar_t *wcsdup(const wchar_t *) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:200:54: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  200 | int     wcscasecmp(const wchar_t *, const wchar_t *) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:201:65: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  201 | int     wcsncasecmp(const wchar_t *, const wchar_t *, size_t n) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:202:49: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  202 | size_t  wcsnlen(const wchar_t *, size_t) __pure __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:215:47: error: expected initializer before '__OSX_AVAILABLE_STARTING'
  215 | wchar_t *fgetwln(FILE * __restrict, size_t *) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~
[ 89%] Linking CXX executable view_translate_test
In file included from /usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cinttypes:46,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/include/seqan3/core/platform.hpp:10,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/include/seqan3/search/detail/search_scheme_precomputed.hpp:18,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/helper_search_scheme.hpp:13,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:11:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/inttypes.h:234:25: error: expected constructor, destructor, or type conversion before '(' token
  234 | __OSX_AVAILABLE_STARTING(__MAC_10_4, __IPHONE_2_0)
      |                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/inttypes.h:244:25: error: expected constructor, destructor, or type conversion before '(' token
  244 | __OSX_AVAILABLE_STARTING(__MAC_10_4, __IPHONE_2_0)
      |                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/inttypes.h:249:25: error: expected constructor, destructor, or type conversion before '(' token
  249 | __OSX_AVAILABLE_STARTING(__MAC_10_4, __IPHONE_2_0)
      |                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/inttypes.h:255:25: error: expected constructor, destructor, or type conversion before '(' token
  255 | __OSX_AVAILABLE_STARTING(__MAC_10_4, __IPHONE_2_0)
      |                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/inttypes.h:262:25: error: expected constructor, destructor, or type conversion before '(' token
  262 | __OSX_AVAILABLE_STARTING(__MAC_10_4, __IPHONE_2_0)
      |                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/inttypes.h:268:25: error: expected constructor, destructor, or type conversion before '(' token
  268 | __OSX_AVAILABLE_STARTING(__MAC_10_4, __IPHONE_2_0)
      |                         ^
In file included from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/include/seqan3/core/platform.hpp:10,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/include/seqan3/search/detail/search_scheme_precomputed.hpp:18,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/helper_search_scheme.hpp:13,
                 from /Users/builder/jenkins/ws/seqan3_build_pipeline_PR-1588/checkout/test/unit/search/search_scheme_test.cpp:11:
/usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cinttypes:61:11: error: '::imaxabs' has not been declared
   61 |   using ::imaxabs;
      |           ^~~~~~~
/usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cinttypes:62:11: error: '::imaxdiv' has not been declared
   62 |   using ::imaxdiv;
      |           ^~~~~~~
/usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cinttypes:68:11: error: '::strtoimax' has not been declared
   68 |   using ::strtoimax;
      |           ^~~~~~~~~
/usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cinttypes:69:11: error: '::strtoumax' has not been declared
   69 |   using ::strtoumax;
      |           ^~~~~~~~~
/usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cinttypes:72:11: error: '::wcstoimax' has not been declared
   72 |   using ::wcstoimax;
      |           ^~~~~~~~~
/usr/local/Cellar/gcc/9.3.0/include/c++/9.3.0/cinttypes:73:11: error: '::wcstoumax' has not been declared
   73 |   using ::wcstoumax;
      |           ^~~~~~~~~
```

**Comment by smehringer** [comment]
Since the error is not related to this PR I'll merge this
