### PR TITLE
[DOC] Tutorial:introduction fix snippets

### LINKED ISSUE #1287: code snippets in SeqAn tutorial
I'm going throug to the SeqAn Tutorial in detail at the moment. After consultaion of @eseiler, my plan is to correct some irregularities and missing lines in the code snippet. Is anyone else working on this?

### PR DESCRIPTION
**Pull request by Irallia**
Resolves #1287 . 
Refurbishes the old PR #1320 .

Closes #1320

### CODE REVIEW

**Comment by Irallia** [comment]
I don't know, why travis throwed an error, I got no error.

File: doc/tutorial/introduction/introduction_align.cpp [hunk 1]
```diff
@@ -1,17 +1,13 @@
...
-
-//! [alignment_include]
-#include <tuple>                                                          // for std::make_pair
-#include <seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp> // for alignment stream operator
-#include <seqan3/alignment/pairwise/align_pairwise.hpp>                   // for align_pairwise
-//! [alignment_include]
-
-using seqan3::operator""_dna4;
+//! [alignment]
+#include <filesystem>                                                       // for tmp_dir
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_align.cpp]: You cannot use the regular `<filesystem>` header because it is not available on gcc7.
You need to use `<seqan3/std/filesystem>` instead. You probably don't have this error because you are using gcc8 or 9

File: doc/tutorial/introduction/introduction_file_input.cpp [hunk 2]
```diff
@@ -0,0 +1,63 @@
+#include <seqan3/std/filesystem>                // to create temp directory
```
Comment (MitraDarja) [inline doc/tutorial/introduction/introduction_file_input.cpp]: tmp instead of temp?

File: doc/tutorial/introduction/introduction_file_input.cpp [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+    std::filesystem::path tmp_dir = std::filesystem::temp_directory_path(); // get the temp directory
+
+    seqan3::sequence_file_input file_in{tmp_dir/"seq.fasta"};
+
+    // Retrieve the sequences and ids.
+    for (auto &[seq, id, qual] : file_in)
+    {
+        seqan3::debug_stream << "ID:     " << id << '\n';
+        seqan3::debug_stream << "SEQ:    " << seq << '\n';
+        seqan3::debug_stream << "Empty Qual." << qual << '\n';  // qual es empty for FastAfiles
```
Comment (MitraDarja) [inline doc/tutorial/introduction/introduction_file_input.cpp]: is, not es

File: doc/tutorial/introduction/introduction_align.cpp [hunk 4]
```diff
@@ -20,26 +16,22 @@ int main()
...
-//! [sequence_input]
-    // Initialise a file input object with a FastA file.
-    seqan3::sequence_file_input file_in{filename}; // filename: "seq.fasta"
+    // Initialise a file input object and a vector
+    seqan3::sequence_file_input file_in{filename};
+    std::vector<seqan3::dna5_vector> sequences;
 
-    // Retrieve the sequences and ids.
-    for (auto &[seq, id, qual] : file_in)
+    for (auto & [ seq, id, qual ] : file_in)
```
Comment (MitraDarja) [inline doc/tutorial/introduction/introduction_align.cpp]: If we do not use id and qual here, should we give them variable names then?

File: doc/tutorial/introduction/introduction_align.cpp (hunk 1 above)
Comment (Irallia) [reply doc/tutorial/introduction/introduction_align.cpp]: That helped. Thanks for the hint!

File: doc/tutorial/introduction/introduction_align.cpp (hunk 4 above)
Comment (Irallia) [reply doc/tutorial/introduction/introduction_align.cpp]: I think its mandatory to name all existing fields: seqan3::fields<seqan3::field::seq, seqan3::field::id, seqan3::field::qual>>

Comment (MitraDarja) [reply doc/tutorial/introduction/introduction_align.cpp]: Maybe, I am wrong but I think it is possible to use _ instead of id and qual. But yeah, I am not sure if using these would not decrease readability...

File: doc/tutorial/introduction/introduction_file_input.cpp [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+
+//! [fileinput]
+#include <string>
+#include <seqan3/core/debug_stream.hpp>         // for debug_stream
+#include <seqan3/io/sequence_file/input.hpp>    // for sequence_file_input
+
+int main ()
+{
+    // Initialise a file input object with a FastA file.
+    std::filesystem::path tmp_dir = std::filesystem::temp_directory_path(); // get the temp directory
```
Comment (MitraDarja) [inline doc/tutorial/introduction/introduction_file_input.cpp]: tmp, not temp

File: doc/tutorial/introduction/index.md [hunk 6]
```diff
@@ -27,12 +27,15 @@ Most good tutorials start with an easy *Hello World!* program. So have a look:
...
 Most of them are compilable as-is, but some are only valid in their context,
 e.g. they depend on other code snippets given before/after the current one or
-other statements implied by the text. You can copy'n'paste freely from these examples,
-this implies no copyright-obligations (however distributing SeqAn or an application
-using it does, see [Copyright](https://docs.seqan.de/seqan/3-master-user/about_copyright.html) and [Citing](https://docs.seqan.de/seqan/3-master-user/about_citing.html).
+other statements implied by the text.
+
+You can copy'n'paste freely from the code snippets, this implies no copyright-obligations (however distributing
+SeqAn or an application using it does, see [Copyright](https://docs.seqan.de/seqan/3-master-user/about_copyright.html)
+and [Citing](https://docs.seqan.de/seqan/3-master-user/about_citing.html)).
```
Comment (smehringer) [inline doc/tutorial/introduction/index.md]: I would remove this change again and mark the `copy'n'paste freely` in bold.

File: doc/tutorial/introduction/introduction_align.cpp [hunk 7]
```diff
@@ -1,17 +1,13 @@
...
-#include <seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp> // for alignment stream operator
-#include <seqan3/alignment/pairwise/align_pairwise.hpp>                   // for align_pairwise
-//! [alignment_include]
-
-using seqan3::operator""_dna4;
+//! [alignment]
+#include <seqan3/std/filesystem>                                            // for tmp_dir
+#include <vector>                                                           // for std::vector
+#include <seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp>   // for alignment stream operator
+#include <seqan3/alignment/pairwise/align_pairwise.hpp>                     // for align_pairwise
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_align.cpp]: sort the includes and distinguish between stl headers and seqan headers by a new line

File: doc/tutorial/introduction/index.md [hunk 8]
```diff
@@ -151,7 +152,12 @@ algorithm which then executes all alignments in parallel and stores the results
 objects. The second argument to seqan3::align_pairwise is the *configuration* which allows you to specify
 a lot of parameters for the alignment computation, for instance score functions, banded alignment and whether
 you wish to compute a traceback or not. The configurations have their own namespace seqan3::align_cfg and can
-be combined via the logical OR operator (`|`) for building combinations. Check out the alignment tutorial if you want to learn more.
+be combined via the logical OR operator (`|`) for building combinations. Check out the alignment tutorial if you want
+to learn more.
+
+\note
+In general, we omit `using namespace seqan3;`, to show which parts are from SeqAn3 and which aren't. However, for comprehensibility we declare string literals like _dna5 beforehand with a using directive. You can skip it, if you
+work with the overall namespace or declare it in lines 20 and 21 directly.
```
Comment (smehringer) [inline doc/tutorial/introduction/index.md]: We encourage you to **avoid** declaring `using namespace seqan3;`. This has the additional benefit of easily distinguishing between library features and standard C++. The only exception are string literals, where we often use `using seqan3::operator""_dna4` for convenience.

File: doc/tutorial/introduction/introduction_align.cpp [hunk 9]
```diff
@@ -20,26 +16,22 @@ int main()
     {
         // Create a /tmp/my.fasta file.
         seqan3::sequence_file_output file_out{filename};
-        file_out.emplace_back("ACGTGATG"_dna4, std::string{"seq1"});
-        file_out.emplace_back("AGTGATACT"_dna4, std::string{"seq2"});
+
+        using seqan3::operator""_dna5;  // for better readability of next code lines
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_align.cpp]:
```suggestion
        using seqan3::operator""_dna5; 
```

File: doc/tutorial/introduction/introduction_align.cpp (hunk 4 above)
Comment (smehringer) [reply doc/tutorial/introduction/introduction_align.cpp]: Unfortunately, this only works in python.

File: doc/tutorial/introduction/introduction_file_input.cpp [hunk 10]
```diff
@@ -0,0 +1,63 @@
+#include <seqan3/std/filesystem>                // to create tmp directory
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_file_input.cpp]: alphabetical order :nail_care:

File: doc/tutorial/introduction/introduction_file_input.cpp [hunk 11]
```diff
@@ -0,0 +1,63 @@
...
+#include <seqan3/alphabet/nucleotide/dna4.hpp>  // to create right datastructure in tmp file
+#include <seqan3/io/sequence_file/output.hpp>   // to create tmp file
+
+// Creating a tmp FastA file with sequences.
+// It's necessary, because some review processes in GitHub don't allow using
+// an alreadys existing file. So you can use the whole code from this file as
+// an example or the collection of snippets, shown in the introduction.
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_file_input.cpp]: This creates a temporary file to ensure that the snippet works correctly without any dependency on external files.

File: doc/tutorial/introduction/introduction_file_input.cpp [hunk 12]
```diff
@@ -0,0 +1,63 @@
...
+        if (ec)
+            seqan3::debug_stream << "[WARNING] Could not delete " << file_path << ". " << ec.message() << '\n';
+    }
+};
+
+write_file_dummy_struct go{};
+
+//! [fileinput]
+#include <string>
+#include <seqan3/core/debug_stream.hpp>         // for debug_stream
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_file_input.cpp]: separate stl header from seqan3 headers by newline

File: doc/tutorial/introduction/introduction_file_input.cpp [hunk 13]
```diff
@@ -0,0 +1,63 @@
...
+#include <seqan3/io/sequence_file/input.hpp>    // for sequence_file_input
+
+int main ()
+{
+    // Initialise a file input object with a FastA file.
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_file_input.cpp]: This comment is meant for the next line of code I think.

File: doc/tutorial/introduction/introduction_read_fasta.cpp [hunk 14]
```diff
@@ -1,16 +1,18 @@
 //! [read]
-#include <string>                            // for std::string
-#include <vector>                            // for std::vector
-#include <seqan3/argument_parser/all.hpp>    // for argument_parser
-#include <seqan3/core/debug_stream.hpp>      // for debug_stream
-#include <seqan3/io/sequence_file/input.hpp> // for sequence_file_input
+#include <string>                               // for std::string
+#include <vector>                               // for std::vector
+#include <seqan3/alphabet/nucleotide/dna5.hpp>  // for dna5 datastrucutre
```
Comment (smehringer) [inline doc/tutorial/introduction/introduction_read_fasta.cpp]: sorry, found one more thig: separate stl headers from seqan3 headers

Comment (Irallia) [reply doc/tutorial/introduction/introduction_read_fasta.cpp]: I amended the last commit.

**Comment by marehr** [comment]
@smehringer merge me please :)
