### PR TITLE
Fixes #3266: Incorrect begin/end of alignment for banded alignment

### LINKED ISSUE #3266: Incorrect begin/end of alignment for banded alignment
### Does this problem persist on the current main?

- [X] I have verified the issue on the current main

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do a banded alignment, I get incorrect values for begin/end of the alignment. For example, the attached program outputs:

```
Using configGeneral: 
{sequence1 id: 0, sequence2 id: 0, score: 4, begin: (0,24), end: (6,30), 
alignment:
(CGTCTA,CGTGTA)}

Using configBanded: 
{sequence1 id: 0, sequence2 id: 0, score: 4, begin: (0,5), end: (6,11), 
alignment:
(CGTCTA,CGTGTA)}
```

### Expected Behavior

I expect the same begin/end values whether I use banded alignment or not.

### Steps To Reproduce

I am using the attached test program on Ubuntu 22.04 and compiling it as follows: 

```
g++ -O3 -DNDEBUG -Wall -Wextra -std=c++20 -I /home/paolo/seqan3/include -isystem /home/paolo/seqan3/submodules/sdsl-lite/include -isystem /home/paolo/seqan3/submodules/cereal/include -pthread -O0 -ggdb3 seqan3test1.cpp
```

### Environment

```markdown
- Operating system: Ubuntu 22.04
- SeqAn version: Commit ca4d668390e35b4045ccd02d070927f8178ed2ce
- Compiler: g++ 11.4.0
```

### Anything else?

Here is the test program. Added `.txt` extension for posting. 

[seqan3test1.cpp.txt](https://github.com/user-attachments/files/16240085/seqan3test1.cpp.txt)

### PR DESCRIPTION
**Pull request by rrahn**
In case the sequences are sliced by cutting off a prefix of the original seuence due to the band configuration, the relative positions of the sliced sequences was reported inside of the alignment result.
However, this slicing happens only internally and thus the positions reported should correspond to the ones of the original sequences.
We fix this by tracking the offset of the prefix that was cut off and add this to the relative positions during result creation to get the absolute positions.

### CODE REVIEW

File: include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp [hunk 1]
```diff
@@ -192,10 +191,39 @@ class alignment_matrix_policy
...
+     * \brief Converts a sliced position in the alignment matrix to the corresponding position in the original sequence 1.
+     *
+     * \param position The position in the sliced alignment matrix.
+     * \return The corresponding position in the original sequence 1.
+     *
+     * Only changes the position if the sequence was sliced due to band configuration.
+     */
+    constexpr size_t to_original_sequence1_position(size_t position) const noexcept
+    {
+        return position + seq1_slice_offset;
```
Comment (eseiler) [inline include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp:204]: In theory, it could just be the identity if `!traits_t::is_banded`?

**Review by eseiler — APPROVED** [review]
Small stuff, you can squash merge if my comments are fine

File: include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp (hunk 1 above)
Comment (rrahn) [reply include/seqan3/alignment/pairwise/policy/alignment_matrix_policy.hpp:203]: Yes. Right now, it would just add 0. However, I guess some extra constexpr wrapper only to get a noop is for this part of the alignment code not performance relevant at all and adds just more complexity.

File: test/unit/alignment/pairwise/global_affine_banded_test.cpp [hunk 2]
```diff
@@ -5,6 +5,7 @@
 #include <gtest/gtest.h>
 
 #include <seqan3/alignment/pairwise/align_pairwise.hpp>
+#include <seqan3/core/debug_stream.hpp>
```
[the remark this answers is not in the document]
Comment (rrahn) [reply test/unit/alignment/pairwise/global_affine_banded_test.cpp]: oh yes, thanks for spotting that.

**Comment by rrahn** [comment]
Thanks a lot for fixing the small stuff right away. 👍
