### PR TITLE
Fix take until

### LINKED ISSUE #1754: take_until does not work with reverse
Combining the view take_until with reverse and then using kmer_hash did lead to two separate problems.

First, the static assert in kmer_hash fails, because kmer_hash expects a const-iterability view, which is not true for `seqan3::views::take_until | std::views::reverse`.
Removing the const from the static assert in kmer_hash should solve this problem.

```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });
std::vector<seqan3::dna4> textt{"ACGTAGC"_dna4};
seqan3::debug_stream << (textt | stop_at_t | seqan3::views::complement | std::views::reverse
                                                    | seqan3::views::kmer_hash(seqan3::ungapped{4})
                                                    | std::views::reverse) << "\n";
// Leads to a static assert failure
```

Second, using only take_until with reverse did not lead to the correct result:

```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });
std::vector<seqan3::dna4> textt{"ACGTAGC"_dna4};
seqan3::debug_stream << (textt | stop_at_t | seqan3::views::complement | std::views::reverse
                                                    | seqan3::views::kmer_hash(seqan3::ungapped{4})
                                                    | std::views::reverse) << "\n";
seqan3::debug_stream << (textt | stop_at_t  | std::views::reverse ) << "\n"; // prints: CGATGCA, not as expected GCA
```

The reason for this behaviour is that take_until does not model `sized_sentinel_for`. A solution for this should be returning `std::ranges::default_sentinel` in the end function of take until.

### PR DESCRIPTION
**Pull request by MitraDarja**
Resolves #1754 and restructures take_until a bit for better readability.

### CODE REVIEW

File: include/seqan3/range/views/take_until.hpp [hunk 1]
```diff
@@ -69,281 +69,14 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
-        }
-
-        //!\brief Switch lhs and rhs for comparison.
-        bool operator!=(sentinel_type const & rhs) const
-            noexcept(noexcept(std::declval<iterator_type &>() == rhs))
-        {
-            return !(*this == rhs);
-        }
+    template <bool is_const_range>
+    class take_until_sentinel;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:76]: I added https://github.com/orgs/seqan/projects/4#card-38949132 to have consistent naming.

Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:76]:
```suggestion
    class basic_sentinel;
```

File: include/seqan3/range/views/take_until.hpp [hunk 2]
```diff
@@ -69,281 +69,14 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
-            {
-                if constexpr (or_throw)
-                    throw unexpected_end_of_input{"Reached end of input before functor evaluated to true."};
-                else
-                    return true;
-            }
-
-            return fun(**this);
-        }
+    class iterator_type;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:73]:
```suggestion
    class basic_iterator;
```

File: include/seqan3/range/views/take_until.hpp [hunk 3]
```diff
@@ -69,281 +69,14 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
-
-        //!\brief Return the saved at_end state.
-        friend bool operator!=(sentinel_type const & lhs, iterator_type_consume_input const & rhs)
-            noexcept(noexcept(rhs != lhs))
-        {
-            return rhs != lhs;
-        }
-        //!\}
-    }; // class iterator_type_consume_input
+    class iterator_type_consume_input;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:79]:
```suggestion
    class basic_consume_iterator;
```

File: include/seqan3/range/views/take_until.hpp [hunk 4]
```diff
@@ -278,14 +278,14 @@ public inherited_iterator_base<iterator_type<rng_t>, std::ranges::iterator_t<rng
...
-public inherited_iterator_base<iterator_type_consume_input<rng_t>, std::ranges::iterator_t<rng_t>>
+class view_take_until<urng_t, fun_t, or_throw, and_consume>::basic_consume_iterator :
+public inherited_iterator_base<basic_consume_iterator<rng_t>, std::ranges::iterator_t<rng_t>>
 {
 private:
     //!\brief The iterator type of the underlying range.
     using base_base_t = std::ranges::iterator_t<rng_t>;
     //!\brief The CRTP wrapper type.
-    using base_t      = inherited_iterator_base<iterator_type_consume_input, std::ranges::iterator_t<rng_t>>;
+    using base_t      = inherited_iterator_base<basic_consume_iterator, std::ranges::iterator_t<rng_t>>;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:288]:
```suggestion
    using base_t = inherited_iterator_base<basic_consume_iterator, std::ranges::iterator_t<rng_t>>;
```

File: include/seqan3/range/views/take_until.hpp [hunk 5]
```diff
@@ -308,21 +308,15 @@ public inherited_iterator_base<iterator_type_consume_input<rng_t>, std::ranges::
...
+    constexpr basic_consume_iterator(basic_consume_iterator && rhs)                  = default; //!< Defaulted.
+    constexpr basic_consume_iterator & operator=(basic_consume_iterator const & rhs) = default; //!< Defaulted.
+    constexpr basic_consume_iterator & operator=(basic_consume_iterator && rhs)      = default; //!< Defaulted.
+    ~basic_consume_iterator()                                                        = default; //!< Defaulted.
 
     //!\brief Constructor that delegates to the CRTP layer and initialises the callable.
-    iterator_type_consume_input(base_base_t it,
+    basic_consume_iterator(base_base_t it,
                                 fun_ref_t _fun,
                                 sentinel_type sen) noexcept(noexcept(base_t{it})) :
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp]:
```suggestion
    basic_consume_iterator(base_base_t it,
                           fun_ref_t _fun,
                           sentinel_type sen) noexcept(noexcept(base_t{it})) :
```

File: include/seqan3/range/views/take_until.hpp [hunk 6]
```diff
@@ -85,10 +85,10 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
     //!\brief The iterator type of this view (a random access iterator).
     using iterator          = std::conditional_t<and_consume && !std::ranges::forward_range<urng_t>,
                                                  basic_consume_iterator<urng_t>,
-                                                 iterator_type<urng_t>>;
+                                                 basic_iterator<urng_t>>;
 
     //!\brief The const_iterator type is equal to the iterator type if the underlying range is const-iterable.
-    using const_iterator    = iterator_type<urng_t const>;
+    using const_iterator    = basic_iterator<urng_t const>;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:91]:
```suggestion
    using const_iterator = basic_iterator<urng_t const>;
```

File: include/seqan3/range/views/take_until.hpp [hunk 7]
```diff
@@ -208,14 +208,14 @@ view_take_until(urng_t &&, fun_t) -> view_take_until<std::ranges::all_view<urng_
...
-public inherited_iterator_base<iterator_type<rng_t>, std::ranges::iterator_t<rng_t>>
+class view_take_until<urng_t, fun_t, or_throw, and_consume>::basic_iterator :
+public inherited_iterator_base<basic_iterator<rng_t>, std::ranges::iterator_t<rng_t>>
 {
 private:
     //!\brief The iterator type of the underlying range.
     using base_base_t = std::ranges::iterator_t<rng_t>;
     //!\brief The CRTP wrapper type.
-    using base_t      = inherited_iterator_base<iterator_type, std::ranges::iterator_t<rng_t>>;
+    using base_t      = inherited_iterator_base<basic_iterator, std::ranges::iterator_t<rng_t>>;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:218]:
```suggestion
    using base_t = inherited_iterator_base<basic_iterator, std::ranges::iterator_t<rng_t>>;
```

File: include/seqan3/range/views/take_until.hpp [hunk 8]
```diff
@@ -85,10 +85,10 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
     //!\brief The iterator type of this view (a random access iterator).
     using iterator          = std::conditional_t<and_consume && !std::ranges::forward_range<urng_t>,
                                                  basic_consume_iterator<urng_t>,
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp]:
```suggestion
    using iterator = std::conditional_t<and_consume && !std::ranges::forward_range<urng_t>,
                                        basic_consume_iterator<urng_t>,
```

File: include/seqan3/range/views/take_until.hpp [hunk 9]
```diff
@@ -85,10 +85,10 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
-                                                 iterator_type<urng_t>>;
+                                                 basic_iterator<urng_t>>;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:88]:
```suggestion
                                        basic_iterator<urng_t>>;
```

File: include/seqan3/range/views/take_until.hpp [hunk 10]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
 template <typename urng_t, typename fun_t, bool or_throw = false, bool and_consume = false>
 view_take_until(urng_t &&, fun_t) -> view_take_until<std::ranges::all_view<urng_t>, fun_t, or_throw, and_consume>;
 
+//!\brief The iterator type inherits from the underlying type, but overwrites several operators.
+//!\tparam rng_t Should be `urng_t` for defining #iterator and `urng_t const` for defining #const_iterator.
+template <std::ranges::view urng_t, typename fun_t, bool or_throw, bool and_consume>
+template <typename rng_t>
+class view_take_until<urng_t, fun_t, or_throw, and_consume>::basic_iterator :
+public inherited_iterator_base<basic_iterator<rng_t>, std::ranges::iterator_t<rng_t>>
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:212]:
```suggestion
    public inherited_iterator_base<basic_iterator<rng_t>, std::ranges::iterator_t<rng_t>>
```

File: include/seqan3/range/views/take_until.hpp [hunk 11]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    /*!\name Constructors, destructor and assignment
+     * \brief Exceptions specification is implicitly inherited.
+     * \{
+     */
+    constexpr basic_iterator()                                       = default; //!< Defaulted.
+    constexpr basic_iterator(basic_iterator const & rhs)             = default; //!< Defaulted.
+    constexpr basic_iterator(basic_iterator && rhs)                  = default; //!< Defaulted.
+    constexpr basic_iterator & operator=(basic_iterator const & rhs) = default; //!< Defaulted.
+    constexpr basic_iterator & operator=(basic_iterator && rhs)      = default; //!< Defaulted.
+    ~basic_iterator()                                                = default; //!< Defaulted.
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:238]:
```suggestion
    constexpr basic_iterator() = default; //!< Defaulted.
    constexpr basic_iterator(basic_iterator const & rhs) = default; //!< Defaulted.
    constexpr basic_iterator(basic_iterator && rhs) = default; //!< Defaulted.
    constexpr basic_iterator & operator=(basic_iterator const & rhs) = default; //!< Defaulted.
    constexpr basic_iterator & operator=(basic_iterator && rhs) = default; //!< Defaulted.
    ~basic_iterator() = default; //!< Defaulted.
```

File: include/seqan3/range/views/take_until.hpp [hunk 12]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+
+    //!\brief Constructor that delegates to the CRTP layer.
+    basic_iterator(base_base_t it) noexcept(noexcept(base_t{it})) :
+        base_t{std::move(it)}
+    {}
+
+    //!\brief Constructor that delegates to the CRTP layer and initialises the callable.
+    basic_iterator(base_base_t it,
+                  fun_ref_t _fun,
+                  sentinel_type /*only used by the consuming iterator*/) noexcept(noexcept(base_t{it})) :
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:248]:
```suggestion
    basic_iterator(base_base_t it,
                   fun_ref_t _fun,
                   sentinel_type /*only used by the consuming iterator*/) noexcept(noexcept(base_t{it})) :
```

File: include/seqan3/range/views/take_until.hpp [hunk 13]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    //!\brief The difference type.
+    using difference_type       = typename std::iterator_traits<base_base_t>::difference_type;
+    //!\brief The value type.
+    using value_type            = typename std::iterator_traits<base_base_t>::value_type;
+    //!\brief The reference type.
+    using reference             = typename std::iterator_traits<base_base_t>::reference;
+    //!\brief The pointer type.
+    using pointer               = typename std::iterator_traits<base_base_t>::pointer;
+    //!\brief The iterator category tag.
+    using iterator_category     = iterator_tag_t<base_base_t>;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:267]:
```suggestion
    //!\brief The difference type.
    using difference_type = typename std::iterator_traits<base_base_t>::difference_type;
    //!\brief The value type.
    using value_type = typename std::iterator_traits<base_base_t>::value_type;
    //!\brief The reference type.
    using reference = typename std::iterator_traits<base_base_t>::reference;
    //!\brief The pointer type.
    using pointer = typename std::iterator_traits<base_base_t>::pointer;
    //!\brief The iterator category tag.
    using iterator_category = iterator_tag_t<base_base_t>;
```

File: include/seqan3/range/views/take_until.hpp [hunk 14]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+        return *this->this_to_base();
+    }
+};
+
+//!\brief Special iterator type used when consuming behaviour is selected.
+//!\tparam rng_t Should be `urng_t` for defining #iterator and `urng_t const` for defining #const_iterator.
+template <std::ranges::view urng_t, typename fun_t, bool or_throw, bool and_consume>
+template <typename rng_t>
+class view_take_until<urng_t, fun_t, or_throw, and_consume>::basic_consume_iterator :
+public inherited_iterator_base<basic_consume_iterator<rng_t>, std::ranges::iterator_t<rng_t>>
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:282]:
```suggestion
    public inherited_iterator_base<basic_consume_iterator<rng_t>, std::ranges::iterator_t<rng_t>>
```

File: include/seqan3/range/views/take_until.hpp [hunk 15]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    constexpr basic_consume_iterator(basic_consume_iterator const & rhs)             = default; //!< Defaulted.
+    constexpr basic_consume_iterator(basic_consume_iterator && rhs)                  = default; //!< Defaulted.
+    constexpr basic_consume_iterator & operator=(basic_consume_iterator const & rhs) = default; //!< Defaulted.
+    constexpr basic_consume_iterator & operator=(basic_consume_iterator && rhs)      = default; //!< Defaulted.
+    ~basic_consume_iterator()                                                        = default; //!< Defaulted.
+
+    //!\brief Constructor that delegates to the CRTP layer and initialises the callable.
+    basic_consume_iterator(base_base_t it,
+                                fun_ref_t _fun,
+                                sentinel_type sen) noexcept(noexcept(base_t{it})) :
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:321]:
```suggestion
    basic_consume_iterator(base_base_t it,
                           fun_ref_t _fun,
                           sentinel_type sen) noexcept(noexcept(base_t{it})) :
```

File: include/seqan3/range/views/take_until.hpp [hunk 16]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+
+    /*!\name Associated types
+     * \brief All are derived from the base_base_t.
+     * \{
+     */
+    using difference_type       = typename std::iterator_traits<base_base_t>::difference_type;  //!< From base.
+    using value_type            = typename std::iterator_traits<base_base_t>::value_type;       //!< From base.
+    using reference             = typename std::iterator_traits<base_base_t>::reference;        //!< From base.
+    using pointer               = typename std::iterator_traits<base_base_t>::pointer;          //!< From base.
+    using iterator_category     = std::input_iterator_tag;                                      //!< Always input.
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:340]:
```suggestion
    using difference_type = typename std::iterator_traits<base_base_t>::difference_type; //!< From base.
    using value_type = typename std::iterator_traits<base_base_t>::value_type; //!< From base.
    using reference = typename std::iterator_traits<base_base_t>::reference; //!< From base.
    using pointer = typename std::iterator_traits<base_base_t>::pointer; //!< From base.
    using iterator_category = std::input_iterator_tag; //!< Always input.
```

File: include/seqan3/range/views/take_until.hpp [hunk 17]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    //!\brief The CRTP wrapper type.
+    using base_t      = inherited_iterator_base<basic_iterator, std::ranges::iterator_t<rng_t>>;
+    //!\brief The sentinel type is identical to that of the underlying range.
+    using sentinel_type = std::ranges::sentinel_t<rng_t>;
+    //!\brief Auxiliary type.
+    using fun_ref_t = std::conditional_t<std::is_const_v<rng_t>,
+                                         std::remove_reference_t<fun_t> const &,
+                                         std::remove_reference_t<fun_t> &>;
+    //!\brief Reference to the functor stored in the view.
+    ranges::semiregular_t<fun_ref_t> fun;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:226]:
```suggestion
    ranges::semiregular_box_t<fun_ref_t> fun;
```

File: include/seqan3/range/views/take_until.hpp [hunk 18]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    using base_base_t = std::ranges::iterator_t<rng_t>;
+    //!\brief The CRTP wrapper type.
+    using base_t      = inherited_iterator_base<basic_consume_iterator, std::ranges::iterator_t<rng_t>>;
+
+    //!\brief Auxiliary type.
+    using fun_ref_t = std::conditional_t<std::is_const_v<rng_t>,
+                                         std::remove_reference_t<fun_t> const &,
+                                         std::remove_reference_t<fun_t> &>;
+    //!\brief Reference to the functor stored in the view.
+    ranges::semiregular_t<fun_ref_t> fun;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:295]:
```suggestion
    ranges::semiregular_box_t<fun_ref_t> fun;
```

File: include/seqan3/range/views/take_until.hpp [hunk 19]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    //!\brief Auxiliary type.
+    using predicate_ref_t = std::conditional_t<is_const_range,
+                                               std::remove_reference_t<fun_t> const &,
+                                               std::remove_reference_t<fun_t> &>;
+
+    //!\brief The actual end of the underlying range.
+    urng_sentinel_type urng_sentinel{};
+
+    //!\brief Reference to the predicate stored in the view.
+    ranges::semiregular_t<predicate_ref_t> predicate{};
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:440]:
```suggestion
    ranges::semiregular_box_t<predicate_ref_t> predicate{};
```

File: include/seqan3/range/views/take_until.hpp [hunk 20]
```diff
@@ -69,293 +69,26 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
-        //!\}
-    }; // class iterator_type_consume_input
+    class basic_consume_iterator;
 
 private:
     /*!\name Associated types
      * \{
      */
     //!\brief The iterator type of this view (a random access iterator).
     using iterator          = std::conditional_t<and_consume && !std::ranges::forward_range<urng_t>,
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:86]:
```suggestion
    using iterator = std::conditional_t<and_consume && !std::ranges::forward_range<urng_t>,
```

File: include/seqan3/range/views/take_until.hpp [hunk 21]
```diff
@@ -69,293 +69,26 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
-                                                 iterator_type_consume_input<urng_t>,
-                                                 iterator_type<urng_t>>;
+                                                 basic_consume_iterator<urng_t>,
+                                                 basic_iterator<urng_t>>;
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:88]:
```suggestion
                                        basic_consume_iterator<urng_t>,
                                        basic_iterator<urng_t>>;
```

File: include/seqan3/range/views/take_until.hpp [hunk 22]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+public:
+    /*!\name Constructors, destructor and assignment
+     * \{
+     */
+    basic_sentinel() = default;                                   //!< Defaulted.
+    basic_sentinel(basic_sentinel const &) = default;             //!< Defaulted.
+    basic_sentinel(basic_sentinel &&) = default;                  //!< Defaulted.
+    basic_sentinel & operator=(basic_sentinel const &) = default; //!< Defaulted.
+    basic_sentinel & operator=(basic_sentinel &&) = default;      //!< Defaulted.
+    ~basic_sentinel() = default;                                  //!< Defaulted.
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:451]:
```suggestion
    basic_sentinel() = default; //!< Defaulted.
    basic_sentinel(basic_sentinel const &) = default; //!< Defaulted.
    basic_sentinel(basic_sentinel &&) = default; //!< Defaulted.
    basic_sentinel & operator=(basic_sentinel const &) = default; //!< Defaulted.
    basic_sentinel & operator=(basic_sentinel &&) = default; //!< Defaulted.
    ~basic_sentinel() = default; //!< Defaulted.
```

File: include/seqan3/range/views/take_until.hpp [hunk 23]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    /*!\name Constructors, destructor and assignment
+     * \brief Exceptions specification is implicitly inherited.
+     * \{
+     */
+    constexpr basic_consume_iterator()                                               = default; //!< Defaulted.
+    constexpr basic_consume_iterator(basic_consume_iterator const & rhs)             = default; //!< Defaulted.
+    constexpr basic_consume_iterator(basic_consume_iterator && rhs)                  = default; //!< Defaulted.
+    constexpr basic_consume_iterator & operator=(basic_consume_iterator const & rhs) = default; //!< Defaulted.
+    constexpr basic_consume_iterator & operator=(basic_consume_iterator && rhs)      = default; //!< Defaulted.
+    ~basic_consume_iterator()                                                        = default; //!< Defaulted.
```
Comment (marehr) [inline include/seqan3/range/views/take_until.hpp:316]:
```suggestion
    constexpr basic_consume_iterator() = default; //!< Defaulted.
    constexpr basic_consume_iterator(basic_consume_iterator const & rhs) = default; //!< Defaulted.
    constexpr basic_consume_iterator(basic_consume_iterator && rhs) = default; //!< Defaulted.
    constexpr basic_consume_iterator & operator=(basic_consume_iterator const & rhs) = default; //!< Defaulted.
    constexpr basic_consume_iterator & operator=(basic_consume_iterator && rhs) = default; //!< Defaulted.
    ~basic_consume_iterator() = default; //!< Defaulted.
```

File: include/seqan3/range/views/take_until.hpp [hunk 24]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+            if constexpr (or_throw)
+                throw unexpected_end_of_input{"Reached end of input before functor evaluated to true."};
+            else
+                return true;
+        }
+
+        return rhs.predicate(*lhs);
+    }
+
+    //!\brief Switch lhs and rhs for comparison.
```
Comment (rrahn) [inline include/seqan3/range/views/take_until.hpp:491]:
```suggestion
    //!\brief Compares `lhs` with `rhs` for equality.
```

File: include/seqan3/range/views/take_until.hpp [hunk 25]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+          predicate{other.predicate}
+    {}
+    //!\}
+
+    /*!\name Comparison operators
+     * \brief We define comparison against the sentinel.
+     * \{
+     */
+
+    //!\brief Evaluate functor, possibly throw.
```
Comment (rrahn) [inline include/seqan3/range/views/take_until.hpp:475]:
```suggestion
    /*!\brief Compares `lhs` with `rhs` for equality.
     * 
     * \details
     *
     * Invokes the stored predicate with the pointed-to element from `lhs` and returns the result of this evaluation.
     * If the end of the underlying range was reached before the predicate evaluated to `true` and the view has 
     * `or_throw` enabled, then a seqan3::unexpected_end_of_input exception will be thrown, otherwise the returned
     * value is `true`.
     */
```

File: include/seqan3/range/views/take_until.hpp [hunk 26]
```diff
@@ -465,6 +204,312 @@ class view_take_until : public std::ranges::view_interface<view_take_until<urng_
...
+    //!\brief Construct from a not const range a const range.
+    basic_sentinel(basic_sentinel<!is_const_range> other)
+        requires is_const_range && std::convertible_to<std::ranges::sentinel_t<urng_t>, urng_sentinel_type>
+        : urng_sentinel{std::move(other.urng_sentinel)},
+          predicate{other.predicate}
+    {}
+    //!\}
+
+    /*!\name Comparison operators
+     * \brief We define comparison against the sentinel.
```
Comment (rrahn) [inline include/seqan3/range/views/take_until.hpp:471]:
```suggestion
```
