### PR TITLE
some fixes file iterators and views, new tests

### LINKED ISSUE #487: sequence_file_input and view::take don't work together
```c++
    sequence_file_input query_file{query_file_path, fields<field::ID, field::SEQ>{}};
    for (auto & [id, query] : query_file | view::take(30))
    {
        debug_stream << "id:\t\t" << id << '\n';
        debug_stream << "query:\t\t" << query << '\n';
    }
```
won't compile and outputs:

```
In file included from /seqan3/include/seqan3/range/view/take.hpp:50,
                 from /seqan3/include/seqan3/io/sequence_file/format_fasta.hpp:67,
                 from /seqan3/include/seqan3/io/sequence_file/input.hpp:63,
                 from /SeqAn3_read_mapper/mapper.cpp:2:
/seqan3/include/seqan3/range/detail/inherited_iterator_base.hpp: In instantiation of ‘class seqan3::detail::inherited_iterator_base<seqan3::detail::view_take<ranges::v3::iterator_range<seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > >, ranges::v3::default_sentinel>, false, false>::iterator_type, seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > > >’:
/seqan3/include/seqan3/range/view/take.hpp:88:11:   required from ‘class seqan3::detail::view_take<ranges::v3::iterator_range<seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > >, ranges::v3::default_sentinel>, false, false>::iterator_type’
/SeqAn3_read_mapper/mapper.cpp:75:57:   required from here
/seqan3/include/seqan3/range/detail/inherited_iterator_base.hpp:83:89: error: no type named ‘difference_type’ in ‘struct std::iterator_traits<seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > > >’
     using difference_type       = typename std::iterator_traits<base_t>::difference_type;
                                                                                         ^
/seqan3/include/seqan3/range/detail/inherited_iterator_base.hpp:84:84: error: no type named ‘value_type’ in ‘struct std::iterator_traits<seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > > >’
     using value_type            = typename std::iterator_traits<base_t>::value_type;
                                                                                    ^
/seqan3/include/seqan3/range/detail/inherited_iterator_base.hpp:85:83: error: no type named ‘reference’ in ‘struct std::iterator_traits<seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > > >’
     using reference             = typename std::iterator_traits<base_t>::reference;
                                                                                   ^
/seqan3/include/seqan3/range/detail/inherited_iterator_base.hpp:86:81: error: no type named ‘pointer’ in ‘struct std::iterator_traits<seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > > >’
     using pointer               = typename std::iterator_traits<base_t>::pointer;
                                                                                 ^
/seqan3/include/seqan3/range/detail/inherited_iterator_base.hpp:87:91: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<seqan3::detail::in_file_iterator<seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_dna, seqan3::fields<(seqan3::field)1, (seqan3::field)0>, meta::v1::list<seqan3::sequence_file_format_fasta, seqan3::sequence_file_format_fastq>, std::basic_ifstream<char> > > >’
     using iterator_category     = typename std::iterator_traits<base_t>::iterator_category;
                                                                                           ^
```

I'm not sure if this is intended or if this is a bug.

### PR DESCRIPTION
**Pull request by h-2**
fixes #487

### CODE REVIEW

File: include/seqan3/range/view/detail.hpp [hunk 1]
```diff
@@ -60,6 +60,26 @@ namespace seqan3::detail
 struct view_base : public ranges::view_base
 {};
 
+// ============================================================================
+//  size_type_t_or_void
+// ============================================================================
+
+//!\brief TransformationTrait that resolves to seqan3::size_type_t if possible and void otherwise. [Default Overload]
```
Comment (rrahn) [inline include/seqan3/range/view/detail.hpp]: Transformation trait

File: include/seqan3/range/view/detail.hpp [hunk 2]
```diff
@@ -60,6 +60,26 @@ namespace seqan3::detail
...
+    //!\brief The default is to expose `void`.
+    using type = void;
+};
+
+//!\brief TransformationTrait that resolves to seqan3::size_type_t if possible and void otherwise. [Specialisation]
+template <std::ranges::SizedRange t>
+struct size_type_t_or_void<t>
+{
+    //!\brief For sized ranges the seqan3::size_type_t is exposed.
+    using type = size_type_t<t>;
```
Comment (rrahn) [inline include/seqan3/range/view/detail.hpp]: there is a size_type_t mf? Does this wrap some ranges code or is it our own?
Just curious.

File: test/unit/io/sequence_file/sequence_file_integration_test.cpp [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+#include <seqan3/range/view/take.hpp>
+#include <seqan3/test/tmp_filename.hpp>
+#include <seqan3/std/iterator>
+
+using namespace seqan3;
+using namespace seqan3::literal;
+
+TEST(rows, assign_sequence_files)
+{
+    std::string const input // differs from output above by formatting
```
Comment (marehr) [inline test/unit/io/sequence_file/sequence_file_integration_test.cpp]: I don't understand this comment.

File: test/unit/io/sequence_file/sequence_file_integration_test.cpp [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+        "GGAGTATAATATATATATATATAT\n"
+    };
+
+    // valid without assignment?
+    sequence_file_input{std::istringstream{input}, sequence_file_format_fasta{}} |
+        sequence_file_output{std::ostringstream{}, sequence_file_format_fasta{}};
+
+    // valid with assignment and check contents
+    auto fout = sequence_file_input{std::istringstream{input}, sequence_file_format_fasta{}} |
+                sequence_file_output{std::ostringstream{}, sequence_file_format_fasta{}};
```
Comment (marehr) [inline test/unit/io/sequence_file/sequence_file_integration_test.cpp]: Can you shortly explain why this works without `view::persist`, but...

File: test/unit/io/sequence_file/sequence_file_integration_test.cpp [hunk 5]
```diff
@@ -0,0 +1,165 @@
...
+    {
+        "> TEST1\n"
+        "ACGT\n"
+        "> Test2\n"
+        "AGGCTGNAGGCTGAGGCTGNAGGCTGNAGGCTGNAGGCTGNAGGCTGNAGGCTGNAGGCTGN\n"
+    };
+
+    // valid without assignment?
+    sequence_file_input{std::istringstream{input}, sequence_file_format_fasta{}} | view::persist | view::take(2) |
+        sequence_file_output{std::ostringstream{}, sequence_file_format_fasta{}};
```
Comment (marehr) [inline test/unit/io/sequence_file/sequence_file_integration_test.cpp]: ... this doesn't? Is it because `view::take` is not rvalue aware?

File: include/seqan3/range/view/detail.hpp [hunk 6]
```diff
@@ -60,6 +60,26 @@ namespace seqan3::detail
...
+
+//!\brief TransformationTrait that resolves to seqan3::size_type_t if possible and void otherwise. [Default Overload]
+template <typename t>
+struct size_type_t_or_void
+{
+    //!\brief The default is to expose `void`.
+    using type = void;
+};
+
+//!\brief TransformationTrait that resolves to seqan3::size_type_t if possible and void otherwise. [Specialisation]
```
Comment (marehr) [inline include/seqan3/range/view/detail.hpp]: Transformation trait

File: include/seqan3/range/view/persist.hpp [hunk 7]
```diff
@@ -87,7 +87,7 @@ class view_persist : public ranges::view_interface<view_persist<urng_t>>
     //!\brief The value_type (which equals the reference_type with any references removed).
     using value_type        = value_type_t<urng_t>;
     //!\brief The size_type is `size_t` if the the view is exact, otherwise void.
-    using size_type         = std::conditional_t<std::ranges::SizedRange<urng_t>, size_type_t<urng_t>, void>;
+    using size_type         = typename detail::size_type_t_or_void<urng_t>::type;
```
Comment (marehr) [inline include/seqan3/range/view/persist.hpp]: Do we need `detail::size_type_t_or_void<urng_t>::type` a lot in the near future? I found the previous line okay and I think we could live without this rather specific meta function.

File: test/unit/io/sequence_file/sequence_file_integration_test.cpp (hunk 3 above)
Comment (h-2) [reply test/unit/io/sequence_file/sequence_file_integration_test.cpp]: copy'n'paste error

File: test/unit/io/sequence_file/sequence_file_integration_test.cpp (hunk 5 above)
Comment (h-2) [reply test/unit/io/sequence_file/sequence_file_integration_test.cpp]: views don't take rvalues, but sequence_file_out is not a view :wink:

File: include/seqan3/range/view/persist.hpp (hunk 7 above)
Comment (h-2) [reply include/seqan3/range/view/persist.hpp]: > I found the previous line okay

I did, too, but the compiler unfortunately didn't! The problem was that for non sized ranges, the metafunction `size_type_t` is not defined at all and this would lead to an error. I needed to add the other metafunction to work around this, I wouldn't have done it otherwise :expressionless:

File: include/seqan3/range/view/detail.hpp [hunk 8]
```diff
@@ -60,6 +60,26 @@ namespace seqan3::detail
...
+template <std::ranges::SizedRange t>
+struct size_type_t_or_void<t>
```
Comment (rrahn) [inline include/seqan3/range/view/detail.hpp]: maybe this could simply be a mf alias with a conditional

Comment (h-2) [reply include/seqan3/range/view/detail.hpp]: It would cause the same problem we are trying to solve with this metafunction, or not?
