### PR TITLE
[FIX] make view::take consume also at the very beginning.

### LINKED ISSUE #950: [BUG] in view_take_until_and_consume
If you add the following test to `take_line` it fails:
```cpp
TEST(view_take_line, eol_at_first_position)
{
    using sbt = std::istreambuf_iterator<char>;
    std::istringstream vec{"\nfoo"};
    auto stream_view = std::ranges::subrange<decltype(sbt{vec}), decltype(sbt{})> {sbt{vec}, sbt{}};
    EXPECT_EQ("", std::string(stream_view | view::take_line));
    EXPECT_EQ("foo", std::string(stream_view | view::take_line));
}

```

The problem is, that the iterator does not consume upon comparison, only upon incrementing which lets an input stream with take_line run into an infinite loop when the very first character is a character that evaluates `fun` to `true`.

I swa no elegant solution at first glance.

### PR DESCRIPTION
**Pull request by smehringer**
Resolves #950

### CODE REVIEW

File: include/seqan3/range/view/take_until.hpp [hunk 1]
```diff
@@ -235,17 +235,18 @@ class view_take_until : public ranges::view_interface<view_take_until<urng_t, fu
...
                                     sentinel_type sen) noexcept(noexcept(base_t{it})) :
             base_t{std::move(it)}, fun{_fun}, stored_end{std::move(sen)}
-        {}
+        {
+            while (fun(**this))
+            {
+                at_end_gracefully = true;
+                base_t::operator++();
+            }
+        }
```
Comment (h-2) [inline include/seqan3/range/view/take_until.hpp]: This invokes UB on multiple ocasions, because you never check at end. I would recommend doing
```cpp
if ((*this->this_to_base() != stored_end) && fun(**this))
    ++(*this);
```
The increment operator will take care of the rest.

Comment (smehringer) [reply include/seqan3/range/view/take_until.hpp]: this is not completely correct because you skip the first character that evaluated to true and `at_end_gracefully` was not set :o

Comment (smehringer) [reply include/seqan3/range/view/take_until.hpp]: any preference?

Comment (h-2) [reply include/seqan3/range/view/take_until.hpp]: either is fine
