### PR TITLE
[FIX] Incorrect copy/move of fm_index

### LINKED ISSUE #1121: Processing returned ranges from search segfaults
I have the following code, compiled with GCC 7.2.0 (c++17) and SeqAn 3.0.0:
```
void seq_search(const dna5_vector& query, const std::vector<fm_index<true,default_sdsl_index_type>& seq_idx)
{
   for (auto ref_it = seq_idx.begin(); ref_it != seq_idx.end(); ref_it++)
   {
      auto results = search(query, *ref_it);
      debug_stream << "There are " << results.size() << " hits.\n";
      debug_stream << results << '\n';
      if (results.size() > 0)
      {
         std::cerr << "found" << std::endl;
      }
   }
}
```
If `query` cannot be found then it's ok, but as soon as there is a match I get a segfault, I think at `results.size() > 0`. The number of hits doesn't print, and the result print line appears as `[1]` (which is wrong).

Any ideas what is causing this?
Is this because my libgcc/libstdc++ doesn't have an implementation of ranges?

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #1121

### CODE REVIEW

File: include/seqan3/search/fm_index/fm_index.hpp [hunk 1]
```diff
@@ -178,12 +178,25 @@ class fm_index
     /*!\name Constructors, destructor and assignment
      * \{
      */
-    fm_index() = default;                             //!< Default constructor.
-    fm_index(fm_index const &) = default;             //!< Copy constructor.
-    fm_index & operator=(fm_index const &) = default; //!< Copy assignment.
-    fm_index(fm_index &&) = default;                  //!< Move constructor.
-    fm_index & operator=(fm_index &&) = default;      //!< Move assignment.
-    ~fm_index() = default;                            //!< Destructor.
+    fm_index() = default;              //!< Default constructor.
```
Comment (smehringer) [inline include/seqan3/search/fm_index/fm_index.hpp]:
```suggestion
    fm_index() = default;              //!< Defaulted.
```

File: include/seqan3/search/fm_index/fm_index.hpp [hunk 2]
```diff
@@ -178,12 +178,25 @@ class fm_index
...
+    fm_index(fm_index const & rhs)     //!< Copy constructor.
```
Comment (smehringer) [inline include/seqan3/search/fm_index/fm_index.hpp]: If the constructor is not defaulted write why into the brief.

File: include/seqan3/search/fm_index/fm_index.hpp [hunk 3]
```diff
@@ -438,6 +452,34 @@ class fm_index
...
+        swap(lhs.text_begin, rhs.text_begin);
+        swap(lhs.text_begin_ss, rhs.text_begin_ss);
+        swap(lhs.text_begin_rs, rhs.text_begin_rs);
+
+        lhs.text_begin_ss.set_vector(&lhs.text_begin);
+        lhs.text_begin_rs.set_vector(&lhs.text_begin);
+        rhs.text_begin_ss.set_vector(&rhs.text_begin);
+        rhs.text_begin_rs.set_vector(&rhs.text_begin);
+    }
+
```
Comment (h-2) [inline include/seqan3/search/fm_index/fm_index.hpp]: Since C++11 Copy'n'swap is typically implemented like this:

  * copy constructor with copy implementation
  * move constructor with move implementation
  * assignment operator that takes by value and std::swaps
  * You very rarely need to define a `.swap()` member since C++11. Always use std::swap which uses the move constructor automatically.

File: include/seqan3/search/fm_index/fm_index.hpp [hunk 4]
```diff
@@ -178,12 +178,26 @@ class fm_index
...
      * \{
      */
-    fm_index() = default;                             //!< Default constructor.
-    fm_index(fm_index const &) = default;             //!< Copy constructor.
-    fm_index & operator=(fm_index const &) = default; //!< Copy assignment.
-    fm_index(fm_index &&) = default;                  //!< Move constructor.
-    fm_index & operator=(fm_index &&) = default;      //!< Move assignment.
-    ~fm_index() = default;                            //!< Destructor.
+    fm_index() = default;              //!< Defaulted.
+    fm_index(fm_index const & rhs)     //!< When copy constructing, also set the pointers of rank and select support.
```
Comment (h-2) [inline include/seqan3/search/fm_index/fm_index.hpp]: Do users of the fm_index (need to) know what rank and select support are?

File: include/seqan3/search/fm_index/fm_index.hpp (hunk 3 above)
Comment (h-2) [reply include/seqan3/search/fm_index/fm_index.hpp]: I would write it like this:

```cpp
fm_index(fm_index const & rhs) :
    index{rhs.index}, sigma{rhs.sigma}, text_begin{rhs.text_begin}, text_begin_ss{rhs.text_begin_ss}
{
    text_begin_ss.set_vector(&text_begin);
    text_begin_rs.set_vector(&text_begin);
}

fm_index(fm_index && rhs) :
    index{std::move(rhs.index)}, sigma{std::move(rhs.sigma)}, text_begin{std::move(rhs.text_begin)}, text_begin_ss{std::move(rhs.text_begin_ss)}
{
    text_begin_ss.set_vector(&text_begin);
    text_begin_rs.set_vector(&text_begin);
}

fm_index & operator=(fm_index rhs) //!< Delegate to swap().
{
    std::swap(*this, rhs);
    return *this;
}
```

This clearly highlights that only thing non-standard that happens is calling `set_vector` for two members.

Comment (eseiler) [reply include/seqan3/search/fm_index/fm_index.hpp]: Mhm, using `std::swap` segfaults. It doesn't seem to set the pointers correctly.

File: include/seqan3/search/fm_index/fm_index.hpp (hunk 4 above)
Comment (eseiler) [reply include/seqan3/search/fm_index/fm_index.hpp]: `When copy constructing, also update internal data structures.` ?

File: include/seqan3/search/fm_index/fm_index.hpp (hunk 3 above)
Comment (h-2) [reply include/seqan3/search/fm_index/fm_index.hpp]: Hm, that sounds weird. Then again, maybe std::swap uses assignment which uses std::swap ... :thinking: 

In any case, if it works now and `std::swap` works now as well, we could also just put move assignment of the member into the assignment operator and get rid of the swap member, or not? I really don't like having a swap member, it looks weird :innocent:

Comment (eseiler) [reply include/seqan3/search/fm_index/fm_index.hpp]: > Hm, that sounds weird. Then again, maybe std::swap uses assignment which uses std::swap ... 🤔
> 

It kinda looked like it in the debugger.
> In any case, if it works now and `std::swap` works now as well, we could also just put move assignment of the members (no swap required) into the assignment operator and get rid of the swap member, or not? I really don't like having a swap member, it looks weird 😇
Ok, done!
