### PR TITLE
[FIX] Remove temporary files

### LINKED ISSUE #1292: Temporary directories/files not cleaned up correctly
We are not removing directories created by
```
structure_file_output_test
alignment_file_output_test
sequence_file_output_test
```

In these tests we create a non-existent directory (`I/do/not/exist.{dbn,sam,fasta}`). 
The destructor will call 
https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/test/include/seqan3/test/tmp_filename.hpp#L111
Which only deletes the parent directory, i.e. `I/do/not`, leaving the temporary directory intact.

Also snippets create multiple files that are not cleaned up afterwards...

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #1292 

Also see [this card](https://github.com/orgs/seqan/projects/4#card-27661279)

### CODE REVIEW

File: doc/tutorial/alignment_file/alignment_file_snippets.cpp [hunk 1]
```diff
@@ -24,6 +24,11 @@ r001	147	ref	37	30	9M	=	7	-39	CAGCGGCAT	*	NM:i:1
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"example.sam");
```
Comment (rrahn) [inline doc/tutorial/alignment_file/alignment_file_snippets.cpp]: please use the non throwing version of remove. and output a debug message that it could not remove together with the error code. should we have at some point snippet tests (testing against the output we might spot the issue much easier) Otherwise the program just terminates.

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp [hunk 2]
```diff
@@ -31,6 +31,12 @@ r003	2064	chr2	18	10	5M	*	0	0	TAGGC	*
         std::string fasta_file_rawstr{fasta_file_raw};
         reffile << fasta_file_rawstr.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"mapping.sam");
```
Comment (rrahn) [inline doc/tutorial/alignment_file/alignment_file_solution2.cpp]: same here

File: doc/tutorial/sequence_file/sequence_file_snippets.cpp [hunk 3]
```diff
@@ -38,16 +38,23 @@ AGCGATCGAGGAATATAT
...
         file2 << str.substr(1); // skip first newline
 
-        std::ofstream file3{"/tmp/my.fasta"};
+        std::ofstream file3{std::filesystem::temp_directory_path()/"my.fasta"};
         file3 << ">seq1\nAVAV\n>seq2\nAVAVA\n";
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"my.fastq");
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_snippets.cpp]: same here

File: doc/tutorial/sequence_file/sequence_file_snippets.cpp [hunk 4]
```diff
@@ -147,22 +154,29 @@ for (auto & rec : fin | minimum_quality_filter)
...
-sequence_file_output{"/tmp/output.fasta"} = sequence_file_input{"/tmp/my.fastq"};
+auto tmp_dir = std::filesystem::temp_directory_path();
+
+sequence_file_output{tmp_dir/"output.fasta"} = sequence_file_input{tmp_dir/"my.fastq"};
 //![file_conversion]
 }
 
+std::filesystem::remove(std::filesystem::temp_directory_path()/"output.fasta");
+std::filesystem::remove(std::filesystem::temp_directory_path()/"output.fastq");
+
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_snippets.cpp]: superfluous empty line

File: doc/tutorial/sequence_file/sequence_file_solution1.cpp [hunk 5]
```diff
@@ -26,6 +26,11 @@ IIIIHHGIIIIHHGIIIH
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"my.fastq");
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution1.cpp]: same here

File: doc/tutorial/sequence_file/sequence_file_solution2.cpp [hunk 6]
```diff
@@ -18,6 +18,11 @@ CGATCGA
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"my.fastq");
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution2.cpp]: same here

File: doc/tutorial/sequence_file/sequence_file_solution3.cpp [hunk 7]
```diff
@@ -34,6 +34,11 @@ IIIIIHIIJJIIIII
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"my.fastq");
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution3.cpp]: same here

File: doc/tutorial/sequence_file/sequence_file_solution4.cpp [hunk 8]
```diff
@@ -34,6 +34,11 @@ IIIIIHIIJJIIIII
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"my.fastq");
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution4.cpp]: same here

File: doc/tutorial/sequence_file/sequence_file_solution5.cpp [hunk 9]
```diff
@@ -34,6 +34,11 @@ IIIIIHIIJJIIIII
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::filesystem::remove(std::filesystem::temp_directory_path()/"my.fastq");
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution5.cpp]: same here

File: test/include/seqan3/test/tmp_filename.hpp [hunk 10]
```diff
@@ -93,22 +93,22 @@ class tmp_filename
...
-                                           tmp_base_dir,
-                                           std::make_error_code(std::errc::bad_file_descriptor));
+                                                tmp_base_dir,
+                                                std::make_error_code(std::errc::bad_file_descriptor));
     }
 
-    /*!\brief Destructs the temporary file path.
-     * Removes the temporary directory and all it's subdirectories and files contained.
+    /*!\brief Destructs the temporary directory path.
+     * Removes the temporary directory and all its subdirectories and files contained.
```
Comment (rrahn) [inline test/include/seqan3/test/tmp_filename.hpp]:
```suggestion
     *
     * \details
     *
     * Removes the temporary directory and all its subdirectories and files contained.
```

File: doc/tutorial/alignment_file/alignment_file_snippets.cpp (hunk 1 above)
Comment (eseiler) [reply doc/tutorial/alignment_file/alignment_file_snippets.cpp]: debug message = std::cerr ?

I'll also have to change this in the ones that already exist and I copied from

Comment (rrahn) [reply doc/tutorial/alignment_file/alignment_file_snippets.cpp]: > debug message = std::cerr ?

I think using debug_stream would be ok. The plan in the future would be to compare the output of the snippet against a gold standard. So if there is an error message in between we then see that the test fails and see also what happened in the diff of the outputs. 

> I'll also have to change this in the ones that already exist and I copied from

I hope I caught all of them

File: test/include/seqan3/test/tmp_filename.hpp (hunk 10 above)
Comment (eseiler) [reply test/include/seqan3/test/tmp_filename.hpp]: test/include docs are not build anyway 🤷‍♂

File: doc/tutorial/sequence_file/sequence_file_solution4.cpp [hunk 11]
```diff
@@ -67,5 +74,7 @@ int main()
     {
         fout.push_back(rec);
     }
-}
+SEQAN3_DOXYGEN_ONLY(})
```
Comment (eseiler) [inline doc/tutorial/sequence_file/sequence_file_solution4.cpp]: Is this ok?
It does exactly what I want without touching the actual documentation.
Otherwise we would have to split it into two snippets...

File: doc/tutorial/sequence_file/sequence_file_snippets.cpp [hunk 12]
```diff
@@ -38,16 +40,37 @@ AGCGATCGAGGAATATAT
...
 
-        std::ofstream file3{"/tmp/my.fasta"};
+        std::ofstream file3{tmp_path/"my.fasta"};
         file3 << ">seq1\nAVAV\n>seq2\nAVAVA\n";
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
+        std::filesystem::path file_path();
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_snippets.cpp]:
```suggestion
        std::filesystem::path file_path{};
```

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp [hunk 13]
```diff
@@ -23,14 +27,31 @@ r004	0	chr2	16	60	6M14N5M	*	0	0	ATAGCTTCAGC	*
...
-        std::ofstream reffile{std::filesystem::temp_directory_path()/"reference.fasta"};
+        std::ofstream reffile{tmp_path/"reference.fasta"};
         std::string fasta_file_rawstr{fasta_file_raw};
         reffile << fasta_file_rawstr.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
+        std::filesystem::path file_path();
```
Comment (rrahn) [inline doc/tutorial/alignment_file/alignment_file_solution2.cpp]:
```suggestion
        std::filesystem::path file_path{};
```

File: doc/tutorial/alignment_file/alignment_file_snippets.cpp [hunk 14]
```diff
@@ -20,10 +24,19 @@ r003	2064	ref	29	17	5M	*	0	0	TAGGC	*
...
 
-        std::ofstream file{std::filesystem::temp_directory_path()/"example.sam"};
+        std::ofstream file{file_path};
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
```
Comment (rrahn) [inline doc/tutorial/alignment_file/alignment_file_snippets.cpp]:
```suggestion
        std::error_code ec{};
```

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp [hunk 15]
```diff
@@ -23,14 +27,31 @@ r004	0	chr2	16	60	6M14N5M	*	0	0	ATAGCTTCAGC	*
...
 
-        std::ofstream reffile{std::filesystem::temp_directory_path()/"reference.fasta"};
+        std::ofstream reffile{tmp_path/"reference.fasta"};
         std::string fasta_file_rawstr{fasta_file_raw};
         reffile << fasta_file_rawstr.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
```
Comment (rrahn) [inline doc/tutorial/alignment_file/alignment_file_solution2.cpp]:
```suggestion
        std::error_code ec{};
```

File: doc/tutorial/sequence_file/sequence_file_snippets.cpp [hunk 16]
```diff
@@ -38,16 +40,37 @@ AGCGATCGAGGAATATAT
...
         file2 << str.substr(1); // skip first newline
 
-        std::ofstream file3{"/tmp/my.fasta"};
+        std::ofstream file3{tmp_path/"my.fasta"};
         file3 << ">seq1\nAVAV\n>seq2\nAVAVA\n";
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_snippets.cpp]:
```suggestion
        std::error_code ec{};
```

File: doc/tutorial/sequence_file/sequence_file_solution1.cpp [hunk 17]
```diff
@@ -22,10 +25,19 @@ AGCGATCGAGGAATATAT
...
 
-        std::ofstream file{std::filesystem::temp_directory_path()/"my.fastq"};
+        std::ofstream file{file_path};
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution1.cpp]:
```suggestion
        std::error_code ec{};
```

File: doc/tutorial/sequence_file/sequence_file_solution2.cpp [hunk 18]
```diff
@@ -14,10 +17,19 @@ AGCT
...
 
-        std::ofstream file{std::filesystem::temp_directory_path()/"my.fasta"};
+        std::ofstream file{file_path};
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution2.cpp]:
```suggestion
        std::error_code ec{};
```

File: doc/tutorial/sequence_file/sequence_file_solution3.cpp [hunk 19]
```diff
@@ -30,10 +33,19 @@ AGCTAGCAGCGATCG
...
 
-        std::ofstream file{std::filesystem::temp_directory_path()/"my.fastq"};
+        std::ofstream file{file_path};
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution3.cpp]:
```suggestion
        std::error_code ec{};
```

File: doc/tutorial/sequence_file/sequence_file_solution4.cpp [hunk 20]
```diff
@@ -30,10 +33,19 @@ AGCTAGCAGCGATCG
...
 
-        std::ofstream file{std::filesystem::temp_directory_path()/"my.fastq"};
+        std::ofstream file{file_path};
         std::string str{file_raw};
         file << str.substr(1); // skip first newline
     }
+
+    ~write_file_dummy_struct()
+    {
+        std::error_code ec;
```
Comment (rrahn) [inline doc/tutorial/sequence_file/sequence_file_solution4.cpp]:
```suggestion
        std::error_code ec{};
```

File: test/include/seqan3/test/tmp_filename.hpp (hunk 10 above)
Comment (rrahn) [reply test/include/seqan3/test/tmp_filename.hpp]: yes, that would be true. But why then using brief anyway? So either following the style guide 100% or not at all 😏

Comment (eseiler) [reply test/include/seqan3/test/tmp_filename.hpp]: Just saying :)
