### PR TITLE
Partially Revert "[FIX] travis/ubuntu16.04: gcc-7.2 bug"

### LINKED ISSUE #264: revert `sequence_concept` workaround for travis-ci / ubuntu 14.04/16.04
I introduced `sequence_concept_modified_by_const_iterator_bug` to workaround an issue that was only present in the [gcc-7.2.0 ppa](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=trusty).

The rational was that ubuntu/debain users that are still on trusty (14.04) or xenial (16.04) have no easy way of installing gcc-7 without this ppa.

On 2018/04/24 the gcc version was updated to 7.3 and [travis](https://travis-ci.org/seqan/seqan3/jobs/385692703) already uses this version, so we should revisit this issue and remove the workaround.

See commit 5ba75261f785259adf8b49e0cf41ce818f481e8a and pr #113.

----
split from  #255

### PR DESCRIPTION
**Pull request by marehr**
This reverts commit 5ba75261f785259adf8b49e0cf41ce818f481e8a.

And resolves #264 

---

Edit:// this is still failing: The reason is that gcc-7 for 14.04 is compiled with disabling dual abi, see #264 for more information.

Edit:// rechecked 2019-06-05

### CODE REVIEW

**Comment by marehr** [comment]
closing for now

**Comment by marehr** [comment]
because of popular demand in #264, let's retry the revert

**Comment by marehr** [comment]
Looks good, seems that we can revert this.

https://travis-ci.org/marehr/seqan3/builds/541751115

File: include/seqan3/range/container/concept.hpp [hunk 1]
```diff
@@ -204,20 +158,18 @@ SEQAN3_CONCEPT SequenceContainer = requires (type val, type val2, type const cva
     // modify container
     // TODO: how do you model this?
     // { val.emplace(typename type::const_iterator{}, ?                                   } -> typename type::iterator;
+    { val.insert(val.cbegin(), val2.front())                                           } -> typename type::iterator;
+    { val.insert(val.cbegin(), typename type::value_type{})                            } -> typename type::iterator;
+    { val.insert(val.cbegin(), typename type::size_type{}, typename type::value_type{})} -> typename type::iterator;
+    { val.insert(val.cbegin(), val2.begin(), val2.end())                               } -> typename type::iterator;
+    requires detail::is_basic_string_v<type> || requires(type val)
```
Comment (h-2) [inline include/seqan3/range/container/concept.hpp]: this is still required?

Comment (h-2) [reply include/seqan3/range/container/concept.hpp]: an improvement in any case

Comment (marehr) [reply include/seqan3/range/container/concept.hpp]: > This isn't going to be backported, because of the new symbols. So fixed for GCC 9 only.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83328#c8
