### PR TITLE
Fix/issue1801 custom thread count in alignment algorithm

### LINKED ISSUE #1801: The number of threads specified in align_cfg::parallel is not propagated to the thread pool of the alignment scheduler.
## Platform

  - SeqAn version: all
  - Operating system: all
  - Compiler: all

## Description

The number of threads specified in align_cfg::parallel is not propagated to the thread pool of the alignment scheduler.

### Expected behaviour

If the user specifies the number of threads the program spawns not more than the given number of threads.

### Actual behaviour

The program spawns as many threads as the system has available.

### PR DESCRIPTION
**Pull request by rrahn**
Fixes #1801

Allows to use only the thread count specified by the user.
Makes the algorithm_executor_blocking data structure constructible over the execution handler and sets the thread count set by the user for the parallel execution handler during the alignment configuration.

### CODE REVIEW

File: test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp [hunk 1]
```diff
@@ -217,3 +217,52 @@ TYPED_TEST(algorithm_executor_blocking_test, empty_result_bucket)
...
+    using algorithm_t = decltype(algorithm);
+    using executor_t =
+        seqan3::detail::algorithm_executor_blocking<std::vector<std::string> &,
+                                                    algorithm_t,
+                                                    size_t,
+                                                    seqan3::detail::execution_handler_parallel>;
+
+    // Allow at most 2 threads and then execute until no results are available anymore.
+    static constexpr size_t thread_count = 2u;
+    executor_t executor{sequences, algorithm, size_t{0}, seqan3::detail::execution_handler_parallel{thread_count}};
```
Comment (joergi-w) [inline test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp:251]: Would this work the same way?
```suggestion
    executor_t executor{sequences, algorithm, 0ull, seqan3::detail::execution_handler_parallel{thread_count}};
```

File: test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp [hunk 2]
```diff
@@ -217,3 +217,52 @@ TYPED_TEST(algorithm_executor_blocking_test, empty_result_bucket)
...
+//See issue: https://github.com/seqan/seqan3/issues/1801
+TEST(algorithm_executor_blocking_test, issue_1801)
+{
+    std::vector<std::thread::id> thread_ids{}; // Stores the thread ids.
+    std::mutex push_mutex{}; // Used to synchronise concurrent push back operation on the thread_ids vector.
+
+    using callback_t = std::function<void(size_t)>;
+    std::function algorithm = [&] (std::string const & seq, callback_t && callback)
+    {
+        { // Tell what thread is working.
```
Comment (joergi-w) [inline test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp:230]:
```suggestion
        { // Tell which thread is working.
```

File: include/seqan3/alignment/pairwise/align_pairwise.hpp [hunk 3]
```diff
@@ -167,28 +167,36 @@ constexpr auto align_pairwise(sequence_t && sequences,
...
     auto && [algorithm, complete_config] = detail::alignment_configurator::configure<decltype(seq_view)>(config);
 
-    using traits_t = detail::alignment_configuration_traits<remove_cvref_t<decltype(complete_config)>>;
-    //!brief Lambda function to translate specified parallel and or vectorised configurations into their execution rules.
-    constexpr auto get_execution_rule = [] ()
-    {
-        if constexpr (traits_t::is_parallel)
-            return seqan3::par;
-        else
-            return seqan3::seq;
```
Comment (joergi-w) [inline include/seqan3/alignment/pairwise/align_pairwise.hpp:177]: Are seqan3::par and seqan3::seq objects still used elsewhere or can they be deleted? It seems they have been replaced by detail::execution_handler_parallel and detail::execution_handler_sequential.

File: include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp [hunk 4]
```diff
@@ -156,17 +156,14 @@ class algorithm_executor_blocking
...
-    //!\endcond
     algorithm_executor_blocking(resource_t resource,
                                 algorithm_t algorithm,
                                 algorithm_result_t const SEQAN3_DOXYGEN_ONLY(result) = algorithm_result_t{},
-                                exec_policy_t const & SEQAN3_DOXYGEN_ONLY(exec) = seq) :
-        resource{std::views::all(resource)},
-        resource_it{std::ranges::begin(this->resource)},
-        algorithm{std::move(algorithm)}
+                                execution_handler_t && exec_handler = execution_handler_t{})
+        : exec_handler{std::move(exec_handler)},
```
Comment (joergi-w) [inline include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp:163]: Before the colon was on the previous line, now it is on the new line. Is the code style change intended?

File: include/seqan3/alignment/pairwise/align_pairwise.hpp (hunk 3 above)
Comment (rrahn) [reply include/seqan3/alignment/pairwise/align_pairwise.hpp:177]: No they are not needed anymore. They are publc API though. I would mark them deprecated instead. But in a separate PR. good point though.

File: include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp (hunk 4 above)
Comment (rrahn) [inline include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp:163]:
```suggestion
                                execution_handler_t && exec_handler = execution_handler_t{}) :
        exec_handler{std::move(exec_handler)},
```

File: test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp (hunk 1 above)
Comment (rrahn) [reply test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp:251]: In this case yes since the executor type is alreadt defined

File: include/seqan3/alignment/pairwise/align_pairwise.hpp (hunk 3 above)
Comment (joergi-w) [reply include/seqan3/alignment/pairwise/align_pairwise.hpp:177]: 👍

File: include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp [hunk 5]
```diff
@@ -156,17 +156,14 @@ class algorithm_executor_blocking
...
                                 algorithm_result_t const SEQAN3_DOXYGEN_ONLY(result) = algorithm_result_t{},
-                                exec_policy_t const & SEQAN3_DOXYGEN_ONLY(exec) = seq) :
-        resource{std::views::all(resource)},
-        resource_it{std::ranges::begin(this->resource)},
-        algorithm{std::move(algorithm)}
+                                execution_handler_t && exec_handler = execution_handler_t{}) :
+        exec_handler{std::move(exec_handler)},
+          resource{std::views::all(resource)},
+          resource_it{std::ranges::begin(this->resource)},
+          algorithm{std::move(algorithm)}
```
Comment (joergi-w) [inline include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp:166]: Now these lines became misaligned...

Comment (rrahn) [inline include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp:166]:
```suggestion
        exec_handler{std::move(exec_handler)},
        resource{std::views::all(resource)},
        resource_it{std::ranges::begin(this->resource)},
        algorithm{std::move(algorithm)}
```

File: include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp [hunk 6]
```diff
@@ -147,7 +147,7 @@ class algorithm_executor_blocking
      * \param[in] resource The underlying resource.
      * \param[in] algorithm The algorithm to invoke on the elements of the underlying resource.
      * \param[in] result A dummy result object to deduce the type of the underlying buffer value.
-     * \param[in] exec Optional execution policy to use. Defaults to seqan3::seq.
+     * \param[in] exec_handler Optional the execution handler to use.
```
Comment (smehringer) [inline include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp:150]:
```suggestion
     * \param[in] exec_handler The execution handler to use [optional].
```
?

File: CHANGELOG.md [hunk 7]
```diff
@@ -85,6 +85,12 @@ Note that 3.1.0 will be the first API stable release and interfaces in this rele
 
 ## Notable Bug-fixes
 
+### Alignment
+
+* When invoking the alignment algorithm with a user defined thread count using the `seqan3::align_cfg::parallel`
+  configuration always `std::thread::hardware_concurrency()` many threads were spawned. This is now fixed and only
```
Comment (smehringer) [inline CHANGELOG.md:91]:
```suggestion
  configuration element, `std::thread::hardware_concurrency()` many threads were always spawned. This is now fixed and only
```
