### PR TITLE
Fix minor issues and typos

### LINKED ISSUE #358: Collection of Minor issues and typos.
- [ ] File https://github.com/seqan/seqan3/blob/master/include/seqan3/alphabet/gap/all.hpp has no `#pragma once`

- [ ] The documentation group opened here has no closing bracket : https://github.com/seqan/seqan3/blob/master/include/seqan3/std/concept/core_language.hpp#L153

- [ ] The record code example is wrong (order of types and get according function) : http://docs.seqan.de/seqan/3.0.0-master-user/structseqan3_1_1record.html

- [ ] The `write_eol` function in IO has a wierd documentation as "\n" is displayed as an actual new line instead of the character: http://docs.seqan.de/seqan/3.0.0-master-dev/group__io.html#gaf387d6832c3e03849af06740694ada9c

- [ ] In many files the date is still `2016-2017` and needs to be updated.

### PR DESCRIPTION
**Pull request by eseiler**
This resolves #358

### CODE REVIEW

File: include/seqan3/std/concept/core_language.hpp [hunk 1]
```diff
@@ -150,7 +150,6 @@ concept bool nothrow_assignable_concept =           assignable_concept<t1, t2> &
  */
 /*!\name Requirements for seqan3::swappable_concept
  * \brief You can expect these functions on all types that implement seqan3::swappable_concept.
- * \{
```
Comment (h-2) [inline include/seqan3/std/concept/core_language.hpp]: instead of removing this, please add a closing brace after the next element

**Comment by h-2** [comment]
Thanks for fixing all the stuff, one minor thing!

File: include/seqan3/std/concept/core_language.hpp (hunk 1 above)
Comment (h-2) [reply include/seqan3/std/concept/core_language.hpp]: `//!\}`
