### PR TITLE
[MISC] Make deprecated values valid for usage within io.

### LINKED ISSUE #1452: uppercase field IDs are broken not deprecated
While keeping and deprecating the values might have been well-intended, it doesn't work anyway because the files complain that they don't know the values...

We are seriously breaking everything anyway, we might as well remove the uppercase version directly.

### PR DESCRIPTION
**Pull request by smehringer**
Resolves #1452

### CODE REVIEW

File: include/seqan3/io/record.hpp [hunk 1]
```diff
@@ -108,40 +108,40 @@ enum class field
...
-    USER_DEFINED_1 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_2 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_3 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_4 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_5 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_6 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_7 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_8 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
-    USER_DEFINED_9 SEQAN3_DEPRECATED_310, //!< Please use the field name in lower case.
+    SEQ SEQAN3_DEPRECATED_310 = seq,            //!< Please use the field name in lower case.
```
Comment (rrahn) [inline include/seqan3/io/record.hpp]: are you gonna fix the indentation issue? Maybe remove the indentation altogether?

Comment (rrahn) [reply include/seqan3/io/record.hpp]: 😁
