### PR TITLE
[FIX] empty sequences for edit_distance

### LINKED ISSUE #1111: edit_distance can't align with empty sequences.
The following cases will seg fault right now:

```c++
align_pairwise(["", ""]); // both empty for edit_distance
align_pairwise(["ACGT", ""]); // one empty for edit_distance
align_pairwise(["", "ACGT"]); // one empty for edit_distance
```

### PR DESCRIPTION
**Pull request by marehr**
This PR will fix
* don't seg-fault on empty sequences (resolves #1111)
* Fixes and tests some bugs with debug_matrix where you can't combine transformation-operations.

### CODE REVIEW

File: include/seqan3/alignment/matrix/debug_matrix.hpp [hunk 1]
```diff
@@ -156,8 +156,10 @@ class debug_matrix
 
         size_t const _row = !_transpose ? row : col;
         size_t const _col = !_transpose ? col : row;
+        size_t const _mask_row = _transpose == _transpose_mask ? row : col;
```
Comment (eseiler) [inline include/seqan3/alignment/matrix/debug_matrix.hpp]: Ah, so if both matrices are transposed (or both not transposed), we don't need to change anything, otherwise we need to transpose one of them?

File: include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp [hunk 2]
```diff
@@ -86,6 +86,14 @@ class edit_distance_unbanded_max_errors_policy :
         max_errors = get<align_cfg::max_error>(self->config).value;
         assert(max_errors >= score_type{0});
 
+        if (std::ranges::size(self->query) == 0) // [[unlikely]]
```
Comment (eseiler) [inline include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp]:
```suggestion
        if (std::ranges::empty(self->query)) // [[unlikely]]
```

File: include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp [hunk 3]
```diff
@@ -374,29 +382,14 @@ class edit_distance_unbanded_semi_global_policy :
...
     void update_best_score() noexcept
     {
         derived_t const * self = static_cast<derived_t const *>(this);
-        // we have to make sure that update_best_score is only called after a score update within the
-        // last row.
+        // we have to make sure that update_best_score is only called after a score update within the last row.
         if constexpr(edit_traits::use_max_errors)
         {
-            assert(self->is_last_active_cell_within_last_row());
+            assert(std::ranges::size(self->query) == 0u || self->is_last_active_cell_within_last_row());
```
Comment (eseiler) [inline include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp]:
```suggestion
            assert(std::ranges::empty(self->query) || self->is_last_active_cell_within_last_row());
```

File: include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp [hunk 4]
```diff
@@ -407,7 +400,9 @@ class edit_distance_unbanded_semi_global_policy :
     size_t back_coordinate_first() const noexcept
     {
         derived_t const * self = static_cast<derived_t const *>(this);
-        return std::ranges::distance(std::ranges::begin(self->database), _best_score_col) + 1u;
+        // offset == 0u is a special case if database sequence is empty, because in this case the best column is zero.
+        size_t offset = std::ranges::begin(self->database) == self->database_it_end ? 0u : 1u;
```
Comment (eseiler) [inline include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp]: Isn't the condition equivalent to `std::ranges::empty(self->database)` ?

File: include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp [hunk 5]
```diff
@@ -956,6 +951,31 @@ class edit_distance_unbanded :
     //!\brief Pattern is larger than one machine word. Use overflow aware computation.
     inline bool large_patterns();
 
+    //!\brief Special case if query sequence is empty.
+    inline void compute_empty_query_sequence()
+    {
+        assert(std::ranges::size(query) == 0u);
```
Comment (eseiler) [inline include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp]:
```suggestion
        assert(std::ranges::empty(query));
```

File: include/seqan3/alignment/matrix/debug_matrix.hpp (hunk 1 above)
Comment (marehr) [reply include/seqan3/alignment/matrix/debug_matrix.hpp]: Yeah unfortunately :(

File: include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp (hunk 4 above)
Comment (marehr) [reply include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp]: true, thank you.

**Comment by marehr** [comment]
@eseiler I worked your changes in, can you have a second look? :>

File: include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp [hunk 6]
```diff
@@ -956,6 +951,31 @@ class edit_distance_unbanded :
...
+        assert(std::ranges::empty(query));
+
+        bool abort_computation = false;
+
+        for (; database_it != database_it_end; ++database_it)
+        {
+            if constexpr(is_global)
+                ++_score;
+
+            if constexpr(is_semi_global)
```
Comment (rrahn) [inline include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp]: can both be valid at the same time? Why not if else then?

File: test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_max_errors_unbanded_test.cpp [hunk 7]
```diff
@@ -30,11 +25,77 @@ using semi_global_edit_distance_max_errors_unbanded_types
...
+
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e255, uint8_t>,
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e255, uint16_t>,
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e255, uint32_t>,
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e255, uint64_t>,
+
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e0, uint8_t>,
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e0, uint16_t>,
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e0, uint32_t>,
+        semi_global_fixture<&semi_global::edit_distance::max_errors::unbanded::dna4_03_e0, uint64_t>
```
Comment (rrahn) [inline test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_max_errors_unbanded_test.cpp]: and this compiles in reasonable time?

Comment (rrahn) [reply test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_max_errors_unbanded_test.cpp]: Would it make sense to split this into multiple translation units if not?

File: test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp [hunk 8]
```diff
@@ -278,6 +278,130 @@ static auto dna4_02_s10u_15u_e7 = []()
     };
 }();
 
+static auto dna4_02_s1u_15u_e255 = []()
```
Comment (rrahn) [inline test/unit/alignment/pairwise/fixture/global_edit_distance_max_errors_unbanded.hpp]:
```suggestion
static auto dna4_02_s1u_15u_e255 = [] ()
```
at all places.

File: test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_max_errors_unbanded_test.cpp (hunk 7 above)
Comment (marehr) [reply test/unit/alignment/pairwise/edit_distance/semi_global_edit_distance_max_errors_unbanded_test.cpp]: later :)
