### PR TITLE
[FIX] Allow '*' at the beginning of string fields in SAM format.

### LINKED ISSUE #2195: SAM/BAM IO: Quality string starting with '*' mess up the parsing
## Platform

  - SeqAn version: current master and release branch
  - Operating system: linux
  - Compiler: GCC7/8/9/10

## Description

Quality string starting with '*' mess up the parsing

### How to repeat the problem

The following test added to format_sam.hpp reproduces the error
```cpp
TEST_F(sam_format, quality_string_starts_with_asterics)
{
    {
        std::istringstream istream
        {
            "r1\t4\t1\t10\t0\t5M\t=\t136097\t-121\tACTGA\t*9>9;\tNM:i:1\tMQ:i:0\n"
        };
        seqan3::alignment_file_input fin{istream, seqan3::format_sam{}};

        EXPECT_EQ(seqan3::get<seqan3::field::qual>(*fin.begin()).size(), 5u);
    }
}
```

### Expected behaviour

The test should pass. Quality strings or any other strings that can be marked as empty with `*` should still be allowed to start with `*`, e.g. `*id_1`.

### Actual behaviour

Parsing is messed up because the string is only parsed for `*` and then continues on the rest of the string trying to parse another field (in the case of the quality string, it tries to parse the rest of the quality string as SAM tags throwing errors on the way)

### PR DESCRIPTION
**Pull request by smehringer**
An error that occurred for @h-2. The offending line was added as a test.

Fixes #2195

### CODE REVIEW

File: include/seqan3/io/alignment_file/format_sam_base.hpp [hunk 1]
```diff
@@ -49,6 +49,8 @@
 #include <seqan3/std/concepts>
 #include <seqan3/std/ranges>
 
+#include <seqan3/core/debug_stream.hpp>
+
 namespace seqan3::detail
 {
```
Comment (eseiler) [inline include/seqan3/io/alignment_file/format_sam_base.hpp:55]:
```suggestion
#include <seqan3/std/ranges>

namespace seqan3::detail
{
```

File: include/seqan3/io/alignment_file/format_sam.hpp [hunk 2]
```diff
@@ -407,7 +407,7 @@ inline void format_sam::read_alignment_record(stream_type & stream,
                   "The ref_offset must be a specialisation of std::optional.");
 
     auto stream_view = views::istreambuf(stream);
-    auto field_view = stream_view | views::take_until_or_throw_and_consume(is_char<'\t'>);
+    auto field_view = stream_view | views::take_until_or_throw(is_char<'\t'>);
```
Comment (eseiler) [inline include/seqan3/io/alignment_file/format_sam.hpp:410]: Why this change?

File: include/seqan3/io/alignment_file/format_sam_base.hpp (hunk 1 above)
Comment (smehringer) [reply include/seqan3/io/alignment_file/format_sam_base.hpp:55]: whops thanks :)

File: include/seqan3/io/alignment_file/format_sam.hpp (hunk 2 above)
Comment (smehringer) [reply include/seqan3/io/alignment_file/format_sam.hpp:410]: So the initial problem was that `*` indicates and empty SAM field and the function `read_field` only checks if `*` is present (before this PR). But I did not check if the field ONLY contains the `*`. 

So I need to check if there is a `\t` after the `*`but I cannot do this if the `\t` is consumed in general (the change you asked the reason for). Note that I cannot check if `field_view` is empty instead of checking if the next char is `\t` because on an input_range the `take..` view will always "regenerate".

```cpp
// input_range = "1\t2\t3\n"
auto v = input_range | take_until_and_consume('\t');
seqan3::debug_stream << v << std::endl; // prints 1
seqan3::debug_stream << v << std::endl;  // prints 2
```

Is that understandable?

Comment (eseiler) [reply include/seqan3/io/alignment_file/format_sam.hpp:410]: Yep; unfortunate that we can't keep the consume :(

**Comment by h-2** [comment]
This slightly shorter patch works for me, too;

```cpp
template <typename stream_view_type, std::ranges::forward_range target_range_type>
inline void format_sam_base::read_field(stream_view_type && stream_view, target_range_type & target)
{
    auto it = std::ranges::begin(stream_view);
    if (it == std::ranges::end(stream_view))
        return;

    char c = *it;
    ++it;

    using val_t = std::ranges::range_value_t<target_range_type>;

    if (it != std::ranges::end(stream_view)) // This is a string with more than one character
    {
        // the first character could be a '*'
        target.push_back(assign_char_to(c, val_t{}));
        std::ranges::copy(stream_view | views::char_to<val_t>, std::cpp20::back_inserter(target));
    }
    else if (c != '*') // single '*' means "empty sequence"; other character is 1-element range
    {
        target.push_back(assign_char_to(c, val_t{}));
    }
}
```
Just replace read_field with this, no need to change anything else. 

format_sam_test and format_bam_test passed for me, also by problematic file.

File: include/seqan3/io/alignment_file/format_sam.hpp (hunk 2 above)
Comment (h-2) [reply include/seqan3/io/alignment_file/format_sam.hpp:410]: This is only problematic if there are empty fields / double tabs. This is not allowed in SAM/BAM.

Note that in your example `v`is "at-end" in between the calls. The second (implicit) call to to `begin()` resets it. As long as you don't do that, there is no problem.

Comment (smehringer) [reply include/seqan3/io/alignment_file/format_sam.hpp:410]: > Note that in your example vis "at-end" in between the calls, i.e. the first begin iterator does compare true to the end. Otherwise it wouldn't stop printing after "1". Only when you create a new iterator (which implicitly happens in your example) does this new iterator start at the next field.

Ah ok thanks. That's the fact that I was missing when trying to fix this :)

**Review by eseiler — CHANGES_REQUESTED** [review]
LGTM, but you deleted the test?

**Comment by smehringer** [comment]
ah damnit

**Comment by h-2** [comment]
In general quite a few places like https://github.com/seqan/seqan3/blob/master/include/seqan3/io/alignment_file/format_bam.hpp#L954  use very many repeated calls to `std::ranges::begin(stream_view)` where I think it would be enough to just call `auto it = std::ranges::begin(stream_view)` once and than work with `it`. This is 
1. safer, because it prevents the potential "reset" of the stream discussed here
2. easier to read (`++it` vs `std::ranges::next(std::ranges::begin(stream_view))` )
3. maybe even a little faster

**Comment by smehringer** [comment]
> In general quite a few places like https://github.com/seqan/seqan3/blob/master/include/seqan3/io/alignment_file/format_bam.hpp#L954 use very many repeated calls to `std::ranges::begin(stream_view)` where I think it would be enough to just call `auto it = std::ranges::begin(stream_view)` once and than work with `it`. This is
> 
>     1. safer, because it prevents the potential "reset" of the stream discussed here
> 
>     2. easier to read (`++it` vs `std::ranges::next(std::ranges::begin(stream_view))` )
> 
>     3. maybe even a little faster

Thanks for the input :) I will add an issue in the backlog about this.

**Review by eseiler — APPROVED** [review]

**Comment by rrahn** [comment]
> An error that occurred for @h-2. The offending line was added as a test.

issue?

File: test/unit/io/alignment_file/format_sam_test.cpp [hunk 3]
```diff
@@ -328,3 +328,16 @@ TEST_F(sam_format, write_different_header)
     EXPECT_EQ(ostream.str(),
               "@HD\tVN:1.6\tSO:coordinate\tSS:query\tGO:reference\n@SQ\tSN:ref\tLN:34\n*\t0\tref\t1\t0\t*\t*\t0\t0\t*\t*\n");
 }
+
+TEST_F(sam_format, quality_string_starts_with_asterics)
```
Comment (rrahn) [inline test/unit/io/alignment_file/format_sam_test.cpp:332]: Would be good to have a tracking issue for this.

File: include/seqan3/io/alignment_file/format_sam_base.hpp [hunk 4]
```diff
@@ -371,11 +371,23 @@ inline void format_sam_base::read_field(stream_view_type && stream_view,
...
+
+        if (it != std::ranges::end(stream_view)) // This is a string with more than one character
+        {
+            target.push_back(assign_char_to(c, val_t{}));
+            std::ranges::copy(stream_view | views::char_to<val_t>, std::cpp20::back_inserter(target));
+        }
+        else if (c != '*') // single '*' means "empty sequence"; other character is 1-element range
+        {
+            target.push_back(assign_char_to(c, val_t{}));
+        }
```
Comment (rrahn) [inline include/seqan3/io/alignment_file/format_sam_base.hpp:389]:
```suggestion
        // Write to target if field does not represent an empty string, denoted as single '*' character.
        if (char c = *it; !(c == '*' && ++it == std::ranges::end(view)))
        {
            target.push_back(seqan3::assign_char_to(c, val_t{}));
            std::ranges::copy(stream_view | views::char_to<val_t>, std::cpp20::back_inserter(target));
        }
```

File: include/seqan3/io/alignment_file/format_sam_base.hpp [hunk 5]
```diff
@@ -371,11 +371,23 @@ inline void format_sam_base::read_field(stream_view_type && stream_view,
 template <typename stream_view_type, std::ranges::forward_range target_range_type>
 inline void format_sam_base::read_field(stream_view_type && stream_view, target_range_type & target)
 {
-    if (!is_char<'*'>(*std::ranges::begin(stream_view)))
-        std::ranges::copy(stream_view | views::char_to<std::ranges::range_value_t<target_range_type>>,
-                          std::cpp20::back_inserter(target));
-    else
-        std::ranges::next(std::ranges::begin(stream_view)); // skip '*'
+    using val_t = std::ranges::range_value_t<target_range_type>;
```
Comment (rrahn) [inline include/seqan3/io/alignment_file/format_sam_base.hpp:374]:
```suggestion
    using target_range_value_t = std::ranges::range_value_t<target_range_type>;
```

**Review by rrahn — CHANGES_REQUESTED** [review]
Some simplifications. And I'd like to track this via issues. Because it took a bit to understand what the problem was  by just looking at the code.

File: include/seqan3/io/alignment_file/format_sam_base.hpp (hunk 4 above)
Comment (h-2) [reply include/seqan3/io/alignment_file/format_sam_base.hpp:389]: This will not work for all cases, because -- as discussed above -- you are calling `std::ranges::begin()` a second time implicitly in line 382 (when iterating over `stream_view`). In the case of an underlying view that is consuming and it was at end, this will read "past-the-end".

Another issue with this code is, that in the case where `c != '*'` you are not incrementing the iterator (because of lazy-evaluation of `&&`) and thus writing `c` to the target twice.

I don't like have a line twice in the code, but I think it is the easiest (correct) solution.

Comment (rrahn) [reply include/seqan3/io/alignment_file/format_sam_base.hpp:389]: >This will not work for all cases, because -- as discussed above -- you are calling std::ranges::begin() a second time implicitly in line 382 (when iterating over stream_view). In the case of an underlying view that is consuming and it was at end, this will read "past-the-end".

Oh, that is actually true. Good point. But nothing that can be easily fixed by calling the right interface:
Since we already have the iterator we can just use it to form a subrange which does not consume anything
```cpp
std::ranges::copy(std::ranges::subrange<...>{it, std::ranges::end(view)} | views::char_to<val_t>, ...);
```
That should work right?

> Another issue with this code is, that in the case where c != '*' you are not incrementing the iterator (because of lazy-evaluation of &&) and thus writing c to the target twice.

Yeah, that's right. I had the order the other way around, which schould be guaranteed to work. In the end, I thought it is nicer to have the char check before but this would introduce a subtle bug indeed.

Comment (h-2) [reply include/seqan3/io/alignment_file/format_sam_base.hpp:389]: > That should work right?

Yes, the proposed solution should work and is more elegant! Although I think it is considerably more difficult to parse for humans while the slightly longer one is a lot more straight-forward (just thinking about how easy it was for you to make this mistake and that I needed to think hard on whether it works now 🤓 ).

But I will leave others to judge 😉 I have no strong preference about it.

Comment (rrahn) [reply include/seqan3/io/alignment_file/format_sam_base.hpp:389]: The problem is that when writing an algorithm with ranges you should pay attention to when you call begin. I don't think  that more verbose code makes the actual problem clearer, as it is quite subtle. At least not for someone who is reading the code for the first time. So I would support the concise version with a clearer comment at the beginning.

Comment (rrahn) [reply include/seqan3/io/alignment_file/format_sam_base.hpp:389]: Anyhow, the introduced issues make up some good test cases that should be added.

Comment (smehringer) [reply include/seqan3/io/alignment_file/format_sam_base.hpp:389]: > Anyhow, the introduced issues make up some good test cases that should be added.

I don't really see the good test cases. The function in question is already used with a consuming and a non-consuming input range, both empty (`*`) in some cases and non-empty in others. The case of a field starting with `*` but not being empty was also added (I added additionally added for the id field which is consuming in the test case - that one is new).

**Comment by smehringer** [comment]
@rrahn polite ping

File: include/seqan3/io/alignment_file/format_sam_base.hpp [hunk 6]
```diff
@@ -371,11 +371,24 @@ inline void format_sam_base::read_field(stream_view_type && stream_view,
...
+    {
+        char c = *it;
+        // Write to target if field does not represent an empty string, denoted as single '*' character.
+        if (!(++it == std::ranges::end(stream_view) && c == '*'))
+        {
+            target.push_back(seqan3::assign_char_to(c, target_range_value_t{}));
+            std::ranges::copy(std::ranges::subrange<begin_iterator_t, end_iterator_t>{it, std::ranges::end(stream_view)}
+                              | views::char_to<target_range_value_t>,
+                              std::cpp20::back_inserter(target));
+        }
```
Comment (rrahn) [inline include/seqan3/io/alignment_file/format_sam_base.hpp:390]:
```suggestion
        // Write to target if field does not represent an empty string, denoted as single '*' character.
        if (char c = *it; !(++it == std::ranges::end(stream_view) && c == '*'))
        {
            target.push_back(seqan3::assign_char_to(c, target_range_value_t{}));
            std::ranges::copy(std::ranges::subrange<begin_iterator_t, end_iterator_t>{it, std::ranges::end(stream_view)}
                              | views::char_to<target_range_value_t>,
                              std::cpp20::back_inserter(target));
        }
```

File: test/unit/io/alignment_file/format_sam_test.cpp [hunk 7]
```diff
@@ -328,3 +328,26 @@ TEST_F(sam_format, write_different_header)
...
+        seqan3::alignment_file_input fin{istream, seqan3::format_sam{}};
+
+        std::vector<seqan3::phred42> expected_quality
+        {
+            seqan3::assign_char_to('*', seqan3::phred42{}),
+            seqan3::assign_char_to('9', seqan3::phred42{}),
+            seqan3::assign_char_to('<', seqan3::phred42{}),
+            seqan3::assign_char_to('9', seqan3::phred42{}),
+            seqan3::assign_char_to(';', seqan3::phred42{})
+        };
```
Comment (rrahn) [inline test/unit/io/alignment_file/format_sam_test.cpp:348]:
```suggestion
        using seqan3::operator""_phred42;
        std::vector<seqan3::phred42> expected_quality = "*9<9;"_phred42;
```

File: test/unit/io/alignment_file/format_sam_test.cpp [hunk 8]
```diff
@@ -328,3 +328,26 @@ TEST_F(sam_format, write_different_header)
     EXPECT_EQ(ostream.str(),
               "@HD\tVN:1.6\tSO:coordinate\tSS:query\tGO:reference\n@SQ\tSN:ref\tLN:34\n*\t0\tref\t1\t0\t*\t*\t0\t0\t*\t*\n");
 }
+
+TEST_F(sam_format, issue2195)
+{ // see issue https://github.com/seqan/seqan3/issues/2195
+    {
+        std::istringstream istream
+        {
+            "*r1\t4\t1\t10\t0\t5M\t=\t136097\t-121\tACTGA\t*9<9;\tNM:i:1\tMQ:i:0\n"
```
Comment (rrahn) [inline test/unit/io/alignment_file/format_sam_test.cpp:337]: Add also an example with exactly one other character, e.g. `*1`

**Review by rrahn — CHANGES_REQUESTED** [review]
looks in general fine. Some small suggestions. You can already rebase.

File: test/unit/io/alignment_file/format_sam_test.cpp (hunk 8 above)
Comment (smehringer) [reply test/unit/io/alignment_file/format_sam_test.cpp:337]: done

**Review by rrahn — APPROVED** [review]
