### PR TITLE
[FIX] #2244: basic support for _GLIBCXX_USE_CXX11_ABI=0

### LINKED ISSUE #2244: CentOS 7 / RHEL 7: error compiling argument_parser
# Platform

  - SeqAn version: master branch (Also same error on 3.0.1)
  - Operating system: Linux cbrglogin2 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  - Compiler: /opt/rh/devtoolset-9/root/usr/bin/g++
 - Compiler version - g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

## Description
Im relatively new to C++ so could entirely be my stupidity. When I try to compile my hello world I get the following error that seem to be related to the argument_parser because when I remove this header ref there are no errors. 

### How to repeat the problem

Code snippet:
```c++
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/argument_parser/all.hpp>

int main()
{
    seqan3::debug_stream << "Hello world\n";
    return 0;
}
```
commands in build dir:
```
cmake ../source
make
```
Compile error:
```
[ 50%] Building CXX object CMakeFiles/hello_world.dir/hello_world.cpp.o
In file included from /Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/io/detail/misc.hpp:19,
                 from /Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/argument_parser/validators.hpp:29,
                 from /Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/argument_parser/detail/format_base.hpp:23,
                 from /Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/argument_parser/detail/format_help.hpp:20,
                 from /Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/argument_parser/argument_parser.hpp:25,
                 from /Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/argument_parser/all.hpp:15,
                 from /Filers/home/cgat/acribbs/Documents/tutorial/source/hello_world.cpp:3:
/Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/io/exception.hpp: In constructor ‘seqan3::io_error::io_error(const string&, const std::error_code&)’:
/Filers/home/cgat/acribbs/Documents/tutorial/seqan3/include/seqan3/io/exception.hpp:59:72: error: no matching function for call to ‘std::ios_base::failure::failure(<brace-enclosed initializer list>)’
   59 |              std::error_code const & ec) : std::ios_base::failure{s, ec}
      |                                                                        ^
In file included from /opt/rh/devtoolset-9/root/usr/include/c++/9/ios:42,
                 from /opt/rh/devtoolset-9/root/usr/include/c++/9/ostream:38,
                 from /opt/rh/devtoolset-9/root/usr/include/c++/9/iostream:39,
                 from /Filers/home/cgat/acribbs/Documents/tutorial/source/hello_world.cpp:1:
/opt/rh/devtoolset-9/root/usr/include/c++/9/bits/ios_base.h:282:7: note: candidate: ‘std::ios_base::failure::failure(const string&)’
  282 |       failure(const string& __str) throw();
      |       ^~~~~~~
/opt/rh/devtoolset-9/root/usr/include/c++/9/bits/ios_base.h:282:7: note:   candidate expects 1 argument, 2 provided
/opt/rh/devtoolset-9/root/usr/include/c++/9/bits/ios_base.h:276:11: note: candidate: ‘std::ios_base::failure::failure(const std::ios_base::failure&)’
  276 |     class failure : public exception
      |           ^~~~~~~
/opt/rh/devtoolset-9/root/usr/include/c++/9/bits/ios_base.h:276:11: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/hello_world.dir/build.make:83: CMakeFiles/hello_world.dir/hello_world.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/hello_world.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

```

### PR DESCRIPTION
**Pull request by marehr**
Fixes #2244

### CODE REVIEW

File: include/seqan3/io/alignment_file/format_bam.hpp [hunk 1]
```diff
@@ -64,12 +64,22 @@ class format_bam : private detail::format_sam_base
...
+    format_bam & operator=(format_bam &&) /*noexcept*/ = default; //!< Defaulted.
+    ~format_bam() /*noexcept*/ = default; //!< Defaulted.
+#else // ^^^ workaround / no workaround vvv
     format_bam() noexcept = default; //!< Defaulted.
     format_bam(format_bam const &) noexcept = default; //!< Defaulted.
     format_bam & operator=(format_bam const &) noexcept = default; //!< Defaulted.
     format_bam(format_bam &&) noexcept = default; //!< Defaulted.
     format_bam & operator=(format_bam &&) noexcept = default; //!< Defaulted.
     ~format_bam() noexcept = default; //!< Defaulted.
+#endif // SEQAN3_WORKAROUND_GCC_NO_CXX11_ABI
```
Comment (eseiler) [inline include/seqan3/io/alignment_file/format_bam.hpp:82]: Aren't defaulted constructors `noexcept` if they can?
Then we can just remove the `noexcept`.

**Review by eseiler — CHANGES_REQUESTED** [review]

File: include/seqan3/io/alignment_file/format_bam.hpp (hunk 1 above)
Comment (marehr) [reply include/seqan3/io/alignment_file/format_bam.hpp:82]: @smehringer Do you agree to remove noexcept?

@esiragusa If we do that I also need to change format_sam.

Either way is fine to me.

Comment (smehringer) [reply include/seqan3/io/alignment_file/format_bam.hpp:82]: Yes I agree. Explicitly defaulted ctors are constexpr and noexcept if they can be. To the best of my knowledge right now, there is no explicit reason for requiring noexcept (which would mean explicitly stating it here regardless of the defaults).

**Review by eseiler — APPROVED** [review]
LGTM, but we still need to decide in what capacity we want to support this?
Is this all we need to change or is there more?

**Comment by marehr** [comment]
> LGTM, but we still need to decide in what capacity we want to support this?
> Is this all we need to change or is there more?

Yep, in a core meeting

File: include/seqan3/io/alignment_file/format_bam.hpp [hunk 2]
```diff
@@ -64,12 +64,13 @@ class format_bam : private detail::format_sam_base
     /*!\name Constructors, destructor and assignment
      * \{
      */
-    format_bam() noexcept = default; //!< Defaulted.
-    format_bam(format_bam const &) noexcept = default; //!< Defaulted.
-    format_bam & operator=(format_bam const &) noexcept = default; //!< Defaulted.
-    format_bam(format_bam &&) noexcept = default; //!< Defaulted.
-    format_bam & operator=(format_bam &&) noexcept = default; //!< Defaulted.
-    ~format_bam() noexcept = default; //!< Defaulted.
+    // string_buffer is of type std::string and has some problems with pre-C++11 ABI
```
Comment (smehringer) [inline include/seqan3/io/alignment_file/format_bam.hpp:67]:
```suggestion
    // string_buffer is of type std::string and has some problems with pre-C++11 ABI if ctor is declared noexcept
```
? Otherwise the comment is not very helpful by itself.
You can also just delete it completely since we decided to not use noexcept explicitly anyway.

**Review by smehringer — APPROVED** [review]
Just one thing about a comment but LGTM otherwise!

**Comment by smehringer** [comment]
hm Codecov says the **no**-workaround in exception.hpp is not tested?

**Comment by eseiler** [comment]
> hm Codecov says the **no**-workaround in exception.hpp is not tested?

Wasn't tested before either:
https://codecov.io/gh/seqan/seqan3/src/master/include/seqan3/io/exception.hpp#L55
