### PR TITLE
[FIX] Fix move construction/assignment of search_result_range.

### LINKED ISSUE #1799: Search result range is not correctly movable
The following test added to `search_result_range_test.cpp` shows the error:

```cpp
TEST_F(search_result_range_test, move)
{
    std::vector<std::pair<size_t, size_t>> expected_range{{0, 0}, {0, 1}, {0, 2}, {0, 3}, {0, 4},
                                                          {1, 0}, {1, 1}, {1, 2}, {1, 3}, {1, 4},
                                                          {2, 0}, {2, 1}, {2, 2}, {2, 3}, {2, 4}};

    seqan3::search_result_range rng{dummy_search_algorithm{}, query_range | seqan3::views::type_reduce};

    auto moved_range = std::move(rng);

    EXPECT_RANGE_EQ(expected_range, moved_range);
}
```

This results in the following error
```
/home/svenja/AGABI/seqan3/include/seqan3/range/views/single_pass_input.hpp:313:37: runtime error: member access within null pointer of type 'struct element_type'
[1]    7187 segmentation fault (core dumped)  ./search/search_result_range_test
```

because within the single_input_view the pointers are not set correctly. It helps to add asserts in
```
    base_iterator_type & cached() const noexcept
    {
        assert(view_ptr != nullptr);
        assert(view_ptr->state_ptr != nullptr);
        return view_ptr->state_ptr->cached_urng_iter;
    }
```
of the `single_pass_input.hpp`.

### PR DESCRIPTION
**Pull request by smehringer**
Fixes #1799

### CODE REVIEW

File: test/unit/search/search_result_range_test.cpp [hunk 1]
```diff
@@ -96,3 +97,23 @@ TEST_F(search_result_range_test, empty_query_range)
...
 }
+
+TEST_F(search_result_range_test, issue1799)
+{
+    std::vector<std::pair<size_t, size_t>> expected_range{{0, 0}, {0, 1}, {0, 2}, {0, 3}, {0, 4},
+                                                          {1, 0}, {1, 1}, {1, 2}, {1, 3}, {1, 4},
+                                                          {2, 0}, {2, 1}, {2, 2}, {2, 3}, {2, 4}};
+    { // move construction
+        seqan3::search_result_range rng{dummy_search_algorithm{}, query_range | seqan3::views::type_reduce};
+        seqan3::search_result_range moved_range(std::move(rng));
```
Comment (eseiler) [inline test/unit/search/search_result_range_test.cpp:108]:
```suggestion
        seqan3::search_result_range moved_range{std::move(rng)};
```

File: test/unit/search/search_result_range_test.cpp [hunk 2]
```diff
@@ -96,3 +97,23 @@ TEST_F(search_result_range_test, empty_query_range)
...
+    { // move construction
+        seqan3::search_result_range rng{dummy_search_algorithm{}, query_range | seqan3::views::type_reduce};
+        seqan3::search_result_range moved_range{std::move(rng)};
+
+        EXPECT_RANGE_EQ(expected_range, moved_range);
+    }
+
+    { // move assignment
+        seqan3::search_result_range rng{dummy_search_algorithm{}, query_range | seqan3::views::type_reduce};
+        auto moved_range = std::move(rng);
```
Comment (marehr) [inline test/unit/search/search_result_range_test.cpp:115]:
```suggestion
        auto && moved_range = std::move(rng);
```

**Comment by marehr** [comment]
2020-05-08

Resolution:

* remove iterator
* keep move semantics
* change test that tests single_input_pass (skip first 2 values, see if move is correct)
