### PR TITLE
[FIX] #1921: cxx20: sequence builder does not work how we use it in a…

### LINKED ISSUE #1921: cxx20: sequence builder does not work how we use it in align_pairwise
The following code does not compile with `g++-10 -std=c++2a`:

```c++
    auto && sequence1 = this->fst;
    auto && sequence2 = this->sec | std::views::drop(0);

    using first_seq_t = decltype(sequence1) &;
    using second_seq_t = decltype(sequence2) &;

    using function_wrapper_t = std::function<void(first_seq_t, second_seq_t)>;

    auto alignment = [&](first_seq_t sequence1, second_seq_t sequence2) {
      seqan3::detail::aligned_sequence_builder builder{sequence1, sequence2};
      auto trace_path = this->path({seqan3::detail::row_index_type{2},
                                    seqan3::detail::column_index_type{3}});
      auto trace_res = builder(trace_path);
    };

    auto algorithm = function_wrapper_t{std::move(alignment)};
```

With error:
```c++
In file included from /seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:13:
/seqan3/include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp: In instantiation of ‘seqan3::detail::aligned_sequence_builder<fst_sequence_t, sec_sequence_t>::result_type seqan3::detail::aligned_sequence_builder<fst_sequence_t, sec_sequence_t>::operator()(trace_path_t&&) [with trace_path_t = std::ranges::subrange<seqan3::detail::trace_iterator<seqan3::detail::two_dimensional_matrix<seqan3::detail::trace_directions>::iterator_type<seqan3::detail::two_dimensional_matrix<seqan3::detail::trace_directions> > >, std::default_sentinel_t, std::ranges::subrange_kind::unsized>&; fst_sequence_t = std::vector<seqan3::dna4>&; sec_sequence_t = std::ranges::drop_view<std::ranges::ref_view<std::vector<seqan3::dna15> > >&]’:
/seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:305:31:   required from ‘void aligned_sequence_builder_fixture_issueXXXX_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = std::pair<std::vector<seqan3::dna4>&, std::vector<seqan3::dna15>&>]’
/seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:291:1:   required from here
/seqan3/include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:196:25: error: no matching function for call to ‘assign_unaligned(std::__tuple_element_t<1, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, 18446744073709551615> >, seqan3::gap_decorator<seqan3::detail::view_take<std::ranges::drop_view<std::ranges::drop_view<std::ranges::ref_view<std::vector<seqan3::dna15, std::allocator<seqan3::dna15> > > > >, false, false> > > >&, std::span<seqan3::dna15, 18446744073709551615>)’
  196 |         assign_unaligned(std::get<1>(res.alignment),
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  197 |                          sec_rng | views::slice(res.second_sequence_slice_positions.first,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  198 |                                                 res.second_sequence_slice_positions.second));
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /seqan3/include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:18,
                 from /seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:13:
/seqan3/include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp:378:13: note: candidate: ‘void seqan3::assign_unaligned(aligned_seq_t&, unaligned_sequence_type&&) [with aligned_seq_t = seqan3::gap_decorator<seqan3::detail::view_take<std::ranges::drop_view<std::ranges::drop_view<std::ranges::ref_view<std::vector<seqan3::dna15> > > >, false, false> >; unaligned_sequence_type = std::span<seqan3::dna15, 18446744073709551615>]’
  378 | inline void assign_unaligned(aligned_seq_t & aligned_seq, unaligned_sequence_type && unaligned_seq)
      |             ^~~~~~~~~~~~~~~~
/seqan3/include/seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp:378:13: note: constraints not satisfied
In file included from /seqan3/include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:24,
                 from /seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:13:
/seqan3/include/seqan3/range/decorator/gap_decorator.hpp:293:17: note: candidate: ‘void seqan3::assign_unaligned(seqan3::gap_decorator<inner_type>&, unaligned_seq_t&&) [with unaligned_seq_t = std::span<seqan3::dna15, 18446744073709551615>; inner_type = seqan3::detail::view_take<std::ranges::drop_view<std::ranges::drop_view<std::ranges::ref_view<std::vector<seqan3::dna15> > > >, false, false>]’
  293 |     friend void assign_unaligned(gap_decorator & dec, unaligned_seq_t && unaligned)
      |                 ^~~~~~~~~~~~~~~~
/seqan3/include/seqan3/range/decorator/gap_decorator.hpp:293:17: note: constraints not satisfied
```

This is bad, because we normally type erase the alignment algorithm within the configuration:

https://github.com/seqan/seqan3/blob/6d36431dc8611ed0979f0053948672840a7c5fd4/include/seqan3/alignment/pairwise/alignment_configurator.hpp#L340-L341

## Platform

  - SeqAn version: 
  - Operating system: 
  - Compiler:

### PR DESCRIPTION
**Pull request by marehr**
…lign_pairwise

Fixes  #1921

### CODE REVIEW

File: include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp [hunk 1]
```diff
@@ -191,11 +191,11 @@ class aligned_sequence_builder
             std::pair<size_t, size_t>{trace_it.coordinate()};
 
         assign_unaligned(std::get<0>(res.alignment),
-                         fst_rng | views::slice(res.first_sequence_slice_positions.first,
-                                                res.first_sequence_slice_positions.second));
+                         std::views::all(fst_rng) | views::slice(res.first_sequence_slice_positions.first,
```
Comment (rrahn) [inline include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:194]: Not type reduce here?

File: include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp [hunk 2]
```diff
@@ -121,8 +122,10 @@ inline alignment_t alignment_trace(database_t && database,
     assert(coordinate.col < matrix.cols());
 
     alignment_t aligned_seq{};
-    assign_unaligned(std::get<0>(aligned_seq), views::slice(database, front_coordinate.first, coordinate.col));
-    assign_unaligned(std::get<1>(aligned_seq), views::slice(query, front_coordinate.second, coordinate.row));
+    assign_unaligned(std::get<0>(aligned_seq), database | views::type_reduce
```
[the remark this answers is not in the document]
Comment (marehr) [reply include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp:125]: No Idea, I just fixed existing code.

File: include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp (hunk 1 above)
Comment (marehr) [reply include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:194]: This one is funny, because `fst_rng` is already of type `type_reduce<urange>`

Comment (marehr) [reply include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:194]: I need to use `std::views::all(fst_rng)`, because otherwise `fst_rng` in `fst_rng | views::slice` would be a lvalue, which would when not be a view but a viewable_range. This means we should ALWAYS call `std::views::all`, before piping it into something.

Comment (rrahn) [reply include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:194]: > This semantic difference can cause different resulting views

That sounds broken!

File: include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (rrahn) [reply include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp:125]: Well, I guess we define internally what the result type is, which would be a std::pair.

[the remark this answers is not in the document]
Comment (marehr) [reply include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp:125]: Yeah, it is a `std::tuple`.

File: include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp (hunk 1 above)
Comment (marehr) [reply include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:194]: I think this was one of the reasons why eric didn't want to allow lvalues, because the whole concept of views is that they are rvalues. If you pass a `view &` into something it will not be a view, but a `range &` that must be made into a view by `std::views::all`.
