### PR TITLE
[FIX,TEST] Do not check zlib output for alternative implementations

### LINKED ISSUE #3323: seqan3 -3.4.0 rc2: some tests failed
Hi all

I'm compiling seqan-3.4.0.rc2 on Fedora 42 with GCC-15; some tests are failing, like:

```
158/314 Test #164: contrib/stream/gz_ostream_test ............................................................***Failed    0.03 sec
Running main() from /builddir/build/BUILD/gtest-1.14.0-build/googletest-1.14.0/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from contrib_streams/ostream/0, where TypeParam = seqan3::contrib::basic_gz_ostream<char,std::char_traits<char>,std::allocator<char>,unsigned char,std::allocator<unsigned char> >
[ RUN      ] contrib_streams/ostream/0.concept_check
[       OK ] contrib_streams/ostream/0.concept_check (0 ms)
[ RUN      ] contrib_streams/ostream/0.output
/builddir/build/BUILD/seqan3-3.4.0-build/seqan3-3.4.0-rc.2/test/unit/contrib/stream/../../io/stream/ostream_test_template.hpp:46: Failure
Expected equality of these values:
  buffer
    Which is: "\x1F\x8B\b\0\0\0\0\0\0\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\xC9HU\xC8I\xAC\xAATH\xC9O\a\09\xA3OA+\0\0\0"
  TestFixture::compressed
    Which is: "\x1F\x8B\b\0\0\0\0\0\0\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\x1J\xE7$VU*\xA4\xE4\xA7\x3\09\xA3OA+\0\0\0"
[  FAILED  ] contrib_streams/ostream/0.output, where TypeParam = seqan3::contrib::basic_gz_ostream<char,std::char_traits<char>,std::allocator<char>,unsigned char,std::allocator<unsigned char> > (1 ms)
[ RUN      ] contrib_streams/ostream/0.output_type_erased
/builddir/build/BUILD/seqan3-3.4.0-build/seqan3-3.4.0-rc.2/test/unit/contrib/stream/../../io/stream/ostream_test_template.hpp:68: Failure
Expected equality of these values:
  buffer
    Which is: "\x1F\x8B\b\0\0\0\0\0\0\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\xC9HU\xC8I\xAC\xAATH\xC9O\a\09\xA3OA+\0\0\0"
  TestFixture::compressed
    Which is: "\x1F\x8B\b\0\0\0\0\0\0\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\x1J\xE7$VU*\xA4\xE4\xA7\x3\09\xA3OA+\0\0\0"
[  FAILED  ] contrib_streams/ostream/0.output_type_erased, where TypeParam = seqan3::contrib::basic_gz_ostream<char,std::char_traits<char>,std::allocator<char>,unsigned char,std::allocator<unsigned char> > (1 ms)
[----------] 3 tests from contrib_streams/ostream/0 (3 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (3 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] contrib_streams/ostream/0.output, where TypeParam = seqan3::contrib::basic_gz_ostream<char,std::char_traits<char>,std::allocator<char>,unsigned char,std::allocator<unsigned char> >
[  FAILED  ] contrib_streams/ostream/0.output_type_erased, where TypeParam = seqan3::contrib::basic_gz_ostream<char,std::char_traits<char>,std::allocator<char>,unsigned char,std::allocator<unsigned char> >
 2 FAILED TESTS
159/314 Test #165: contrib/stream/bgzf_istream_test ..........................................................   Passed    0.03 sec
160/314 Test #166: contrib/stream/bgzf_ostream_test ..........................................................***Failed    0.03 sec
Running main() from /builddir/build/BUILD/gtest-1.14.0-build/googletest-1.14.0/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from contrib_streams/ostream/0, where TypeParam = seqan3::contrib::basic_bgzf_ostream<char,std::char_traits<char>,std::allocator<char>,char,std::allocator<char> >
[ RUN      ] contrib_streams/ostream/0.concept_check
[       OK ] contrib_streams/ostream/0.concept_check (0 ms)
[ RUN      ] contrib_streams/ostream/0.output
/builddir/build/BUILD/seqan3-3.4.0-build/seqan3-3.4.0-rc.2/test/unit/contrib/stream/../../io/stream/ostream_test_template.hpp:46: Failure
Expected equality of these values:
  buffer
    Which is: "\x1F\x8B\b\x4\0\0\0\0\0\0\x6\0BC\x2\0F\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\xC9HU\xC8I\xAC\xAATH\xC9O\a\09\xA3OA+\0\0\0\x1F\x8B\b\x4\0\0\0\0\0\xFF\x6\0BC\x2\0\x1B\0\x3\0\0\0\0\0\0\0\0\0"
  TestFixture::compressed
    Which is: "\x1F\x8B\b\x4\0\0\0\0\0\0\x6\0BC\x2\0E\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\x1J\xE7$VU*\xA4\xE4\xA7\x3\09\xA3OA+\0\0\0\x1F\x8B\b\x4\0\0\0\0\0\xFF\x6\0BC\x2\0\x1B\0\x3\0\0\0\0\0\0\0\0\0"
[  FAILED  ] contrib_streams/ostream/0.output, where TypeParam = seqan3::contrib::basic_bgzf_ostream<char,std::char_traits<char>,std::allocator<char>,char,std::allocator<char> > (2 ms)
[ RUN      ] contrib_streams/ostream/0.output_type_erased
/builddir/build/BUILD/seqan3-3.4.0-build/seqan3-3.4.0-rc.2/test/unit/contrib/stream/../../io/stream/ostream_test_template.hpp:68: Failure
Expected equality of these values:
  buffer
    Which is: "\x1F\x8B\b\x4\0\0\0\0\0\0\x6\0BC\x2\0F\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\xC9HU\xC8I\xAC\xAATH\xC9O\a\09\xA3OA+\0\0\0\x1F\x8B\b\x4\0\0\0\0\0\xFF\x6\0BC\x2\0\x1B\0\x3\0\0\0\0\0\0\0\0\0"
  TestFixture::compressed
    Which is: "\x1F\x8B\b\x4\0\0\0\0\0\0\x6\0BC\x2\0E\0\v\xC9HU(,\xCDL\xCEVH*\xCA/\xCFSH\xCB\xAFP\xC8*\xCD-(V\xC8/K-R(\x1J\xE7$VU*\xA4\xE4\xA7\x3\09\xA3OA+\0\0\0\x1F\x8B\b\x4\0\0\0\0\0\xFF\x6\0BC\x2\0\x1B\0\x3\0\0\0\0\0\0\0\0\0"
[  FAILED  ] contrib_streams/ostream/0.output_type_erased, where TypeParam = seqan3::contrib::basic_bgzf_ostream<char,std::char_traits<char>,std::allocator<char>,char,std::allocator<char> > (0 ms)
[----------] 3 tests from contrib_streams/ostream/0 (3 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (3 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] contrib_streams/ostream/0.output, where TypeParam = seqan3::contrib::basic_bgzf_ostream<char,std::char_traits<char>,std::allocator<char>,char,std::allocator<char> >
[  FAILED  ] contrib_streams/ostream/0.output_type_erased, where TypeParam = seqan3::contrib::basic_bgzf_ostream<char,std::char_traits<char>,std::allocator<char>,char,std::allocator<char> >
 2 FAILED TESTS
```

Full build log:  [seqan3.zip](https://github.com/user-attachments/files/18470635/seqan3.zip)

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #3323

### CODE REVIEW

File: test/unit/io/stream/ostream_test_template.hpp [hunk 1]
```diff
@@ -41,7 +42,10 @@ TYPED_TEST_P(ostream, output)
     std::string buffer{std::istreambuf_iterator<char>{fi}, std::istreambuf_iterator<char>{}};
 
     if constexpr (TestFixture::zero_out_os_byte)
+    {
         buffer[9] = '\x00'; // zero-out the OS byte.
+        SEQAN3_TEST_GTEST_SKIP_ZLIB_DEFLATE;
```
Comment (eseiler) [inline test/unit/io/stream/ostream_test_template.hpp:47]: The template is also used for `bz2`, which we don't want to skip.
`zero_out_os_byte` (also used for istream template) is currently equivalent to `is_zlib_compression`.

**Comment by seqan-actions** [comment]
Documentation preview available at https://docs.seqan.de/preview/seqan/seqan3/3324

**Review by SGSSGene — APPROVED** [review]
Very cool! Thx!
