### PR TITLE
[FIX] BAM: Not consuming sequence

### LINKED ISSUE #2417: [BUG] Extracting the alignment from a BAM file referenes ID index not in range.
## Platform

  - SeqAn version: 
  - Operating system: Linux
  - Compiler: g++ 7.5

## Description
When I extract the alignment field of records in an alignment file, at some point it throws the following message:
```terminate called after throwing an instance of 'seqan3::format_error'
  what():  Reference id index '287314191' is not in range of header.ref_ids(), which has size 34.
```

### How to repeat the problem

Code snippet:
```cpp
#include <seqan3/io/alignment_file/input.hpp>   // SAM/BAM support
#include <seqan3/core/debug_stream.hpp>
#include <filesystem>

int main()
{
    std::filesystem::path alignment_path = "test.bam";

    using my_fields = seqan3::fields<seqan3::field::id,
                                     seqan3::field::alignment>;

    seqan3::alignment_file_input alignment_file{alignment_path, my_fields{}};

    for (auto & [ id, alignment ] : alignment_file)
    {
        seqan3::debug_stream << ": " << id << ": " << std::get<1>(alignment) << '\n';
    }

}
```

Test file attached. It's a part of a larger BAM file, the error occurs at the last line of this part.

[test.bam.gz](https://github.com/seqan/seqan3/files/6049807/test.bam.gz)

I wonder if it has to do with the record trying to extract an alignment in an unmapped sequence?

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #2417 

If we do not want to parse the sequence, but still want an alignment, but then have an empty CIGAR, we create a dummy alignment, but we forget to consume the sequence.

### CODE REVIEW

File: test/unit/io/alignment_file/format_bam_test.cpp [hunk 1]
```diff
@@ -516,3 +519,38 @@ TEST_F(bam_format, too_long_cigar_string_write)
...
+    std::istringstream stream{input};
+
+    seqan3::alignment_file_input fin{stream, seqan3::format_bam{}, seqan3::fields<seqan3::field::id,
+                                                                                  seqan3::field::alignment>{}};
+
+    std::vector<seqan3::gapped<seqan3::dna5>> const empty_sequence{};
+
+    // In 2417, the sequence was not consumed. Thus, wrong bytes were read for the following records.
+    // With the chosen `input` this also means that there will be more than 1 record in the alignment file.
+    // Hence, we need the for loop even though there is only 1 record.
```
Comment (marehr) [inline test/unit/io/alignment_file/format_bam_test.cpp:549]: I don't understand this remark.

Comment (eseiler) [reply test/unit/io/alignment_file/format_bam_test.cpp:555]: There's only one record in the bam file.
The bug caused the sequence to not be consumed, which also means that we think there is another record because we are not at the end of the stream after reading one record.
The second record will then be gibberish and throw something somewhere while being parsed.

Since I only read `id` and `alignment`, there is not really something I can check that would be parsed incorrectly in this one record (`id` is before the sequence and alignment is an empty dummy).

I could also check if the file iterator is at end after reading one record, but the for-loop is closer to the reported bug/use-case and also kinda easier to parse IMO.

Comment (marehr) [reply test/unit/io/alignment_file/format_bam_test.cpp:555]: Okay! Can you add a counter that counts the number of loop-passes? That one should be 1 right?

File: include/seqan3/io/alignment_file/format_bam.hpp [hunk 2]
```diff
@@ -486,6 +486,9 @@ inline void format_bam::read_alignment_record(stream_type & stream,
                 }
                 else
                 {
+                    detail::consume(seq_stream);
+                    if (core.l_seq & 1)
+                        std::ranges::next(std::ranges::begin(stream_view));
```
Comment (marehr) [inline include/seqan3/io/alignment_file/format_bam.hpp:491]: Can you out-source this into a lambda?

File: test/unit/io/alignment_file/format_bam_test.cpp [hunk 3]
```diff
@@ -22,7 +22,10 @@ struct alignment_file_read<seqan3::format_bam> : public alignment_file_data
     // formatted input
     // -----------------------------------------------------------------------------------------------------------------
     // See format_sam_test for the corresponding input in human readable-form.
-    // The byte sequence here are all uncompressed bam files since the file handles compression.
+    // The byte sequence here are all uncompressed (both gzip and bgzf) bam files since the file handles compression.
+    // Conversion can look like this: samtools view -u test.sam | bgzip -d
```
[the remark this answers is not in the document]
Comment (eseiler) [reply test/unit/io/alignment_file/format_bam_test.cpp:26]: Nope.
You write what you want in the SAM file. `samtools view -u` returns an uncompressed (=no gzip compression) BAM file, which you then bgzf-decompress.

[the remark this answers is not in the document]
Comment (marehr) [reply test/unit/io/alignment_file/format_bam_test.cpp:26]: Okay, I tried it with bam and worked to :)

**Review by marehr — APPROVED** [review]

**Comment by marehr** [comment]
rebase :)

**Review by eaasna — APPROVED** [review]
Looks good to me :)
