### PR TITLE
Fix/issue_3264

### LINKED ISSUE #3264: Question regarding the usage of `seqan3::fm_index_cursor` using `seqan3::bitpacked_sequence`.
## Platform

  - SeqAn version: 3.3.0
  - Operating system: Linux arch 6.9.8-arch1-1  SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 x86_64 GNU/Linux
  - Compiler: g++ (GCC) 14.1.1 20240522

## Question
I am relatively new to C++ and I'm currently learning to use the SeqAn3 library. I've been following the documentation for the fm_index, but I encountered an issue that I cannot resolve.

Here's a code Snippet:
```cpp
#include <seqan3/argument_parser/all.hpp>
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/alphabet/nucleotide/dna5.hpp>
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/io/sequence_file/input.hpp>
#include <seqan3/search/fm_index/fm_index.hpp>
#include <string>
#include <vector>
#include <seqan3/alphabet/container/bitpacked_sequence.hpp>
#include <fstream>

int main(int argc, char const** argv) {
    using namespace seqan3::literals;

    seqan3::bitpacked_sequence<seqan3::dna4> seq{"ACGGTCAGGTTC"_dna4};
    seqan3::fm_index index{seq};

    // I don't know why the normal slicing is not working???
    // auto search(seq.begin(), seq.begin() + 4);
    auto search = seqan3::views::slice(seq, 0, 4);

    auto cursor = index.cursor();
    cursor.extend_right(search);
}

```
### Steps to Reproduce
- Run the given code with seqan3 version 3.3.0

### Expected Behavior
- The FM-index cursor should be extended to the right using the sliced sequence.

### Observed Behavior
- The code does not compile or execute as expected.

### LINKED ISSUE #3267: Alphabet conversion is not properly constrained
### Does this problem persist on the current main?

- [X] I have verified the issue on the current main

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Explicit casting of a bitpacked proxy type to its actual value type causes a compile time error.
See #3264 for more details.

### Expected Behavior

It compiles.

### Steps To Reproduce

```cpp
#include <vector>

#include <seqan3/alphabet/container/bitpacked_sequence.hpp>
#include <seqan3/alphabet/nucleotide/dna4.hpp>

using namespace seqan3::literals;

seqan3::bitpacked_sequence<seqan3::dna4> source{"ACGGTCAGGTTC"_dna4};
auto it = source.begin();
seqan3::dna4 val = seqan3::dna4{*it}; // compile error - due to explicit conversion
```

### Environment

```markdown
- Operating system: macOS 14.5
- SeqAn version: main
- Compiler: gcc 13.3
```

### Anything else?

One problem is this code: https://github.com/seqan/seqan3/blob/ca4d668390e35b4045ccd02d070927f8178ed2ce/include/seqan3/alphabet/detail/convert.hpp#L32-L44

Here, we only require `in_t` to be an alphabet type but this does not include that `in_t` is also default constructible. However, inside of the initialization of the conversion table the default constructor of `in_t` is called, causing the seen compile error.

To fix this the `in_t` must be constrained with `std::default_initializable` as well.

### PR DESCRIPTION
**Pull request by rrahn**
Further constraints the conversion constructors of the nucleotide and aminoacid base alphabet types to only consider conversion if all requirements are fulfilled. This is now represented by the specific concept `convertable_to_through_char_representation`.
Through this proxy types will not be converted through their char representation but will be implicitly converted to their underling base alphabet type, e.g. dna4, and then copied/moved using the copy/move constructor of the underlying base alphabet type.

Fixes #3264
Fixes #3267

### CODE REVIEW

File: test/unit/alphabet/container/bitpacked_sequence_test.cpp [hunk 1]
```diff
@@ -4,6 +4,8 @@
 
 #include <gtest/gtest.h>
 
+#include <vector>
+
```
Comment (eseiler) [inline test/unit/alphabet/container/bitpacked_sequence_test.cpp:8]:
```suggestion
```

Needed?

File: test/unit/search/fm_index_cursor/extend_bitpacked_query_sequence_test.cpp [hunk 2]
```diff
@@ -0,0 +1,29 @@
+// SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
+// SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
+// SPDX-License-Identifier: BSD-3-Clause
+
+#include <gtest/gtest.h>
+
+#include <vector>
+
```
Comment (eseiler) [inline test/unit/search/fm_index_cursor/extend_bitpacked_query_sequence_test.cpp:8]:
```suggestion
```

Needed?

**Review by eseiler — CHANGES_REQUESTED** [review]
Do you have an opinion regarding https://github.com/seqan/seqan3/issues/3267#issuecomment-2230757229 ?

**Comment by rrahn** [comment]
> Do you have an opinion regarding https://github.com/seqan/seqan3/issues/3267#issuecomment-2230757229 ?

I answered on the issue page.

File: test/unit/search/fm_index_cursor/extend_bitpacked_query_sequence_test.cpp (hunk 2 above)
Comment (rrahn) [reply test/unit/search/fm_index_cursor/extend_bitpacked_query_sequence_test.cpp:8]: Well, I am using a `std::vector`. It might be included by the `helper.hpp` already. Not including it has the potential that if some other code is refactored this test might not compile anymore since vector is not included through some dependent includes. Adding it makes clear, that I need it in the test.
But frankly, I don't care too much. What is the preferred policy here?

File: test/unit/alphabet/container/bitpacked_sequence_test.cpp (hunk 1 above)
Comment (rrahn) [reply test/unit/alphabet/container/bitpacked_sequence_test.cpp:8]: Definitely not. Thanks for spotting!

Comment (rrahn) [inline test/unit/alphabet/container/bitpacked_sequence_test.cpp:8]:
```suggestion
```

File: test/unit/search/fm_index_cursor/extend_bitpacked_query_sequence_test.cpp (hunk 2 above)
Comment (eseiler) [reply test/unit/search/fm_index_cursor/extend_bitpacked_query_sequence_test.cpp:8]: Ah, didn't see the `result_t`. It's fine then

**Review by eseiler — APPROVED** [review]
