### PR TITLE
Makes the exception names of the argument parser consistent

### LINKED ISSUE #481: [Argument Parser] make the exception names consistent
There should be one parser_exception that all the others inherit from and none has `parse_` in its name

### PR DESCRIPTION
**Pull request by smehringer**
Resolves #481

I changed the names according to our resolution in the strategy meeting ([card](https://github.com/orgs/seqan/projects/4#card-26600178))
Additionally, the first commit get's rid of the internal exception in the function retrive_value. The success is indicated by a return value instead and the exception is thrown outside. This also made the exceptions std::type_conversion-error and std::overflow_errow obsolete which lowers the number of exceptions in general.

### CODE REVIEW

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 1]
```diff
@@ -285,84 +292,80 @@ class format_parse : public format_base
...
-     * \param[out] value Stores the casted value.
-     * \param[in]  in    The input argument to be casted.
-     *
-     * \throws seqan3::type_conversion_failed
-     * \throws seqan3::overflow_error_on_conversion
+     * \tparam option_t The optiona value type; must model seqan3::arithmetic.
+     * \param[out] value Stores the cast value.
+     * \param[in] in The input argument to be cast.
+     * \returns seqan3::option_cast_result::type_conversion_error if \p in could not be converted to an arithmetic type
+     *          via std::from_chars, seqan3::option_cast_result::overflow_error if \p in could be converted but the
```
Comment (MitraDarja) [inline include/seqan3/argument_parser/detail/format_parse.hpp]: What does \p stand for?
Do we always shorten \param[in] with \p in?

File: include/seqan3/argument_parser/exceptions.hpp [hunk 2]
```diff
@@ -19,6 +19,17 @@
 namespace seqan3
 {
 
+//!\brief This class is eprecated.
```
Comment (MitraDarja) [inline include/seqan3/argument_parser/exceptions.hpp]: deprecated

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 3]
```diff
@@ -285,84 +292,80 @@ class format_parse : public format_base
 
     /*!\brief Tries to cast an input string into a value.
      * \tparam option_t Must model seqan3::input_stream_over.
-     * \param[out] value Stores the casted value.
-     * \param[in]  in    The input argument to be casted.
-     *
-     * \throws seqan3::type_conversion_failed
+     * \param[out] value Stores the cast value.
+     * \param[in] in The input argument to be cast.
+     * \returns seqan3::option_cast_result::type_conversion_error if \p in could not be converted via the stream
```
[the remark this answers is not in the document]
Comment (smehringer) [reply include/seqan3/argument_parser/detail/format_parse.hpp]: With \p doxygen just formats the next word in code style. I will change it to back ticks ` which isused more frequently

**Comment by smehringer** [comment]
sorry I did not see that you approved already. You can or cannot check the differences and approve again. In general if you find typos, you can request changes as they are just as valid as code changing requests.

File: include/seqan3/argument_parser/exceptions.hpp [hunk 4]
```diff
@@ -133,13 +134,13 @@ class validation_failed : public parser_invalid_argument
  * - Reuse of a short or long identifier (must be unique)
  * - Both identifiers must not be empty (one is ok)
  */
-class parser_design_error : public std::logic_error
+class design_error : public std::logic_error
```
Comment (rrahn) [inline include/seqan3/argument_parser/exceptions.hpp]: in the Changelog you mentioned, that this inherits from argument_parser_error, which I would prefer. I also would not inherit the argument_parser_error from invalid_argument but make it it's own exception.

File: include/seqan3/argument_parser/exceptions.hpp [hunk 5]
```diff
@@ -34,93 +45,83 @@ namespace seqan3
...
     /*!\brief The constructor.
      * \param[in] s The error message.
      */
-    overflow_error_on_conversion(std::string const & s) : parser_invalid_argument(s) {}
+    option_declared_multiple_times(std::string const & s) : argument_parser_error(s) {}
 };
 
 //!\brief Argument parser exception thrown when an argument could not be casted to the according type.
-class validation_failed : public parser_invalid_argument
+class validation_error : public argument_parser_error
```
Comment (rrahn) [inline include/seqan3/argument_parser/exceptions.hpp]: So if I get this right. When people use one of this exceptions they will get an compiler error because it is no longer present. When they used parser_invalid_argument they will get a deprecation message but also thrown exceptions are never catched and the program terminates. So which means we have two options. Either deprecate everything or let the compiler always fail when using old exceptions. I am tending for the former solution. Or am I missing something here?

File: CHANGELOG.md [hunk 6]
```diff
@@ -54,6 +54,13 @@ If possible, provide tooling that performs the changes, e.g. a shell-script.
   the respective instances (e.g. change `input_file_validator` to `input_file_validator<>`).
 * The member type that denotes which arguments a `validator` can validate has been renamed from `value_type` to
   `option_value_type`.
+* **Some exception names were altered and some removed**
+  * The exception seqan3::parser_invalid_argument was renamed to seqan3::argument_parser_error.
+  * The exception seqan3::validation_failed was renamed to seqan3::validation_error.
+  * The exception seqan3::parser_design_error was renamed to seqan3::design_error and also inherits from
+    seqan3::argument_parser_error.
+  * The exception seqan3::type_conversion_failed was removed, you can catch seqan3::user_input_error instead.
```
Comment (rrahn) [inline CHANGELOG.md]: should then be deprecated.

File: CHANGELOG.md [hunk 7]
```diff
@@ -54,6 +54,13 @@ If possible, provide tooling that performs the changes, e.g. a shell-script.
...
+  * The exception seqan3::overflow_error was removed, you can catch seqan3::user_input_error instead.
```
Comment (rrahn) [inline CHANGELOG.md]: should then be deprecated.

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 8]
```diff
@@ -285,84 +292,80 @@ class format_parse : public format_base
...
         requires input_stream_over<std::istringstream, typename container_option_t::value_type>
     //!\cond
-    void retrieve_value(container_option_t & value, std::string const & in)
+    option_cast_result cast_option_value(container_option_t & value, std::string const & in)
     {
-        typename container_option_t::value_type tmp;
+        typename container_option_t::value_type tmp{};
 
-        retrieve_value(tmp, in); // throws on failure
+        auto res = cast_option_value(tmp, in); // throws on failure
```
[the remark this answers is not in the document]
Comment (smehringer) [reply include/seqan3/argument_parser/detail/format_parse.hpp]: Hm.. So when there is a conversion error the tmp variable will not be altered so I am appending the default constructed value. So this is not an issue but probably it is better to not append anything at all.

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 9]
```diff
@@ -285,84 +292,80 @@ class format_parse : public format_base
...
     //!\endcond
 
-    /*!\brief Appends a casted value to its container.
-     *
-     * \tparam container_option_t Must satisfy the seqan3::sequence_container and
-     *                            its value_type must satisfy the seqan3::input_stream_over
-     *
-     * \param[out] value container that stores the casted value.
-     * \param[in]  in    The input argument to be casted.
+    /*!\brief Appends a cast value to its container.
```
[the remark this answers is not in the document]
Comment (smehringer) [reply include/seqan3/argument_parser/detail/format_parse.hpp]: I talked briefly with @marehr about this and decided to switch from `cast` (which I agree is not appropiate) to `parse` everywhere in the documentation.

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 10]
```diff
@@ -406,22 +408,58 @@ class format_parse : public format_base
...
+    template <typename option_type>
+    void throw_on_input_error(option_cast_result const res,
+                              std::string const & option_name,
+                              std::string const & input_value)
+    {
+        std::string msg{"Value cast failed for " + option_name + ": "};
+
+        if (res == option_cast_result::conversion_error)
+        {
+            throw user_input_error{msg + "Argument " + input_value + " could not be cast to type " +
```
[the remark this answers is not in the document]
Comment (smehringer) [reply include/seqan3/argument_parser/detail/format_parse.hpp]: see above -> `parsed`

File: include/seqan3/argument_parser/exceptions.hpp (hunk 4 above)
Comment (smehringer) [reply include/seqan3/argument_parser/exceptions.hpp]: > in the Changelog you mentioned, that this inherits from argument_parser_error, which I would prefer.

Good catch

> I also would not inherit the argument_parser_error from invalid_argument but make it it's own exception.

You mean it should inherit from std::exception instead of std::invalid_argument?

File: include/seqan3/argument_parser/exceptions.hpp (hunk 5 above)
Comment (smehringer) [reply include/seqan3/argument_parser/exceptions.hpp]: Alright, I will deprecate all the old names and we can remove them with 3.1

**Comment by smehringer** [comment]
Sorry, I had to rebase and add a different commit for the renaming in the documentation to keep the history clean. Doing that later would have been too compilcated.

File: include/seqan3/argument_parser/exceptions.hpp (hunk 4 above)
Comment (rrahn) [reply include/seqan3/argument_parser/exceptions.hpp]: Yes, because design_error is not an invalid_argument is it? I would think it is an own error for itself.

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 11]
```diff
@@ -162,15 +162,15 @@ class argument_parser
     argument_parser(argument_parser &&) = default;                  //!< Defaulted.
     argument_parser & operator=(argument_parser &&) = default;      //!< Defaulted.
 
-    /*!\brief Initializes an argument_parser object from the command line arguments.
+    /*!\brief Initializes seqan3::an argument_parser object from the command line arguments.
```
Comment (rrahn) [inline include/seqan3/argument_parser/argument_parser.hpp]:
```suggestion
    /*!\brief Initializes an seqan3::argument_parser object from the command line arguments.
```

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 12]
```diff
@@ -406,22 +413,58 @@ class format_parse : public format_base
...
+    template <typename option_type>
+    void throw_on_input_error(option_parse_result const res,
+                              std::string const & option_name,
+                              std::string const & input_value)
+    {
+        std::string msg{"Value parse failed for " + option_name + ": "};
+
+        if (res == option_parse_result::error)
+        {
+            throw user_input_error{msg + "Argument " + input_value + " could not be cast to type " +
```
Comment (rrahn) [inline include/seqan3/argument_parser/detail/format_parse.hpp]:
```suggestion
            throw user_input_error{msg + "Argument " + input_value + " could not be parsed as type " +
```

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 13]
```diff
@@ -283,86 +290,87 @@ class format_parse : public format_base
...
     //!\cond
-    void retrieve_value(container_option_t & value, std::string const & in)
+    option_parse_result parse_option_value(container_option_t & value, std::string const & in)
     {
-        typename container_option_t::value_type tmp;
+        typename container_option_t::value_type tmp{};
 
-        retrieve_value(tmp, in); // throws on failure
-        value.push_back(tmp);
+        auto res = parse_option_value(tmp, in); // throws on failure
```
Comment (rrahn) [inline include/seqan3/argument_parser/detail/format_parse.hpp]:
```suggestion
        auto res = parse_option_value(tmp, in);
```

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 14]
```diff
@@ -406,22 +413,58 @@ class format_parse : public format_base
...
             value = false;
         else
-            throw type_conversion_failed("Argument '" + in + "' could not be casted to boolean.");
+            return option_parse_result::error;
+
+        return option_parse_result::success;
+    }
+
+    /*!\brief Tries to parse an input string into boolean value.
+     * \param[in] res A result value of parseing an input string to the respective option value type.
```
Comment (rrahn) [inline include/seqan3/argument_parser/detail/format_parse.hpp]:
```suggestion
     * \param[in] res A result value of parsing an input string to the respective option value type.
```

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 15]
```diff
@@ -406,22 +413,58 @@ class format_parse : public format_base
...
+     * \param[in] option_name The name of the option who's input was parsed.
```
Comment (rrahn) [inline include/seqan3/argument_parser/detail/format_parse.hpp]:
```suggestion
     * \param[in] option_name The name of the option whose input was parsed.
```
?

**Comment by rrahn** [comment]
Have you verified the code coverage issue?

**Comment by smehringer** [comment]
It has nothing to do with me. I'll rebase to current master to see if this fixes it.

**Comment by smehringer** [comment]
@rrahn Code coverage only fails because of the filesystem errors that in the file validators were renamed but are not tested. So I think this can be merged.

**Comment by smehringer** [comment]
@rrahn I updated the Changelog entry to link this PR.
The code coverage fail is unrelated to this PR, since it records 4 misses that are due to the untested error handling of the `input_directory_validator`s where I changed the exception names so I trigger the misses again. Fixes the code coverage should be part of another PR, I'll make a card.
