### PR TITLE
[FIX, FEATURE] Fix initialising the version_check_option. Add multi-level argument parsing.

### LINKED ISSUE #1177: Segmentation fault produced by version check on some machines.
Hi,

I am using the argument parser. On one machine the binary runs, on the other I get a segfault.

```
pocki@salz4 /ccb/salz4-2/pocki/HAPLO_RES % gdb ./kmc_unique                                                                                                                                                 :(
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /ccb/salz4-2/pocki/HAPLO_RES/kmc_unique...done.
(gdb) run
Starting program: /ccb/salz4-2/pocki/HAPLO_RES/./kmc_unique 
Detaching after fork from child process 8658.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000004d3c61 in std::thread::detach() ()
#2  0x000000000042b8da in seqan3::detail::version_checker::operator()(std::promise<bool>) ()
#3  0x0000000000435e14 in seqan3::argument_parser::parse() ()
#4  0x0000000000405f8c in main ()
```

I can fix it by turning version-check off. Interestingly the first one works, the second call produces the same segmentation fault (it seems the order of arguments matters ... shouldn't all arguments be parsed first before sending data over the internet? :thinking: ):

```
% ./kmc_unique --version-check 0 --help
***HELP PAGE***
% ./kmc_unique --help --version-check 0
[1]    9131 segmentation fault (core dumped)  ./kmc_unique --help --version-check 0
```

I include omp.h but I don't do anything fancy in my program. If I share the entire code I guess it will be hard to reproduce as it only happens on one of my machines. Do you have any idea that I could try fixing it? Where are the information stored when you first open the program and it asks you whether you want to run version checks every time? Maybe this file got messed up on that machine.

### PR DESCRIPTION
**Pull request by smehringer**
Resolves #1177

### CODE REVIEW

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 1]
```diff
@@ -551,18 +553,18 @@ class argument_parser
             {
                 format = detail::format_help{false};
                 init_standard_options();
-                return;
+                special_format_was_set = true;
```
Comment (cpockrandt) [inline include/seqan3/argument_parser/argument_parser.hpp]: It seems that if you pass multiple special formats (e.g., h and hh), it will overwrite it in the next loop iteration. I think we should either print an error message or always take the first one. Currently it would choose the last argument.

**Comment by h-2** [comment]
How does that work with nested argument parsers? For nested arg parser the version check argument should refer to the nested inner arg parser if it comes after the keyowrd. I suspect these changes will break that.

We really need test-cases for nested arg parsers as it is a commonly used design.

**Comment by rrahn** [comment]
Sorry to jump into this but what is a nested argument parser? Do we have a snippet or demo/tutorial for this? I can only think of a tool with different configurations who have their own options, e.g.samtools.

**Comment by h-2** [comment]
> Sorry to jump into this but what is a nested argument parser? 

A program with different sub-programs, like `git` or `lambda` (equally famous tools ☝️ ). Each sub-program should have their own help/man-page et cetera...

> Do we have a snippet or demo/tutorial for this?

@smehringer said she would write a HowTo at some point (or at least we agreed that we want such a HowTo). Currently we have nothing that tests this, that's why I said new changes threaten to break it.

**Comment by rrahn** [comment]
Ok, this is what I had in mind already.

File: doc/howto/multi_level_argument_parser/multi_level_arg_parse.cpp [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+    return 0;
+}
+
+int main(int argc, char const ** argv)
+{
+    //![construction]
+    argument_parser top_level_parser{"mygit", argc, argv, true, {"push", "pull"}};
+    //![construction]
+
+    // Add information and options to your top level parser just as you would do with a normal one.
```
Comment (eseiler) [inline doc/howto/multi_level_argument_parser/multi_level_arg_parse.cpp]:
```suggestion
    // Add information and options to your top-level parser just as you would do with a normal one.
```

File: doc/tutorial/argument_parser/index.md [hunk 3]
```diff
@@ -466,6 +466,13 @@ that can serve as a copy'n'paste source for your application.
 \include doc/tutorial/argument_parser/solution6.cpp
 \endsolution
 
+# Multi-level argument parsing
+
+Many applications provide several sub programs, e.g. `git` comes with many functionalities like `git push`,
+`git pull`, `git checkout`, etc. each having their own help page.
+If you are interested in how this multi-level parsing can be done with the seqan3::argument_parser,
+take a look at our \link multi_level_arg_parse How-to\endlink.
```
Comment (eseiler) [inline doc/tutorial/argument_parser/index.md]:
```suggestion
take a look at our \link multi_level_arg_parse HowTo\endlink.
```

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 4]
```diff
@@ -389,6 +392,16 @@ class argument_parser
         parse_was_called = true;
     }
 
+    //!\brief Returns a reference to the sub-parser instance if
+    //!       \link multi_level_arg_parse multi-level parsing \endlink was enabled.
+    argument_parser & get_sub_parser()
+    {
+        if (sub_parser == nullptr)
+            throw parser_design_error("You did not enable multi-level parsing on construction "
```
Comment (eseiler) [inline include/seqan3/argument_parser/argument_parser.hpp]: Braces?

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 5]
```diff
@@ -511,13 +524,17 @@ class argument_parser
     //!\brief The future object that keeps track of the detached version check call thread.
     std::future<bool> version_check_future;
 
-    //!\brief Validates the application name to ensure an escaped server call
+    //!\brief Validates the application name to ensure an escaped server call.
     std::regex app_name_regex{"^[a-zA-Z0-9_-]+$"};
 
+    //!\brief Stores the sub-parser in case multi level parsing is enabled on construction.
```
Comment (eseiler) [inline include/seqan3/argument_parser/argument_parser.hpp]:
```suggestion
    //!\brief Stores the sub-parser in case \link multi_level_arg_parse multi-level parsing \endlink is enabled on construction.
```

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 6]
```diff
@@ -553,26 +570,38 @@ class argument_parser
...
         }
 
+        bool special_format_was_set{false};
+        bool sub_parser_was_set{false};
+
         for(int i = 1, argv_len = argc; i < argv_len; ++i) // start at 1 to skip binary name
         {
             std::string arg{argv[i]};
 
+            if (std::find(subcommands.begin(), subcommands.end(), arg) != subcommands.end())
```
Comment (eseiler) [inline include/seqan3/argument_parser/argument_parser.hpp]:
```suggestion
            if (std::ranges::find(subcommands, arg) != subcommands.end())
```

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 7]
```diff
@@ -553,26 +570,38 @@ class argument_parser
...
+            {
+                sub_parser = std::unique_ptr<argument_parser>{new argument_parser{info.app_name + "-" + arg,
```
Comment (eseiler) [inline include/seqan3/argument_parser/argument_parser.hpp]: Why not

```cpp
sub_parser = std::make_unique<argument_parser>(info.app_name + "-" + arg, argc - i, argv + i, false);
```

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 8]
```diff
@@ -629,7 +658,14 @@ class argument_parser
             }
         }
 
-        format = detail::format_parse(argc, std::move(argv_new));
+        if (!special_format_was_set)
+        {
+            if (!subcommands.empty() && !sub_parser_was_set)
+                throw parser_invalid_argument{detail::to_string("Please specify which sub program you want to use ",
```
Comment (eseiler) [inline include/seqan3/argument_parser/argument_parser.hpp]: braces?

File: include/seqan3/argument_parser/detail/format_base.hpp [hunk 9]
```diff
@@ -325,6 +326,19 @@ class format_help_base : public format_base
                 print_line(desc);
         }
 
+        if (!command_names.empty())
+        {
+            derived_t().print_section("Sub Commands");
```
Comment (eseiler) [inline include/seqan3/argument_parser/detail/format_base.hpp]:
```suggestion
            derived_t().print_section("Subcommands");
```

File: include/seqan3/argument_parser/detail/format_base.hpp [hunk 10]
```diff
@@ -325,6 +326,19 @@ class format_help_base : public format_base
...
+            derived_t().print_line("This program must be invoked with one of the following subcommands:", false);
+            for (std::string & name : command_names)
```
Comment (eseiler) [inline include/seqan3/argument_parser/detail/format_base.hpp]:
```suggestion
            for (std::string const & name : command_names)
```

File: test/unit/argument_parser/format_parse_test.cpp [hunk 11]
```diff
@@ -804,3 +804,85 @@ TEST(parse_test, version_check_option_error)
...
+
+        EXPECT_EQ(sub_parser.info.app_name, "top_level-sub1");
+
+        sub_parser.add_positional_option(option_value2, "foo bar");
+
+        EXPECT_NO_THROW(sub_parser.parse());
+        EXPECT_EQ("foo", option_value2);
+    }
+
+    // top level help page
```
Comment (eseiler) [inline test/unit/argument_parser/format_parse_test.cpp]:
```suggestion
    // top-level help page
```

File: test/unit/argument_parser/format_parse_test.cpp [hunk 12]
```diff
@@ -804,3 +804,85 @@ TEST(parse_test, version_check_option_error)
...
+        const char * argv[]{"./top_level", "-h", "2", "sub1", "foo"};
+        argument_parser top_level_parser{"top_level", 5, argv, false, {"sub1", "sub2"}};
+        top_level_parser.add_option(option_value, 'f', "foo", "foo bar");
+
+        testing::internal::CaptureStdout();
+        EXPECT_EXIT(top_level_parser.parse(), ::testing::ExitedWithCode(EXIT_SUCCESS), "");
+        EXPECT_FALSE(std::string{testing::internal::GetCapturedStdout()}.empty());
+    }
+
+    // sub parser help page
```
Comment (eseiler) [inline test/unit/argument_parser/format_parse_test.cpp]:
```suggestion
    // sub-parser help page
```

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 13]
```diff
@@ -511,13 +527,17 @@ class argument_parser
     //!\brief The future object that keeps track of the detached version check call thread.
     std::future<bool> version_check_future;
 
-    //!\brief Validates the application name to ensure an escaped server call
+    //!\brief Validates the application name to ensure an escaped server call.
     std::regex app_name_regex{"^[a-zA-Z0-9_-]+$"};
 
+    //!\brief Stores the sub-parser in case \link multi_level_arg_parse multi-level parsing \endlink is enabled on construction.
```
Comment (eseiler) [inline include/seqan3/argument_parser/argument_parser.hpp]: Line break

**Comment by smehringer** [comment]
Code coverage complains that format man is not tested :roll_eyes:

File: doc/howto/multi_level_argument_parser/multi_level_arg_parse.cpp [hunk 14]
```diff
@@ -0,0 +1,97 @@
...
+    }
+    catch (parser_invalid_argument const & ext)
+    {
+        debug_stream << "[Error] " << ext.what() << "\n";
+        return -1;
+    }
+
+    return 0;
+}
+
```
Comment (h-2) [inline doc/howto/multi_level_argument_parser/multi_level_arg_parse.cpp]:
```suggestion
// =====================================================================================================================
// main
// =====================================================================================================================
```

If you use these in the code, add one before main

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 15]
```diff
@@ -178,14 +180,15 @@ class argument_parser
...
+                    bool version_check = true,
+                    std::vector<std::string> subcommands = {}) :
         version_check_dev_decision{version_check}
     {
         if (!std::regex_match(app_name, app_name_regex))
             throw parser_design_error{"The application name must only contain alpha-numeric characters "
                                                "or '_' and '-' (regex: \"^[a-zA-Z0-9_-]+$\")."};
         info.app_name = std::move(app_name);
-        init(argc, argv);
+        init(argc, argv, subcommands);
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]:
```suggestion
        init(argc, argv, std::move(subcommands));
```

:nail_care:

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 16]
```diff
@@ -553,26 +573,35 @@ class argument_parser
             return;
         }
 
+        bool special_format_was_set{false};
+        bool sub_parser_was_set{false};
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]: Why is this needed? Can't you check if  `unique_ptr != nullptr` ?

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 17]
```diff
@@ -553,26 +573,35 @@ class argument_parser
...
+
         for(int i = 1, argv_len = argc; i < argv_len; ++i) // start at 1 to skip binary name
         {
             std::string arg{argv[i]};
 
+            if (std::ranges::find(subcommands, arg) != subcommands.end())
+            {
+                sub_parser = std::make_unique<argument_parser>(info.app_name + "-" + arg, argc - i, argv + i, false);
+                sub_parser_was_set = true;
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]: I think this won't work in the following case:

```
git --string-option pull --flag bar push --foo
```
In this case it will identify the subcommand as pull, although it is push, or not?

Comment (h-2) [reply include/seqan3/argument_parser/argument_parser.hpp]: Why don't you call parse on the the sub_parser here and return after that? Then you don't need `special_format_was_set` and the extra handling at the end.

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 18]
```diff
@@ -705,7 +743,7 @@ class argument_parser
                  detail::format_html,
                  detail::format_man,
                  detail::format_copyright/*,
-                 detail::format_ctd*/> format{detail::format_help(0)};
+                 detail::format_ctd*/> format{detail::format_help{{}, false}};
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]: Does this need to be initialised?

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 16 above)
Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: left over from previous solutions :see_no_evil:

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 17 above)
Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: > I think this won't work in the following case:

Yes you are right but I do not see how I can avoid that?

> Why don't you call parse on the the sub_parser here and return after that?

Because the sub parser is not set up yet by the user with all its `add_option` calls yet?

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 18 above)
Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: When the constructor is called the format would be default initialised which is not possible because format_parse has no default constructor..?

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 17 above)
Comment (h-2) [reply include/seqan3/argument_parser/argument_parser.hpp]: * forbid options and positionals in the top-level parser if it has subcommends
* forbid subcommands that start with `-` or consist only of numbers

Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: If we do not allow any options anyway we don't need to restrict the command to "may not have only numbers"?

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 19]
```diff
@@ -553,26 +573,33 @@ class argument_parser
             return;
         }
 
+        bool special_format_was_set{false};
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]: Still don't understand why you need this. Just return as before.

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 20]
```diff
@@ -553,26 +573,33 @@ class argument_parser
...
+
         for(int i = 1, argv_len = argc; i < argv_len; ++i) // start at 1 to skip binary name
         {
             std::string arg{argv[i]};
 
+            if (std::ranges::find(subcommands, arg) != subcommands.end())
+            {
+                sub_parser = std::make_unique<argument_parser>(info.app_name + "-" + arg, argc - i, argv + i, false);
+                break;
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]: return here.

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 21]
```diff
@@ -629,7 +656,16 @@ class argument_parser
             }
         }
 
-        format = detail::format_parse(argc, std::move(argv_new));
+        if (!special_format_was_set)
+        {
+            if (!subcommands.empty() && sub_parser == nullptr)
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]:
```suggestion
            if (!subcommands.empty())
```
And remove the check above.

Then this implies that you only reach this point if there was no special format and no subcommand was set.

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 18 above)
Comment (h-2) [reply include/seqan3/argument_parser/argument_parser.hpp]: Well, it's weird because it suggests that it has some kind of special meaning. 

Why not use std::monostate which was created for this purpose?
https://en.cppreference.com/w/cpp/utility/variant/monostate

File: include/seqan3/argument_parser/argument_parser.hpp [hunk 22]
```diff
@@ -166,6 +167,7 @@ class argument_parser
      * \param[in] argc           The number of command line arguments.
      * \param[in] argv           The command line arguments to parse.
      * \param[in] version_check  Notify users about app version updates (default true).
+     * \param[in] subcommands    A list of sub-programs (see \link subcommand_arg_parse subcommand parsing \endlink).
```
Comment (h-2) [inline include/seqan3/argument_parser/argument_parser.hpp]: Why do you use the term "sub-program" here when you use subcommand everywhere else?

File: include/seqan3/argument_parser/detail/format_base.hpp [hunk 23]
```diff
@@ -214,10 +214,11 @@ class format_help_base : public format_base
     ~format_help_base() = default;                                       //!< Defaulted.
 
     /*!\brief Initializes a format_help_base object.
+     * \param[in] names    A list of sub-program names for subcommand argument parsing.
```
Comment (h-2) [inline include/seqan3/argument_parser/detail/format_base.hpp]: here as well

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 19 above)
Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: I need to scan the whole argv in order to strip the version check option from the argv if present at any position. I cannot just return at any place.

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 20 above)
Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: If I return here I need to copy and paste the same if check as comes after the for loop into the current if scope. It is more dry like this.

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 19 above)
Comment (h-2) [reply include/seqan3/argument_parser/argument_parser.hpp]: Hm, it's ugly, but oh well.

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 18 above)
Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: uh I did not know of this :+1:

Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: too bad... If I use std::monostate the std::visit call fails because monostate obviously has no `add_flag` member function :/

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 17 above)
Comment (h-2) [reply include/seqan3/argument_parser/argument_parser.hpp]: I don't core.

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 18 above)
Comment (h-2) [reply include/seqan3/argument_parser/argument_parser.hpp]: Hm, than maybe at least write something like "The state will be overwritten in any case." as comment?

Comment (h-2) [reply include/seqan3/argument_parser/argument_parser.hpp]: Still open.

**Comment by smehringer** [comment]
why did you remove your review? :scream_cat: 
(I already sais the code coverage fails because of the untested man format, if this is the case)

File: include/seqan3/argument_parser/argument_parser.hpp (hunk 18 above)
Comment (smehringer) [reply include/seqan3/argument_parser/argument_parser.hpp]: ok fine

**Comment by h-2** [comment]
I remove my review request not because I am pissed, just so that I know which of the items in the list is actually waiting for me and not me waiting on the other person :wink:

**Comment by smehringer** [comment]
I know, I just thought it is because of the code coverage that bites me any time I do something on the argument parser :innocent:

**Comment by smehringer** [comment]
[issue](https://trello.com/c/zZTGUtVr/4-issue)
