### PR TITLE
[FIX, FEATURE] Add PPC Support

### LINKED ISSUE #1096: Build errors on Ubuntu 19.04 (GNU/Linux 5.2.0-rc4+ ppc64le)
On the machine specified above I found the following build error types:

- `WARN_X86_INTRINSICS`: `#error "Please read comment above.`
- `-Wnarrowing`: narrowing conversions from ‘char’ to ‘signed char’ with `magic_header` (compressed streams)
- `-Wnarrowing`: narrowing conversions from ‘int’ to ‘char’ with `small_string`

Attached there is the log file of the Release build.

[build_release_log.txt](https://github.com/seqan/seqan3/files/3290090/build_release_log.txt)

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #1096

Unit tests with GCC9 Debug and -funsigned-char work for me 
Building on ppc (Debug, GCC8) also works

---
We add `-DNO_WARN_X86_INTRINSICS` for tests to silence the following error from a system header:
```
#ifndef NO_WARN_X86_INTRINSICS
/* This header is distributed to simplify porting x86_64 code that
   makes explicit use of Intel intrinsics to powerpc64le.
   It is the user's responsibility to determine if the results are
   acceptable and make additional changes as necessary.
   Note that much code that uses Intel intrinsics can be rewritten in
   standard C or GNU C extensions, which are more portable and better
   optimized across multiple targets.

   In the specific case of X86 SSE (__m128) intrinsics, the PowerPC
   VMX/VSX ISA is a good match for vector float SIMD operations.
   However scalar float operations in vector (XMM) registers require
   the POWER8 VSX ISA (2.07) level. Also there are important
   differences for data format and placement of float scalars in the
   vector register. For PowerISA Scalar floats in FPRs (left most
   64-bits of the low 32 VSRs) is in double format, while X86_64 SSE
   uses the right most 32-bits of the XMM. These differences require
   extra steps on POWER to match the SSE scalar float semantics.

   Most SSE scalar float intrinsic operations can be performed more
   efficiently as C language float scalar operations or optimized to
   use vector SIMD operations.  We recommend this for new applications.

   Another difference is the format and details of the X86_64 MXSCR vs
   the PowerISA FPSCR / VSCR registers. We recommend applications
   replace direct access to the MXSCR with the more portable <fenv.h>
   Posix APIs. */
#error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
#endif
```

### CODE REVIEW

File: include/seqan3/core/char_operations/predicate_detail.hpp [hunk 1]
```diff
@@ -344,19 +344,50 @@ struct is_in_alphabet_type : public char_predicate_base<is_in_alphabet_type<alph
...
 {
     static_assert(char_v == EOF || static_cast<uint64_t>(char_v) < 256, "TODO");
 
+    //!\brief Helper struct to handle char_v == EOF.
+    static string_helper<char_v> helper;
+
     //!\brief The message representing this condition.
     static constexpr auto msg = small_string{"is_char<'"} +
-                                small_string{char_v}      +
+                                helper.get_string()       +
```
Comment (rrahn) [inline include/seqan3/core/char_operations/predicate_detail.hpp]: and `(char_v == EOF) ? small_string{"EOF"} : small_string<3>(char_v)` did not work?

Comment (eseiler) [reply include/seqan3/core/char_operations/predicate_detail.hpp]: Nope, still `error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]`, because `small_string<3>(char_v)` needs to be valid in the ternary.

**Comment by eseiler** [comment]
travis and jenkins passed, but codecov upload and cdash upload failed 😬

File: include/seqan3/core/char_operations/predicate_detail.hpp (hunk 1 above)
Comment (eseiler) [reply include/seqan3/core/char_operations/predicate_detail.hpp]:
```cpp
    static constexpr auto lam = [] () {
        if constexpr (char_v == EOF)
            return small_string{"EOF"};
        else
            return small_string{char_v};
    };
```

would work ( and then `lam()` instead of `helper.get_string()`).

**Comment by eseiler** [comment]
One more issue:

```console
seiler@???:~/build$ ./range/view/view_take_test 
Running main() from /home/seiler/build/vendor/googletest/googletest/src/gtest_main.cc
[==========] Running 11 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from view_take
[ RUN      ] view_take.regular
[       OK ] view_take.regular (0 ms)
[ RUN      ] view_take.concepts
[       OK ] view_take.concepts (0 ms)
[ RUN      ] view_take.underlying_is_shorter
[       OK ] view_take.underlying_is_shorter (0 ms)
[ RUN      ] view_take.type_erasure
[       OK ] view_take.type_erasure (0 ms)
[----------] 4 tests from view_take (0 ms total)

[----------] 4 tests from view_take_exactly
[ RUN      ] view_take_exactly.regular
/home/seiler/seqan3/test/unit/range/view/view_take_test.cpp:53: Failure
Expected equality of these values:
  "rab"
  v3b
    Which is: "rabof"
[  FAILED  ] view_take_exactly.regular (0 ms)
[ RUN      ] view_take_exactly.concepts
[       OK ] view_take_exactly.concepts (0 ms)
[ RUN      ] view_take_exactly.underlying_is_shorter
[       OK ] view_take_exactly.underlying_is_shorter (0 ms)
[ RUN      ] view_take_exactly.shrink_size_on_input_ranges
[       OK ] view_take_exactly.shrink_size_on_input_ranges (0 ms)
[----------] 4 tests from view_take_exactly (0 ms total)

[----------] 3 tests from view_take_exactly_or_throw
[ RUN      ] view_take_exactly_or_throw.regular
[       OK ] view_take_exactly_or_throw.regular (0 ms)
[ RUN      ] view_take_exactly_or_throw.concepts
[       OK ] view_take_exactly_or_throw.concepts (0 ms)
[ RUN      ] view_take_exactly_or_throw.underlying_is_shorter
[       OK ] view_take_exactly_or_throw.underlying_is_shorter (1 ms)
[----------] 3 tests from view_take_exactly_or_throw (1 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 3 test cases ran. (1 ms total)
[  PASSED  ] 10 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] view_take_exactly.regular

 1 FAILED TEST
```

---

The failing `v3b` is 
```cpp
std::string v3b = vec | std::view::reverse | adaptor(3) | ranges::view::unique | std::ranges::to<std::string>;
```
where `vec = "foobar"`. If you remove, e.g., `ranges::view::unique`, it works. You can also remove some of the other to make it work.

---

Fail matrix (:x: = fail, :white_check_mark: = passes)

|                | no flags           | -fsanitize=unused  | -fsanitize=address |
|----------------|--------------------|--------------------|--------------------|
| Release        | :x:                | :white_check_mark: | :white_check_mark: |
| RelWithDebInfo | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Debug          | :white_check_mark: | :white_check_mark: | :white_check_mark: |

File: include/seqan3/core/platform.hpp [hunk 2]
```diff
@@ -185,6 +185,17 @@
...
 #endif
 
+// ============================================================================
+//  Architectures
+// ============================================================================
+
+// Warn if NO_WARN_X86_INTRINSICS is not set on PowerPC. See https://github.com/seqan/seqan3/pull/1157.
+#if defined(__powerpc64__)
+#   ifndef NO_WARN_X86_INTRINSICS
+#      warning "To use SeqAn3 on PowerPC, you may need to set -DNO_WARN_X86_INTRINSICS. Please note that SeqAn3 is not yet optimised for PowerPC."
```
Comment (rrahn) [inline include/seqan3/core/platform.hpp]: Line wrap?

Comment (eseiler) [reply include/seqan3/core/platform.hpp]: Ok, I changed it.

Looks now like this:
```console
/Users/enricoseiler/git/seqan3/include/seqan3/core/platform.hpp:199:28: error: To use SeqAn3 on PowerPC, you may need to set -DNO_WARN_X86_INTRINSICS.                             Please note that SeqAn3 is not yet optimised for PowerPC. [-Werror]
 #       pragma GCC warning "To use SeqAn3 on PowerPC, you may need to set -DNO_WARN_X86_INTRINSICS. \
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             Please note that SeqAn3 is not yet optimised for PowerPC."
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

(Not that there is no way to do a linebreak AFAIK, you can use `\` to make the preprocessor evaluate the next line in the current expression, but you can't escape the whitespaces used for indentation.)

But I think it looks fine now.

Comment (h-2) [reply include/seqan3/core/platform.hpp]: But does it work? I mean, if they are x86-intrinsics (popcount comes to mind) what happens when they are used on PPC?

Comment (eseiler) [reply include/seqan3/core/platform.hpp]: Tests work fine, except the one I wrote about above.

Internally, if an explicit intel intrinsic pops up, the behaviour is emulated on the PPC (also see the header I added in the first post). This may be a bit slower, but is well defined.
