### PR TITLE
[MISC] Small output fixes of the argument parser.

### LINKED ISSUE #787: small stuff in arg-parser
When validation fails for an option without short/long name, don't print that.

```
Validation failed for option -j/--: Validation Failed - Value 144 is not in range [0,20].
```
→
```
Validation failed for option -j: Validation Failed - Value 144 is not in range [0,20].
```

Also, why does it say `Validation failed` twice?

### PR DESCRIPTION
**Pull request by smehringer**
Fixes #787

### CODE REVIEW

**Comment by h-2** [comment]
SEGMENTATION FAULT :trollface:

File: include/seqan3/argument_parser/detail/format_parse.hpp [hunk 1]
```diff
@@ -219,6 +219,21 @@ class format_parse : public format_base
...
+    * \returns The short_id prepended with a single dash and the long_id prepended with a double dash, separated by '/'.
+    */
+    std::string combine_option_names(char const short_id, std::string const & long_id)
+    {
+        if (short_id == '\0')
+            return prepend_dash(long_id);
+        else if (long_id.empty())
+            return prepend_dash(short_id);
+        else // both are set (note: both cannot be empty, this is caught before)
+            return combine_option_names(short_id, long_id);
```
Comment (eseiler) [inline include/seqan3/argument_parser/detail/format_parse.hpp]: 👀

**Comment by smehringer** [comment]
Note that the changes in the test are done to increase the code coverage.
