### PR TITLE
[FIX] Fix format_html and an issue with format_base.

### LINKED ISSUE #689: export_html.hpp doesn't seem to work completely correctly?
It doesn't actually print the synopsis, and print_footer doesn't print the url or any of the legal things.

### PR DESCRIPTION
**Pull request by joshuak94**
Resolves #689

### CODE REVIEW

File: test/unit/argument_parser/detail/format_html_test.cpp [hunk 1]
```diff
@@ -74,12 +75,18 @@ TEST(html_test, html)
                           "<html lang=\"en\">"
                           "<head>"
                           "<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">"
-                          "<title> &mdash; </title>"
+                          "<title>full &mdash; so short</title>"
```
[the remark this answers is not in the document]
Comment (joshuak94) [reply test/unit/argument_parser/detail/format_html_test.cpp]: :+1:

File: test/unit/argument_parser/detail/format_html_test.cpp [hunk 2]
```diff
@@ -107,8 +114,16 @@ TEST(html_test, html)
...
                           "<strong>Last update:</strong> <br>"
-                          "<strong> version:</strong> <br>"
+                          "<strong>program_full_options version:</strong> <br>"
                           "<strong>SeqAn version:</strong> 3.0.0<br>"
+                          "<h2>Url</h2>"
+                          "www.seqan.de<br>"
+                          "<br>"
+                          "<h2>Legal</h2>"
+                          "<strong>program_full_options Copyright: </strong>short copyright<br>"
+                          "<strong>SeqAn Copyright:</strong> 2006-2015 Knut Reinert, FU-Berlin; released under the 3-clause BSDL.<br>"
```
Comment (eseiler) [inline test/unit/argument_parser/detail/format_html_test.cpp]: 2015 ?

Comment (joshuak94) [reply test/unit/argument_parser/detail/format_html_test.cpp]: Good catch!
