### PR TITLE
[FIX] Doxygen warnings fixed triggered by version update to 1.8.17

### LINKED ISSUE #1499: Warnings with Doxygen Version 1.8.17
2 types of warnings:
- warning: argument 'alph' of command @param is not found in the argument list of ...
- warning: Member eback(T... args) (function) of class ... is not documented.

Full list of warnings:
.../seqan3/include/seqan3/alphabet/composite/alphabet_tuple_base.hpp:392: warning: argument 'alph' of command @param is not found in the argument list of seqan3::structured_aa< sequence_alphabet_t, structure_alphabet_t >::operator=(typename component_type)
.../seqan3/include/seqan3/alphabet/composite/alphabet_tuple_base.hpp:412: warning: argument 'alph' of command @param is not found in the argument list of seqan3::structured_aa< sequence_alphabet_t, structure_alphabet_t >::operator=(typename indirect_component_type)
.../seqan3/include/seqan3/io/stream/iterator.hpp:47: warning: Member eback(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:49: warning: Member egptr(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:55: warning: Member epptr(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:50: warning: Member gbump(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:48: warning: Member gptr(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:57: warning: Member overflow(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:53: warning: Member pbase(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:56: warning: Member pbump(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:54: warning: Member pptr(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/io/stream/iterator.hpp:51: warning: Member underflow(T... args) (function) of class seqan3::detail::stream_buffer_exposer is not documented.
.../seqan3/include/seqan3/alphabet/composite/alphabet_tuple_base.hpp:392: warning: argument 'alph' of command @param is not found in the argument list of seqan3::structured_aa< sequence_alphabet_t, structure_alphabet_t >::operator=(typename component_type)
.../seqan3/include/seqan3/alphabet/composite/alphabet_tuple_base.hpp:412: warning: argument 'alph' of command @param is not found in the argument list of seqan3::structured_aa< sequence_alphabet_t, structure_alphabet_t >::operator=(typename indirect_component_type)

### PR DESCRIPTION
**Pull request by Irallia**
Resolves #1499 :

- Doxygen warnings fixed triggered by version update 1.8.16 -> 1.8.17.
- Removed gbump, because it is never used.

### CODE REVIEW

File: include/seqan3/alphabet/composite/alphabet_tuple_base.hpp [hunk 1]
```diff
@@ -388,7 +388,7 @@ class alphabet_tuple_base :
      * with one of its derived classes (seqan3::qualified).
      * \include test/snippet/alphabet/composite/alphabet_tuple_base_value_assignment.cpp
      */
-    template <typename component_type>
+    template <typename component_type alph>
```
Comment (marehr) [inline include/seqan3/alphabet/composite/alphabet_tuple_base.hpp]: this is syntactically wrong. 

you try to fix this warning:
```
.../seqan3/include/seqan3/alphabet/composite/alphabet_tuple_base.hpp:412: warning: argument 'alph' of command @param is not found in the argument list of seqan3::structured_aa< sequence_alphabet_t, structure_alphabet_t >::operator=(typename indirect_component_type)
```
but I think this warning warns you about a different location, namely the `operator=` of `seqan3::structured_aa`, which is apparently in https://github.com/seqan/seqan3/blob/ddda01f410b8dc83e664ab67a3ca6a87bd28d584/include/seqan3/alphabet/structure/structured_aa.hpp#L81-L88

My guess is that we need to add the templates and that a block comment would be appropiate:

```c++
#if SEQAN3_DOXYGEN_ONLY(1)0 // this complete block is only visible by doxygen.
    //!\copydoc alphabet_tuple_base::alphabet_tuple_base(component_type const alph)
    template <typename component_type>
    constexpr structured_aa(component_type const alph) {}

    //!\copydoc alphabet_tuple_base::alphabet_tuple_base(indirect_component_type const alph)
    template <typename indirect_component_type>
    constexpr structured_aa(indirect_component_type const alph) {}

    //!\copydoc alphabet_tuple_base::operator=(component_type const alph)
    template <typename component_type>
    constexpr structured_aa & operator=(component_type const alph) {}

    //!\copydoc alphabet_tuple_base::operator=(indirect_component_type const alph)
    template <typename indirect_component_type>
    constexpr structured_aa & operator=(indirect_component_type const alph) {}
#endif
```

File: include/seqan3/io/stream/iterator.hpp [hunk 2]
```diff
@@ -44,16 +44,27 @@ struct stream_buffer_exposer : public std::basic_streambuf<char_t, traits_t>
...
+    //!\brief Beginning of the buffered part of the output sequence.
     using base_t::pbase;
+    //!\brief Current position in the output sequence ("put pointer").
     using base_t::pptr;
+    //!\brief End of the buffered part of the output sequence.
     using base_t::epptr;
+    //!\brief Increase put pointer.
     using base_t::pbump;
+    //!\brief Checks for capacity in the given buffer.
     using base_t::overflow;
```
Comment (eseiler) [inline include/seqan3/io/stream/iterator.hpp]: Just wrap this in a `//!\cond` `//!\endcond`. All the members are already documented via their STL counterparts.

File: include/seqan3/io/stream/iterator.hpp [hunk 3]
```diff
@@ -43,18 +43,31 @@ struct stream_buffer_exposer : public std::basic_streambuf<char_t, traits_t>
...
 
+    //!\brief Beginning of the buffered part of the output sequence.
     using base_t::pbase;
+    //!\brief Current position in the output sequence ("put pointer").
     using base_t::pptr;
+    //!\brief End of the buffered part of the output sequence.
     using base_t::epptr;
+    //!\brief Increase put pointer.
     using base_t::pbump;
+    //!\brief Checks for capacity in the given buffer.
```
Comment (eseiler) [inline include/seqan3/io/stream/iterator.hpp]: You can remove the briefs again

File: include/seqan3/alphabet/structure/structured_aa.hpp [hunk 4]
```diff
@@ -77,19 +77,27 @@ class structured_aa :
 
     using base_type::base_type; // Inherit non-default constructors
 
-
+#if SEQAN3_DOXYGEN_ONLY(1)0
     //!\copydoc alphabet_tuple_base::alphabet_tuple_base(component_type const alph)
-    SEQAN3_DOXYGEN_ONLY(( constexpr structured_aa(component_type const alph) {} ))
```
Comment (smehringer) [inline include/seqan3/alphabet/structure/structured_aa.hpp]: We use this syntax elsewhere too right? why does it only break here?

File: include/seqan3/alphabet/structure/structured_aa.hpp [hunk 5]
```diff
@@ -77,19 +77,27 @@ class structured_aa :
...
+
     //!\copydoc alphabet_tuple_base::operator=(indirect_component_type const alph)
-    SEQAN3_DOXYGEN_ONLY(( constexpr structured_aa & operator=(indirect_component_type const alph) {} ))
-    //!\}
+    template <typename indirect_component_type>
+    constexpr structured_aa & operator=(indirect_component_type const alph) {}
+#endif
 
-    // Inherit operators from base
+    //!\brief Inherit operators from base
```
Comment (marehr) [inline include/seqan3/alphabet/structure/structured_aa.hpp]: @smehringer This fixed the break, but we are not sure why. Because the exact same line was used in the other files.

File: include/seqan3/alphabet/structure/structured_aa.hpp (hunk 4 above)
Comment (marehr) [reply include/seqan3/alphabet/structure/structured_aa.hpp]: This change makes the complete stuff more readable.

Comment (smehringer) [reply include/seqan3/alphabet/structure/structured_aa.hpp]: Well personally I disagree, I like the short syntax better as you directly spot the "this is only documentation" in every line instead of only at the top of the list. And additionally this is done in all the other places so I would refrain from changes it here because you just saw it but nowhere else. If we change this, it should be part of another PR.
