### PR TITLE
[FIX] Restrict seqan3::alphabet_variant.

### LINKED ISSUE #2867: [Alphabet]  Open Todo: Contraing alphabet_variant to only allow types with the same underlying char type.
Here is the todo:

https://github.com/seqan/seqan3/blob/master/include/seqan3/alphabet/composite/alphabet_variant.hpp#L125

As this makes the class more constrained. This needs to be done before the 3.1 release since `seqan3::alphabet_variant` is marked stable.

### PR DESCRIPTION
**Pull request by smehringer**
to only accept alphabets with the same underlying char type.

This cannot be tested, since incorrect code would not compile.

since all our alphabets have `char` as underlying type, this did not break anything.

Fixes #2867

### CODE REVIEW

**Comment by smehringer** [comment]
Core Meeting 01.11.2021: 

We will restrict the `seqan3::alphabet_variant` to only work on chars. If we support wide chars can be tested once the use case arrives.

File: include/seqan3/alphabet/composite/alphabet_variant.hpp [hunk 1]
```diff
@@ -122,18 +122,21 @@ template <typename ...alternative_types>
...
     //!\brief The base type.
     using base_t = alphabet_base<alphabet_variant<alternative_types...>,
-                                                   (static_cast<size_t>(alphabet_size<alternative_types>) + ...),
-                                                   char>;
+                                                  (static_cast<size_t>(alphabet_size<alternative_types>) + ...),
+                                                  char>;
+
+    static_assert((std::is_same_v<alphabet_char_t<alternative_types>, char> && ...),
+                  "The alphabet_variant is currently only tested for alphabets with char_type char. "
+                  "Contact as on GitHub if you have a different use case https://github.com/seqan/seqan3 .");
```
Comment (Irallia) [inline include/seqan3/alphabet/composite/alphabet_variant.hpp:138]:
```suggestion
                  "Contact us on GitHub if you have a different use case: https://github.com/seqan/seqan3 .");
```

**Review by Irallia — CHANGES_REQUESTED** [review]
LGFM, just a spelling mistake.

**Review by Irallia — APPROVED** [review]

File: include/seqan3/alphabet/composite/alphabet_variant.hpp [hunk 2]
```diff
@@ -122,18 +122,21 @@ template <typename ...alternative_types>
     requires (detail::writable_constexpr_alphabet<alternative_types> && ...) &&
              (std::regular<alternative_types> && ...) &&
              (sizeof...(alternative_types) >= 2)
-             //TODO same char_type
 //!\endcond
 class alphabet_variant : public alphabet_base<alphabet_variant<alternative_types...>,
                                                (static_cast<size_t>(alphabet_size<alternative_types>) + ...),
```
Comment (eseiler) [inline include/seqan3/alphabet/composite/alphabet_variant.hpp:127]:
```suggestion
                                              (static_cast<size_t>(alphabet_size<alternative_types>) + ...),
```

File: include/seqan3/alphabet/composite/alphabet_variant.hpp [hunk 3]
```diff
@@ -122,18 +122,21 @@ template <typename ...alternative_types>
...
-                                               char> //TODO underlying char t
-
+                                               char>
```
Comment (eseiler) [inline include/seqan3/alphabet/composite/alphabet_variant.hpp:128]:
```suggestion
                                              char>
```

**Review by eseiler — APPROVED** [review]
