### PR TITLE
[I/O] Remove column interface for sequence files

### LINKED ISSUE #1411: [Sequence IO] Remove file column interface
**Level 1 - Easy**

We expose a broken file column interface for our files. Read the documentation of `sequence_file_input` to get to know the interface.

- [ ] Remove all tests for the column interface (usually have `column` in their test name)
- [ ] Remove the `Tuple interface` from the `sequence_file_input` object (all get functions)
- [ ] Remove the `file_as_tuple_type columns_buffer;`
- [ ] Remove the member function `read_columns`
- [ ] Remove the std-overloads for the tuple like interface
- [ ] Remove all `Field column types and tuple type` (see group of types in the beginning)
- [ ] Remove the column based reading from the documentation of sequence_file_input. Check if it is mentioned anywhere else in the documentation!
- [ ] Remove all container_container concepts from the `sequence_file_input_traits` and remove the corresponding documentation
- [ ] Remove the container_container types from sequence_file_input_default_traits_dna/aa

### PR DESCRIPTION
**Pull request by joergi-w**
I have to extend the record's `get_or_ignore` interface for `common_pair`, which is the result of `ranges::zip` with two arguments. Therefore, I use the `template template tuple_like` to cover both `std::tuple` and `common_pair`.

Resolves #1411.

### CODE REVIEW

**Comment by joergi-w** [comment]
Rebased on master because the CHANGELOG caused a merge conflict.

**Comment by joergi-w** [comment]
I had to change the solution of an alignment I/O tutorial exercise, because it was using the column interface. It is now realised with a for-loop over the file.
Additionally there was an error with the snippet output: The reference and read were both taken from index 0 of the alignment. I fixed this in the code as well as in the expected output.

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp [hunk 1]
```diff
@@ -57,51 +57,58 @@ r003	2064	chr2	18	10	5M	*	0	0	TAGGC	*
...
+    seqan3::alignment_file_input mapping_file{tmp_dir/"mapping.sam",
+                                              ref_ids,
+                                              ref_seqs,
+                                              seqan3::fields<seqan3::field::ID,
+                                                             seqan3::field::REF_ID,
+                                                             seqan3::field::MAPQ,
+                                                             seqan3::field::ALIGNMENT>{}};
 
-    auto mapq_filter = std::views::filter([] (auto & rec) { return get<field::MAPQ>(rec) >= 30; });
+    auto mapq_filter = std::views::filter([] (auto & rec) { return seqan3::get<seqan3::field::MAPQ>(rec) >= 30; });
```
Comment (eseiler) [inline doc/tutorial/alignment_file/alignment_file_solution2.cpp]: This `seqan3::get` works?

File: doc/tutorial/alignment_file/index.md [hunk 2]
```diff
@@ -252,9 +252,9 @@ With those information do the following:
 Your program should print the following:
 
 ```
-r001 mapped against 0 with 2 gaps in the read sequence and 2 gaps in the reference sequence.
+r001 mapped against 0 with 1 gaps in the read sequence and 2 gaps in the reference sequence.
```
Comment (eseiler) [inline doc/tutorial/alignment_file/index.md]: Was the old output wrong or was something changed?

Comment (joergi-w) [reply doc/tutorial/alignment_file/index.md]: The old output was wrong. It used the first sequence as the second.

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp (hunk 1 above)
Comment (joergi-w) [reply doc/tutorial/alignment_file/alignment_file_solution2.cpp]: yes, I see no error...

Comment (eseiler) [reply doc/tutorial/alignment_file/alignment_file_solution2.cpp]: Apparently, but I'm wondering why :)

Comment (joergi-w) [reply doc/tutorial/alignment_file/alignment_file_solution2.cpp]: I guess because this `get` has a `seqan3::record` as argument...

File: include/seqan3/io/detail/record.hpp [hunk 3]
```diff
@@ -135,8 +136,8 @@ auto const & get_or_ignore(record<field_types, field_ids> const & r)
 }
 
 //!\copydoc seqan3::detail::get_or_ignore
-template <size_t i, typename ...types>
-auto & get_or_ignore(std::tuple<types...> & t)
+template <size_t i, template <tuple_like ...types_> typename tuple_like_t, typename ...types>
```
Comment (rrahn) [inline include/seqan3/io/detail/record.hpp]: So the this should be a tuple of tulles?

File: include/seqan3/io/sequence_file/output.hpp [hunk 4]
```diff
@@ -152,7 +152,7 @@ namespace seqan3
  * The record-based interface treats the file as a range of tuples (the records), but in certain situations
  * you might have the data as columns, i.e. a tuple-of-ranges, instead of range-of-tuples.
  *
- * You can use column-based writing in that case, it uses operator=() :
+ * You can use column-based writing in that case, it uses operator=() and views::zip():
```
Comment (rrahn) [inline include/seqan3/io/sequence_file/output.hpp]:
```suggestion
 * You can use column-based writing in that case, it uses operator=() and seqan3::views::zip():
```

File: include/seqan3/io/detail/record.hpp (hunk 3 above)
Comment (joergi-w) [reply include/seqan3/io/detail/record.hpp]: No it is not a tuple of tuples. The function was only valid for `std::tuple` as input argument and I want to extend it for seqan3::common_pair. This is needed when we call for instance

```cpp
fout = seqan3::views::zip(ids, seq_quals);
```

Then parameter `t` has type `seqan3::common_pair<string, vector<qualified>>`.

Instead of writing two additional overloads I generalised it to `tuple_like`.

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp [hunk 5]
```diff
@@ -57,51 +57,58 @@ r003	2064	chr2	18	10	5M	*	0	0	TAGGC	*
...
 {
     std::filesystem::path tmp_dir = std::filesystem::temp_directory_path(); // get the temp directory
 
     // read in reference information
-    sequence_file_input<my_traits> reference_file{tmp_dir/"reference.fasta"};
-    concatenated_sequences<std::string> ref_ids = get<field::ID>(reference_file);
-    std::vector<std::vector<dna5>> ref_seqs = get<field::SEQ>(reference_file);
+    seqan3::sequence_file_input reference_file{tmp_dir/"reference.fasta"};
+    seqan3::concatenated_sequences<std::string> ref_ids{};
+    std::vector<std::vector<seqan3::dna5>> ref_seqs{};
```
[the remark this answers is not in the document]
Comment (joergi-w) [reply doc/tutorial/alignment_file/alignment_file_solution2.cpp]: Yes, I swap them!

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp [hunk 6]
```diff
@@ -57,51 +57,58 @@ r003	2064	chr2	18	10	5M	*	0	0	TAGGC	*
...
-    auto mapq_filter = std::views::filter([] (auto & rec) { return get<field::MAPQ>(rec) >= 30; });
+    auto mapq_filter = std::views::filter([] (auto & rec) { return seqan3::get<seqan3::field::MAPQ>(rec) >= 30; });
 
     for (auto & [id, ref_id, mapq, alignment] : mapping_file | mapq_filter)
     {
+        using seqan3::get;
         auto & ref = get<0>(alignment);
         size_t sum_ref{};
-        std::ranges::for_each(ref.begin(), ref.end(), [&sum_ref] (auto c) { if (c == gap{}) ++sum_ref; });
+        std::ranges::for_each(ref.begin(), ref.end(), [&sum_ref] (auto c) { if (c == seqan3::gap{}) ++sum_ref; });
```
[the remark this answers is not in the document]
Comment (joergi-w) [reply doc/tutorial/alignment_file/alignment_file_solution2.cpp]: Then I also use the range based for loop here.

**Comment by joergi-w** [comment]
I rebased on master to solve merge conflicts with the fields renaming (to lowercase).

File: doc/tutorial/alignment_file/alignment_file_solution2.cpp [hunk 7]
```diff
@@ -76,35 +75,36 @@ int main()
...
     }
 
-    seqan3::alignment_file_input mapping_file{tmp_dir/"mapping.sam",
-                                              ref_ids,
-                                              ref_seqs,
-                                              seqan3::fields<seqan3::field::id,
-                                                             seqan3::field::ref_id,
-                                                             seqan3::field::mapq,
-                                                             seqan3::field::alignment>{}};
+    auto const fields = seqan3::fields<seqan3::field::id,
```
Comment (rrahn) [inline doc/tutorial/alignment_file/alignment_file_solution2.cpp]: I would only declare a type here with using. Then construct the type inplace of the constructor argument.

**Comment by rrahn** [comment]
Can you please squash the last two commits.

**Comment by joergi-w** [comment]
> Can you please squash the last two commits.

Sure!
