### PR TITLE
[TEST] Index Benchmark

### LINKED ISSUE #1566: Add microbenchmark for index construction
To evaluate the performance of index creation we need a benchmark that can be executed to show improvements or regressions and compares the construction time to SeqAn2.

### PR DESCRIPTION
**Pull request by Clemapfel**
benchmark construction of fm- and bi-fm-index and compare with seqan2

resolves #1566

### CODE REVIEW

File: test/performance/search/index_construction_benchmark.cpp [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+    return dna_sequence_dict[length];
+}
+
+// ============================================================================
+// seqan3 index construction with dna4 only
+// ============================================================================
+bool formatting_help_has_been_printed = false;
+
+template<typename index_t, std::size_t const length>
+void construct_index_dna(benchmark::State & state)
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: why this function ? isn't `construct_index` enough because it is already templetized by the alphabet type?

Comment (Clemapfel) [reply test/performance/search/index_construction_benchmark.cpp]: I needed to make a special case for the seqan3 benchmark function to react differently when called with dna4 (the same type the seqan2 function is called). 
``construct_index<... dna4>`` calls 
```cpp
30: auto sequence = test::generate_sequence<alphabet_t>(length, 0, SEED);
``` 

while 
``construct_index_dna`` calls
```cpp
80: auto sequence_char = get_sequence(length);
81: std::vector<dna4> sequence = sequence_char | view::char_to<dna4>;
```

This initializes the memory cache in line 52 and if it is already initalized just retrieves it. This is necessary so both the seqan3 and seqan2 function use the exact same sequence. My other option was to compare the template type against seqan3::dna4 and call ``get_sequence`` only then which I figured would be even more messy since that options is completely superflous if ``SEQAN3_HAS_SEQAN2`` evaluates to false (c.f. below). This way it's in a section of the code that's only relevant for the seqan2 comparison

Alternative way (pseudo code):
```cpp
template<typename index_t, std::size_t const length>
void construct_index(benchmark::State & state)
{
    using alphabet_t = typename index_t::char_type;

    if (std::is_same<alphabet_t, seqan3::dna4>:value)
        // call construct_index_dna method only for seqan2 comparison
    else
        // call original method

  (...)
}
```

Comment (Clemapfel) [reply test/performance/search/index_construction_benchmark.cpp]: I couldn't think of a cleaner way

**Comment by Clemapfel** [comment]
Let me know if I should change anything, I want to get these off of my backlog

I'm not sure if there's an error in my code or if these results reflect reality but it seems strange that seqan3 has so much trouble only for small texts but is slightly faster for bigger ones

```
construct_index_seqan3<fm_index<std::vector<dna4>>, 5>                    22375839 ns     22375746 ns           31
construct_index_seqan3<fm_index<std::vector<dna4>>, 50>                   11148532 ns     11148310 ns           66
construct_index_seqan3<fm_index<std::vector<dna4>>, 500>                   8372083 ns      8371841 ns           83
construct_index_seqan3<fm_index<std::vector<dna4>>, 5000>                  6904690 ns      6904545 ns          102
construct_index_seqan3<fm_index<std::vector<dna4>>, 50000>                10536404 ns     10536065 ns           67
construct_index_seqan3<fm_index<std::vector<dna4>>, 500000>               68870512 ns     68868419 ns           10
construct_index_seqan3<fm_index<std::vector<dna4>>, 5000000>             763673684 ns    763580355 ns            1
construct_index_seqan2<Index<String<Dna>, FMIndex<void, cfg>>, 5>             9627 ns         9627 ns        72073
construct_index_seqan2<Index<String<Dna>, FMIndex<void, cfg>>, 50>           13446 ns        13446 ns        52503
construct_index_seqan2<Index<String<Dna>, FMIndex<void, cfg>>, 500>          66011 ns        66009 ns        10746
construct_index_seqan2<Index<String<Dna>, FMIndex<void, cfg>>, 5000>        979003 ns       978978 ns          727
construct_index_seqan2<Index<String<Dna>, FMIndex<void, cfg>>, 50000>     10734212 ns     10733943 ns           66
construct_index_seqan2<Index<String<Dna>, FMIndex<void, cfg>>, 500000>   124561039 ns    124560337 ns            6
construct_index_seqan2<Index<String<Dna>, FMIndex<void, cfg>>, 5000000> 1874113125 ns   1811238968 ns            1
```

File: test/performance/search/index_construction_benchmark.cpp [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+    std::vector<char> imported_seq = get_sequence(length);
+    String<Dna> sequence{};
+
+    for (auto c : imported_seq)
+        sequence += c;
+
+    for (auto _ : state)
+    {
+        index_t index(sequence);
+        indexRequire(index, FibreSA());
```
Comment (eseiler) [inline test/performance/search/index_construction_benchmark.cpp]: Can you add `indexRequire(index, FibreLF());` and see how the times look like>

**Comment by rrahn** [comment]
@Clemapfel thank you for this work. Please let us know if you can finish this PR, otherwise we will take it over.

**Comment by eseiler** [comment]
### Size = 50
```
-----------------------------------------------------------------------------------------------------------------------
Benchmark                                                                             Time             CPU   Iterations
-----------------------------------------------------------------------------------------------------------------------
index_benchmark<std::vector<seqan3::dna4>>/fm_index_1                           9694997 ns      9791667 ns           75
index_benchmark<std::vector<seqan3::aa27>>/fm_index_2                           5568685 ns      5667892 ns          102
index_benchmark<std::string>/fm_index_3                                         5721029 ns      5719866 ns          112
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/fm_index_4              8985347 ns      9027778 ns           90
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/fm_index_5              9003509 ns      8958333 ns           75
index_benchmark<std::vector<std::string>>/fm_index_6                            8857841 ns      8958333 ns           75
index_benchmark<std::vector<seqan3::dna4>>/bi_fm_index_1                       19779454 ns     19847973 ns           37
index_benchmark<std::vector<seqan3::aa27>>/bi_fm_index_2                       18941547 ns     18841912 ns           34
index_benchmark<std::string>/bi_fm_index_3                                     19079965 ns     19003378 ns           37
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/bi_fm_index_4          13235782 ns     13437500 ns           50
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/bi_fm_index_5          13890164 ns     13750000 ns           50
index_benchmark<std::vector<std::string>>/bi_fm_index_6                        13224644 ns     13437500 ns           50

index_benchmark<std::vector<seqan3::dna4>>/seqan2_fm_index_1                      30303 ns        30483 ns        23579
index_benchmark<std::vector<seqan3::aa27>>/seqan2_fm_index_2                      31419 ns        31495 ns        21333
index_benchmark<std::string>/seqan2_fm_index_3                                    36707 ns        36830 ns        18667
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/seqan2_fm_index_4         45773 ns        46039 ns        14933
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/seqan2_fm_index_5         49000 ns        50000 ns        10000
index_benchmark<std::vector<std::string>>/seqan2_fm_index_6                       77448 ns        78125 ns        11200
index_benchmark<std::vector<seqan3::dna4>>/seqan2_bi_fm_index_1                   62199 ns        59375 ns        10000
index_benchmark<std::vector<seqan3::aa27>>/seqan2_bi_fm_index_2                   63646 ns        62779 ns        11200
index_benchmark<std::string>/seqan2_bi_fm_index_3                                 76926 ns        76730 ns         8960
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/seqan2_bi_fm_index_4      94056 ns        94164 ns         7467
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/seqan2_bi_fm_index_5      99653 ns       100442 ns         7467
index_benchmark<std::vector<std::string>>/seqan2_bi_fm_index_6                   154939 ns       153460 ns         4480
```

### Size = 50'000
```
-----------------------------------------------------------------------------------------------------------------------
Benchmark                                                                             Time             CPU   Iterations
-----------------------------------------------------------------------------------------------------------------------
index_benchmark<std::vector<seqan3::dna4>>/fm_index_1                           5314992 ns      5312500 ns          100
index_benchmark<std::vector<seqan3::aa27>>/fm_index_2                           5363862 ns      5301339 ns          112
index_benchmark<std::string>/fm_index_3                                         5965164 ns      5859375 ns          112
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/fm_index_4             19752076 ns     19847973 ns           37
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/fm_index_5             19496426 ns     19761029 ns           34
index_benchmark<std::vector<std::string>>/fm_index_6                           22063284 ns     21972656 ns           32
index_benchmark<std::vector<seqan3::dna4>>/bi_fm_index_1                       10786256 ns     10742188 ns           64
index_benchmark<std::vector<seqan3::aa27>>/bi_fm_index_2                       10948766 ns     10986328 ns           64
index_benchmark<std::string>/bi_fm_index_3                                     12070402 ns     12207031 ns           64
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/bi_fm_index_4          38552500 ns     38651316 ns           19
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/bi_fm_index_5          38460063 ns     38651316 ns           19
index_benchmark<std::vector<std::string>>/bi_fm_index_6                        44046100 ns     43945312 ns           16

index_benchmark<std::vector<seqan3::dna4>>/seqan2_fm_index_1                    6334793 ns      6250000 ns           90
index_benchmark<std::vector<seqan3::aa27>>/seqan2_fm_index_2                    8866397 ns      9027778 ns           90
index_benchmark<std::string>/seqan2_fm_index_3                                 12672620 ns     12834821 ns           56
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/seqan2_fm_index_4      47076433 ns     47916667 ns           15
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/seqan2_fm_index_5      54937820 ns     54687500 ns           10
index_benchmark<std::vector<std::string>>/seqan2_fm_index_6                    73960622 ns     72916667 ns            9
index_benchmark<std::vector<seqan3::dna4>>/seqan2_bi_fm_index_1                12616348 ns     12695312 ns           64
index_benchmark<std::vector<seqan3::aa27>>/seqan2_bi_fm_index_2                15400638 ns     14930556 ns           45
index_benchmark<std::string>/seqan2_bi_fm_index_3                              25356629 ns     25669643 ns           28
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/seqan2_bi_fm_index_4   93827400 ns     93750000 ns            7
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/seqan2_bi_fm_index_5   90320300 ns     89285714 ns            7
index_benchmark<std::vector<std::string>>/seqan2_bi_fm_index_6                190387775 ns    191406250 ns            4
```

### Size = 500'000
```
-----------------------------------------------------------------------------------------------------------------------
Benchmark                                                                             Time             CPU   Iterations
-----------------------------------------------------------------------------------------------------------------------
index_benchmark<std::vector<seqan3::dna4>>/fm_index_1                          33999543 ns     34226190 ns           21
index_benchmark<std::vector<seqan3::aa27>>/fm_index_2                          34804800 ns     34539474 ns           19
index_benchmark<std::string>/fm_index_3                                        38902278 ns     39062500 ns           18
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/fm_index_4            189752975 ns    191406250 ns            4
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/fm_index_5            220274033 ns    218750000 ns            3
index_benchmark<std::vector<std::string>>/fm_index_6                          231449933 ns    229166667 ns            3
index_benchmark<std::vector<seqan3::dna4>>/bi_fm_index_1                       70174778 ns     69444444 ns            9
index_benchmark<std::vector<seqan3::aa27>>/bi_fm_index_2                       73341122 ns     72916667 ns            9
index_benchmark<std::string>/bi_fm_index_3                                     80824457 ns     80357143 ns            7
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/bi_fm_index_4         395090100 ns    398437500 ns            2
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/bi_fm_index_5         438812950 ns    406250000 ns            2
index_benchmark<std::vector<std::string>>/bi_fm_index_6                       458149900 ns    460937500 ns            2

index_benchmark<std::vector<seqan3::dna4>>/seqan2_fm_index_1                   75215814 ns     73660714 ns            7
index_benchmark<std::vector<seqan3::aa27>>/seqan2_fm_index_2                  109371867 ns    109375000 ns            6
index_benchmark<std::string>/seqan2_fm_index_3                                209087800 ns    208333333 ns            3
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/seqan2_fm_index_4     867676500 ns    859375000 ns            1
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/seqan2_fm_index_5     902669700 ns    890625000 ns            1
index_benchmark<std::vector<std::string>>/seqan2_fm_index_6                  1136226400 ns   1125000000 ns            1
index_benchmark<std::vector<seqan3::dna4>>/seqan2_bi_fm_index_1               152813175 ns    152343750 ns            4
index_benchmark<std::vector<seqan3::aa27>>/seqan2_bi_fm_index_2               187564750 ns    187500000 ns            4
index_benchmark<std::string>/seqan2_bi_fm_index_3                             386712450 ns    390625000 ns            2
index_benchmark<std::vector<std::vector<seqan3::dna4>>>/seqan2_bi_fm_index_4 1479774000 ns   1484375000 ns            1
index_benchmark<std::vector<std::vector<seqan3::aa27>>>/seqan2_bi_fm_index_5 1729828200 ns   1718750000 ns            1
index_benchmark<std::vector<std::string>>/seqan2_bi_fm_index_6               2267391900 ns   2234375000 ns            1
```

SeqAn3 seems to be asymptocially faster than SeqAn2 😁

File: test/performance/search/index_construction_benchmark.cpp [hunk 3]
```diff
@@ -0,0 +1,213 @@
...
+
+#include <seqan3/alphabet/nucleotide/dna4.hpp>
+#include <seqan3/alphabet/aminoacid/aa27.hpp>
+#include <seqan3/search/fm_index/all.hpp>
+#include <seqan3/test/performance/sequence_generator.hpp>
+#include <seqan3/test/seqan2.hpp>
+#include <seqan3/range/views/persist.hpp>
+#include <seqan3/range/views/rank_to.hpp>
+#include <seqan3/range/views/to.hpp>
+#include <seqan3/range/views/to_rank.hpp>
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: Please sort this list...

File: test/performance/search/index_construction_benchmark.cpp [hunk 4]
```diff
@@ -0,0 +1,213 @@
...
+#endif
+
+static void arguments(benchmark::internal::Benchmark* b)
+{
+    for (int32_t length : {50, 5000, 50'000})
+    {
+        for (int32_t collection_size : {5})
+        {
+            b->Args({length, collection_size});
+        }
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: Why do we need this loop? Are you planning to add more values later?

File: test/performance/search/index_construction_benchmark.cpp [hunk 5]
```diff
@@ -0,0 +1,213 @@
...
+class sequence_generator
+{
+private:
+    size_t length{50'000};
+    size_t collection_size{5};
+
+    using alphabet_t = seqan3::innermost_value_type_t<rng_t>;
+    using inner_rng_t = std::conditional_t<seqan3::dimension_v<rng_t> == 1,
+                                             rng_t,
+                                             std::ranges::range_value_t<rng_t>>;
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: align with the first template argument, please

File: test/performance/search/index_construction_benchmark.cpp [hunk 6]
```diff
@@ -0,0 +1,213 @@
...
+    {
+        // The characters with rank 254 and 255 are reserved for the indices.
+        if constexpr (seqan3::alphabet_size<alphabet_t> > 254)
+        {
+            return seqan3::test::generate_sequence<alphabet_t>(length, 0, seed)
+                   | seqan3::views::persist
+                   | seqan3::views::to_rank
+                   | std::views::transform([] (uint8_t const r)
+                   {
+                       return (r > 253 ? 253 : r);
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: more comprehensive is:
```suggestion
                       return std::max{r, 253u};
```

File: test/performance/search/index_construction_benchmark.cpp [hunk 7]
```diff
@@ -0,0 +1,213 @@
...
+    inner_rng_t make_single_seqan3(size_t seed = 0)
+    {
+        // The characters with rank 254 and 255 are reserved for the indices.
+        if constexpr (seqan3::alphabet_size<alphabet_t> > 254)
+        {
+            return seqan3::test::generate_sequence<alphabet_t>(length, 0, seed)
+                   | seqan3::views::persist
+                   | seqan3::views::to_rank
+                   | std::views::transform([] (uint8_t const r)
+                   {
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: reconsider whether it is better to indent this `{ .. }` block further, e.g. align with `[]`

File: test/performance/search/index_construction_benchmark.cpp [hunk 8]
```diff
@@ -0,0 +1,213 @@
...
+        {
+            return seqan3::test::generate_sequence<alphabet_t>(length, 0, seed) | seqan3::views::to<inner_rng_t>;
+        }
+    }
+
+    rng_t make_collection_seqan3()
+    {
+        rng_t result;
+        for (size_t i = 0; i < collection_size; ++i)
+            result.emplace_back(make_single_seqan3(i));
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: use `result.reserve(collection_size)` before the loop

File: test/performance/search/index_construction_benchmark.cpp [hunk 9]
```diff
@@ -0,0 +1,213 @@
...
+    seqan::String<to_t> convert_single_range(range_t<from_t> const & original_range)
+    {
+        seqan::String<to_t> result_range;
+        seqan::reserve(result_range, std::ranges::size(original_range));
+
+        for (auto const & element : original_range)
+            appendValue(result_range, seqan3::to_char(element));
+
+        return result_range;
+    }
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: It seems like it possible to replace this whole function by 
```cpp
std::transform(begin(original_range), end(original_range), begin(result_range), seqan3::to_char)
```

File: test/performance/search/index_construction_benchmark.cpp [hunk 10]
```diff
@@ -0,0 +1,213 @@
...
+
+BENCHMARK_TEMPLATE(index_benchmark, bi_fm_index_seqan3, std::vector<seqan3::aa27>)->Apply(arguments);
+#if SEQAN3_HAS_SEQAN2
+BENCHMARK_TEMPLATE(index_benchmark, bi_fm_index_seqan2, std::vector<seqan3::aa27>)->Apply(arguments);
+#endif // SEQAN3_HAS_SEQAN2
+
+BENCHMARK_TEMPLATE(index_benchmark, bi_fm_index_seqan3, std::string)->Apply(arguments);
+#if SEQAN3_HAS_SEQAN2
+BENCHMARK_TEMPLATE(index_benchmark, bi_fm_index_seqan2, std::string)->Apply(arguments);
+#endif // SEQAN3_HAS_SEQAN2
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: Why don't you group all the seqan2 benchmarks in one `#if` block and after that have all seqan3 benchmarks?

File: test/performance/search/index_construction_benchmark.cpp (hunk 4 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: Yes, I planned to; I think I might add a high number, like 100'000 to have some comparison for something-not-genomic.

File: test/performance/search/index_construction_benchmark.cpp (hunk 6 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: `std::min` :) but yes, way more expressive 👍

File: test/performance/search/index_construction_benchmark.cpp (hunk 8 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: I think `reserve` doesn't help here, because `reserve` only allocates the outer vector, so I get a vector of size 5, where the inner elements are vectors of size 0

File: test/performance/search/index_construction_benchmark.cpp (hunk 10 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: I wanted to have the equivalent benchmarks in seqan2 and seqan3 next to each other, rather than having a long block of seqan3 related benchmarks and then a long block of seqan2 related benchmarks...

File: test/performance/search/index_construction_benchmark.cpp (hunk 9 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: I could do
```
std::transform(std::ranges::begin(original_range), std::ranges::end(original_range), seqan::begin(result_range), seqan3::to_char);
```
but this is also two lines, and maybe harder to understand

File: test/performance/search/index_construction_benchmark.cpp (hunk 6 above)
Comment (joergi-w) [reply test/performance/search/index_construction_benchmark.cpp]: true! 😆

File: test/performance/search/index_construction_benchmark.cpp (hunk 8 above)
Comment (joergi-w) [reply test/performance/search/index_construction_benchmark.cpp]: yes, okay 👍

File: test/performance/search/index_construction_benchmark.cpp (hunk 9 above)
Comment (joergi-w) [reply test/performance/search/index_construction_benchmark.cpp]: Yes, but I don't mean to put this code inside the function, but rather you could avoid defining the whole template function (which spans 12 lines) by using `transform` wherever you would otherwise call `convert_single_range`.
You want to make a to_char conversion and in my opinion `transform` should be intuitive enough. 

But I also notice that then you would have to change the calling code, because `transform` has different return semantics etc. so maybe it's more difficult than I think...

File: test/performance/search/index_construction_benchmark.cpp [hunk 11]
```diff
@@ -0,0 +1,237 @@
...
+    }
+
+    template <typename to_t, typename from_t, template <typename> typename range_t>
+        requires (seqan3::alphabet<from_t> && std::ranges::forward_range<range_t<from_t>>)
+    seqan::StringSet<seqan::String<to_t>> convert_range_of_range(std::vector<range_t<from_t>> const & original_range)
+    {
+        seqan::StringSet<seqan::String<to_t>> result_range;
+
+        for (auto const & single_range : original_range)
+            appendValue(result_range, convert_single_range<to_t>(single_range));
```
Comment (joergi-w) [inline test/performance/search/index_construction_benchmark.cpp]: This is my idea from above:
```suggestion
        {
            seqan::reserve(result_range, std::ranges::size(original_range));
            std::transform(std::ranges::begin(single_range), std::ranges::end(single_range), 
                           seqan::begin(result_range), seqan3::to_char);
        }
```

Comment (joergi-w) [reply test/performance/search/index_construction_benchmark.cpp]: Ah, but with `result_range` as the actual element inside the string set.

File: test/performance/search/index_construction_benchmark.cpp [hunk 12]
```diff
@@ -0,0 +1,226 @@
...
+
+static void arguments(benchmark::internal::Benchmark* b)
+{
+    for (int32_t length : {50, 5000, 50'000})
+        b->Args({length, 5});
+
+    b->Args({500, 1'000});
+}
+
+struct fm_index_seqan2;
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: use an enum?

```cpp
class enum index_tag
{
    fm_index_seqan2,
    fm_index_seqan3,
    bi_fm_index_seqan2,
    bi_fm_index_seqan3
}
```

File: test/performance/search/index_construction_benchmark.cpp [hunk 13]
```diff
@@ -0,0 +1,226 @@
...
+    using alphabet_t = seqan3::innermost_value_type_t<rng_t>;
+    using inner_rng_t = std::conditional_t<seqan3::dimension_v<rng_t> == 1,
+                                           rng_t,
+                                           std::ranges::range_value_t<rng_t>>;
+    using fm_index_seqan3_t = decltype(seqan3::fm_index{std::declval<rng_t>()});
+    using bi_fm_index_seqan3_t = decltype(seqan3::bi_fm_index{std::declval<rng_t>()});
+
+    inner_rng_t make_single_seqan3(size_t seed = 0)
+    {
+        // The characters with rank 254 and 255 are reserved for the indices.
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: Do we actually test a text with an alphabet of such a large size? Does our index (the SDSL) even work?
I cannot see a respective test in here.

File: test/performance/search/index_construction_benchmark.cpp [hunk 14]
```diff
@@ -0,0 +1,226 @@
...
+    {
+        if constexpr(seqan3::dimension_v<rng_t> == 1)
+            return make_single_seqan3();
+        else
+            return make_collection_seqan3();
+    }
+
+#if SEQAN3_HAS_SEQAN2
+    // Map the SeqAn3 alphabet to its SeqAn2 equivalent.
+    using seqan2_alphabet_t = std::conditional_t<std::same_as<alphabet_t, seqan3::dna4>, seqan::Dna,
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: why do you need to do this here? 
Can't you write directly into the benchmark template:

```diff
BENCHMARK_TEMPLATE(index_benchmark, bi_fm_index_seqan3, std::vector<seqan3::dna4>)->Apply(arguments);
#if SEQAN3_HAS_SEQAN2
- BENCHMARK_TEMPLATE(index_benchmark, bi_fm_index_seqan2, std::vector<seqan3::dna4>)->Apply(arguments);
+ BENCHMARK_TEMPLATE(index_benchmark, bi_fm_index_seqan2, seqan::String<seqan::Dna>)->Apply(arguments);
#endif // SEQAN3_HAS_SEQAN2
```

This also seems error-prone if change the alphabet to `dna5` for testing, this function will fall back to `char` for seqan2 wihtout any error

File: test/performance/search/index_construction_benchmark.cpp [hunk 15]
```diff
@@ -0,0 +1,226 @@
...
+                                std::conditional_t<std::same_as<alphabet_t, seqan3::aa27>, seqan::AminoAcid, char>>;
+    // SeqAn2: `seqan::String` and `seqan::StringSet`, SeqAn3: `std::vector` and `std::vector<std::vector>`.
+    using seqan2_rng_t = std::conditional_t<seqan3::dimension_v<rng_t> == 1,
+                                            seqan::String<seqan2_alphabet_t>,
+                                            seqan::StringSet<seqan::String<seqan2_alphabet_t>>>;
+    using index_cfg = seqan::FastFMIndexConfig<void, uint32_t>;
+    using fm_index_seqan2_t = seqan::Index<seqan2_rng_t, seqan::FMIndex<void, index_cfg>>;
+    using bi_fm_index_seqan2_t = seqan::Index<seqan2_rng_t, seqan::BidirectionalIndex<seqan::FMIndex<void, index_cfg>>>;
+
+    seqan2_rng_t make_sequence_seqan2()
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: We should introduce a `seqan3::test::generate_seqan2_sequence` into the global test include header since this is something we will need more often.

File: test/performance/search/index_construction_benchmark.cpp [hunk 16]
```diff
@@ -0,0 +1,226 @@
...
+template <typename index_tag_t, typename rng_t>
+void index_benchmark(benchmark::State & state)
+{
+    sequence_generator<index_tag_t, rng_t> generator(state.range(0), state.range(1));
+    for (auto _ : state)
+    {
+#if SEQAN3_HAS_SEQAN2
+        if constexpr (std::same_as<index_tag_t, fm_index_seqan2> || std::same_as<index_tag_t, bi_fm_index_seqan2>)
+        {
+            typename sequence_generator<index_tag_t, rng_t>::index_t index{generator.seqan2};
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: Why do you store this in a member?
```suggestion
            typename sequence_generator<index_tag_t, rng_t>::index_t index{generator.make_seqan2_sequence()};
```

File: test/performance/search/index_construction_benchmark.cpp [hunk 17]
```diff
@@ -0,0 +1,226 @@
...
+            seqan::indexCreate(index, seqan::FibreSALF());
+        }
+        else
+#endif // SEQAN3_HAS_SEQAN2
+            typename sequence_generator<index_tag_t, rng_t>::index_t index{generator.seqan3};
+    }
+}
+
+BENCHMARK_TEMPLATE(index_benchmark, fm_index_seqan3, std::vector<seqan3::dna4>)->Apply(arguments);
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: You are generating the same sequences for every new benchmark right? This is quite inefficient for these many benchmarks :/ make we could store them somehow?
Sorry that this will require some more refactoring but we don't want the benchmark to take too much time.

File: test/performance/search/index_construction_benchmark.cpp (hunk 13 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: `std::string` ? 😁

File: test/performance/search/index_construction_benchmark.cpp (hunk 15 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: https://github.com/seqan/seqan3/blob/1c2b720f52d033924167949932fe231e24fd9db3/test/include/seqan3/test/performance/sequence_generator.hpp#L77-L92

File: test/performance/search/index_construction_benchmark.cpp (hunk 17 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: The sequence generation isn't acutally taking long, but I can refactor the tests.

The whole point of the class was to use the same sequences for seqan2 and seqan3, but I can just generate them individually and store them.

In this case, I would also block this PR by #920 such that I have the numeric sequence generator for generating char-sequences for seqan3 (numeric-sequence -> to_char?), because I think this is easier then generating a char sequence and then filtering out the ranks that are too high.

Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: I could actually just store a long enough sequence, and then do `| seqan3::views::drop(length)` on it. the view should produce overhead, but then again I'm not entirely sure ... but it would be a quite elegant solution?

File: test/performance/search/index_construction_benchmark.cpp (hunk 15 above)
Comment (smehringer) [reply test/performance/search/index_construction_benchmark.cpp]: or maybe templatize over the range_type?

File: test/performance/search/index_construction_benchmark.cpp (hunk 17 above)
Comment (smehringer) [reply test/performance/search/index_construction_benchmark.cpp]: > In this case, I would also block this PR by #920 such that I have the numeric sequence generator for generating char-sequences for seqan3 (numeric-sequence -> to_char?), because I think this is easier than generating a char sequence and then filtering out the ranks that are too high.

:+1: 

> I could just store a long enough sequence, and then do | seqan3::views::take(length) on it. the view should produce overhead, but then again I'm not entirely sure ... but it would be a quite elegant solution?

Indeed this would be elegant :) And I think it would be comparable if you use 
`seqan3::views::take(length) | seqan3::views::to<std::vector>` ? This, of course, involves copying but this should not be a major performance bottleneck.. Or you could use vies::take for seqan3 and `Infix<>` for seqan2?

Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: Yes, something like this. I'll try it out and then we can talk about it on monday 👍

File: test/performance/search/index_construction_benchmark.cpp [hunk 18]
```diff
@@ -9,218 +9,188 @@
...
+#include <seqan3/core/type_traits/lazy.hpp>
 #include <seqan3/range/views/persist.hpp>
 #include <seqan3/range/views/rank_to.hpp>
-#include <seqan3/range/views/to.hpp>
-#include <seqan3/range/views/to_rank.hpp>
 #include <seqan3/search/fm_index/all.hpp>
 #include <seqan3/test/performance/sequence_generator.hpp>
 #include <seqan3/test/seqan2.hpp>
 
+
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: remove newline

File: test/performance/search/index_construction_benchmark.cpp [hunk 19]
```diff
@@ -9,218 +9,188 @@
...
-static void arguments(benchmark::internal::Benchmark* b)
+static constexpr int32_t max_length{50'000};
+static constexpr size_t seed{0x6126f};
+
+static void arguments(benchmark::internal::Benchmark * b)
 {
     for (int32_t length : {50, 5000, 50'000})
+    {
+        if (length > max_length)
+            throw std::logic_error{"Increase max_length to at least " + std::to_string(length)};
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]:
```suggestion
            throw std::logic_error{"Increase max_length to at most " + std::to_string(max_length)};
```
:eyes: ?

File: test/performance/search/index_construction_benchmark.cpp [hunk 20]
```diff
@@ -9,218 +9,188 @@
...
-    size_t collection_size{5};
+    std::vector<seqan3::dna4> const dna4_rng{seqan3::test::generate_sequence<seqan3::dna4>(max_length, 0, seed)};
+    std::vector<seqan3::aa27> const aa27_rng{seqan3::test::generate_sequence<seqan3::aa27>(max_length, 0, seed)};
+    std::string const char_rng{seqan3::test::generate_numeric_sequence<uint8_t>(max_length, 0, 253, seed)
+                               | seqan3::views::persist
+                               | seqan3::views::rank_to<char>
+                               | seqan3::views::to<std::string>};
+};
+
+sequence_store_seqan3 store3;
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]:
```suggestion
sequence_store_seqan3 store{};
```
I like the design :)

File: test/performance/search/index_construction_benchmark.cpp [hunk 21]
```diff
@@ -9,218 +9,188 @@
...
+        inner_sequence = store3.dna4_rng | seqan3::views::take(state.range(0)) | seqan3::views::to<inner_rng_t>;
+    else if constexpr (std::same_as<alphabet_t, seqan3::aa27>)
+        inner_sequence = store3.aa27_rng | seqan3::views::take(state.range(0)) | seqan3::views::to<inner_rng_t>;
+    else
+        inner_sequence = store3.char_rng | seqan3::views::take(state.range(0)) | seqan3::views::to<inner_rng_t>;
+
+    if constexpr (seqan3::dimension_v<rng_t> == 1)
+        sequence = std::move(inner_sequence);
+    else
+        for (int32_t i = 0; i < state.range(1); ++i)
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: braces around multi-line if else clause

File: test/performance/search/index_construction_benchmark.cpp [hunk 22]
```diff
@@ -0,0 +1,196 @@
...
+        if constexpr (index_tag == tag::fm_index)
+        {
+            seqan::Index<rng_t, seqan::FMIndex<void, index_cfg>> index{sequence};
+            seqan::indexCreate(index, seqan::FibreSALF());
+        }
+        else
+        {
+            seqan::Index<rng_t, seqan::BidirectionalIndex<seqan::FMIndex<void, index_cfg>>> index{sequence};
+            seqan::indexCreate(index, seqan::FibreSALF());
+        }
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]:
```cpp
using index_type = std::conditional_t<index_tag == tag::fm_index, seqan::FMIndex<void, index_cfg>, seqan::BidirectionalIndex<seqan::FMIndex<void, index_cfg>>>;
seqan::Index<rng_t, index_type> index{sequence};
seqan::indexCreate(index, seqan::FibreSALF());
```
instead of the if else clause

File: test/performance/search/index_construction_benchmark.cpp (hunk 19 above)
Comment (eseiler) [reply test/performance/search/index_construction_benchmark.cpp]: Mhm, either I decrease `length` or increase `max_length`; I only care about `length <= max_length` so I don't take a prefix longer than the sequence.

File: test/performance/search/index_construction_benchmark.cpp [hunk 23]
```diff
@@ -0,0 +1,197 @@
...
+        inner_sequence = seqan::prefix(store2.dna4_rng, state.range(0));
+    else if constexpr (std::same_as<alphabet_t, seqan::AminoAcid>)
+        inner_sequence = seqan::prefix(store2.aa27_rng, state.range(0));
+    else
+        inner_sequence = seqan::prefix(store2.char_rng, state.range(0));
+
+    if constexpr (dimension == 1)
+        sequence = std::move(inner_sequence);
+    else
+        for (int32_t i = 0; i < state.range(1); ++i)
```
Comment (smehringer) [inline test/performance/search/index_construction_benchmark.cpp]: multi line else block with braces
