### PR TITLE
[fix] clang: use source-level subsumption

### LINKED ISSUE #524: [clang-concepts] normalization of constraints
Code like:

https://github.com/seqan/seqan3/blob/147a7111c16801dba01a32fd7d9301b9e9eaf044/include/seqan3/core/metafunction/range.hpp#L201-L222

and

https://github.com/seqan/seqan3/blob/147a7111c16801dba01a32fd7d9301b9e9eaf044/include/seqan3/core/metafunction/range.hpp#L242-L255

seem to be not concept-ts conforming.

I opened a discussion at https://github.com/saarraz/clang-concepts/issues/23 where the concept implementer  said that this is not standard conforming.

A suggested fix for this situation can also be found in https://github.com/saarraz/clang-concepts/issues/23.

### PR DESCRIPTION
**Pull request by marehr**
fixes #524; a problem with normalization of constaints

### CODE REVIEW

**Comment by marehr** [comment]
Since #557 addresses #520; What should the Concept name be in this case?

File: include/seqan3/core/metafunction/range.hpp [hunk 1]
```diff
@@ -180,20 +190,20 @@ struct size_type<rng_t>
...
+struct innermost_value_type<t>
 {
     //!\brief The return type (recursion not shown).
     using type = value_type_t<remove_cvref_t<t>>;
 };
 
 //!\cond
 template <typename t>
-    requires requires (t)
+    requires detail::has_value_type<t> && requires
```
Comment (h-2) [inline include/seqan3/core/metafunction/range.hpp]: why not change this to just
```cpp
requires detail::has_value_type<t> && detail::has_value_type<value_type_t<t>>
```
Or does this fail because of GCC not lazy instantiating? Then you could still do:
```cpp
requires detail::has_value_type<t> && detail::has_value_type<detail::type_trait_or_t<value_type<t>, void>
```

File: include/seqan3/core/metafunction/range.hpp [hunk 2]
```diff
@@ -220,18 +230,20 @@ using innermost_value_type_t = typename innermost_value_type<t>::type;
  * Attention, this metafunction implicitly removes cv-qualifiers and reference from the types it recurses on and
  * returns.
  */
+template <typename t>
+constexpr size_t dimension_v = 0;
+
```
Comment (h-2) [inline include/seqan3/core/metafunction/range.hpp]: Why do you want to add this anchor that makes the statement valid for types where it makes no sense? Is this required for something?

File: include/seqan3/core/metafunction/range.hpp [hunk 3]
```diff
@@ -57,6 +57,16 @@
 //NOTE(h-2): for the range overloads we explicitly forbid that the type is iteratoer
 // because some types are actually both (e.g. std::directory_iterator)
 
+namespace seqan3::detail
+{
+
+//!\cond
+template <typename t>
+concept has_value_type = requires { typename value_type_t<remove_cvref_t<t>>; };
```
Comment (smehringer) [inline include/seqan3/core/metafunction/range.hpp]: 1) Why the extra concept? I remember from one of the meeting C++ talks that `requires requires` clauses are not recommended but is this the reason or was there a specialization issue?

2) If we do have an extra concept shouldn't this go into `/core` and be used in all similar places?

Comment (marehr) [reply include/seqan3/core/metafunction/range.hpp]: 1.
    Here, the problem is that we use the overload-resolution property of concepts. 

    If we don't use a single concept `detail::has_value_type` here, the compiler does not now that both statements are the same (the definition of "same" is if the same line number in the same file of a concept matches) and `innermost_value_type` would not see that the second definition is a more specialized version of the first one.

    ```c++
    template <typename t>
        requires detail::has_value_type<t>
    struct innermost_value_type

    template <typename t>
        requires detail::has_value_type<t> && detail::has_value_type<value_type_t<remove_cvref_t<t>>>
    struct innermost_value_type<t>
    ```

2. The extra concept is only local, therefore in the same file. If we need that in other file we can think about the location.

**Comment by marehr** [comment]
@h-2  ping
