### PR TITLE
[FIX] Wrong soft clipping values for short cigar strings of length two was fixed.

### LINKED ISSUE #1327: Getting field::ALIGNMENT leads to crash with some softclipped SAM records
## Platform

  - SeqAn version: lastest commit to date (`c326cff`)
  - Operating system: `Linux ppericard-matam-dev 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
  - Compiler: `g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

## Description

When outputting fields from SAM alignment records, the program crashes with the following error only when getting field::ALIGNMENT for some specific records (that have a lot of soft-clipping at the end) 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  end_pos argument to seqan3::views::slice must be >= the begin_pos argument.
Aborted (core dumped)
```

### How to repeat the problem

Here is a sample SAM file ([sample_bug.sam.txt](https://github.com/seqan/seqan3/files/3774669/sample_bug.sam.txt))

```
ECO_X80725-396/2	0	AAAA02020713.1.1297	73	255	99M1S	*	0	0	GATGACCAGCAACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGTAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCG	CACCCE1GGGGGGEGG=<GGGGGGGGGFGGGGGGGGGGGGGFGGGD/GFG1GGGGGGGGGGGFGGBGG1GGGGGEGBEGG0GGGDFGGG=GGGGEG=EGB	AS:i:188	NM:i:2
SSO_FR870445-352/2	16	AAAA02020713.1.1297	353	255	2S98M	*	0	0	CCCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTC	08GGGGGEGGGE/GGGEGGGGGC>GGGGGGG<GG>FGGGGGGGGG/GGGGEGGGFFGGGGGGGGGGGGDG@G<GGGGCGGGG;1GGGGGGGGGGGBBCBB	AS:i:196	NM:i:0
VCH_X76337-258/1	16	EF105671.1.1426	115	255	40M60S	*	0	0	AGAGGGGGATAACCATTGGAAACGATGGCTAATACCGCATAACCTCGCAAGAGCAAAGCAGGGGACCTTCGGGCCTTGCGCTACCGGATATGCCCAGGTG	GGG@GGGCGCGGGGGGFGDCGGGBGGGGGGGGGGGGGGGGG1GGG/GBGGGGG@GGGGGGGGGGGG?GGGGGGGGGGGGGGGGGGGGGGGGGGGGCCCCB	AS:i:80	NM:i:0
VCH_X76337-296/1	0	EF105671.1.1426	115	255	40M60S	*	0	0	AGAGGGGGATAACCATTGGAAACGATGGCTAATACCGCATAACCTCGCAAGAGCAAAGCAGGGGACCTTCGGGCCTTGCGCTACCGGATATGCCCAGGTG	CACCBGGCGGGE@GGGDGGGGGG@GGGG>GGG>GGGGGGGGGGGGGGBGGGGGBGGGDGG<CCCGGGGGGGGGEGGGGGFDGGGGGGGG0GGDGG0G0GG	AS:i:80	NM:i:0
```

The corresponding reference fasta file ([sample_bug.ref.fa.txt](https://github.com/seqan/seqan3/files/3774670/sample_bug.ref.fa.txt))

```
>AAAA02020713.1.1297
gaacccagatgggattagctagtaggcggggtaacggcccacctaggcgacgatccctagctggtctgagaggatgacca
gccacactggaactgagacacggtccagactcctacgggaggcagcagtggggaatattgcacaatgggcgcaagcctga
tgcagccatgccgcgtgtatgaagaaggccttcgggttgtaaagtactttcagcggggaggaaggcgatgtggttaatac
ctttgctcattgacgttacccgcagaagaagcaccggctaactccgtgccagcagccgcggtaatacggagggtgcaagc
gttaatcggaattactgggcgtaaagcgcacgcaggcggtttgttaagtcagatgtgaaatccccgggctcaacctggga
actgcatctgatactggcaagcttgagtctcgtagaggggggtagaattccaggtgtagcggtgaaatgcgtagagatct
ggaggaataccggtggcgaaggcggccccctggacgaagactgacgctcaggtgcgaaagcgtggggagcaaacaggatt
agataccctggtagtccacgccgtaaacgatggaagctagccgttgggggatttatctctcggtggcgcagttaacgcat
taagcttcccgcctggggagtacggtcgcaagattaaaactcaaaggaattgacgggggcccgcacaagcggtggagcat
gtggtttaattcgaagcaacgcgcagaaccttaccagcccttgacatgccctgacggctccagagatggagctattcctt
cgggacaggtgcacaggtgctgcatggctgtcgtcagctcgtgtcgtgagatgttgggttaagtcccgcaacgagcgcaa
ccctcgcccttagttgccagcattcagttgggcactctagggggactgccggtgataagccgagaggaaggtggggatga
cgtcaagtcctcatggcccttacgggctgggctacacacgtgctacaatggcggtgacagtgggcagccagaccgcgagg
tcgagctaatcccaaaaagccgtctcagttcggattgcactctgcaactcgagtgcatgaagttggaatcgctagtaatc
gtggctcagcatgccacggtgaatacgttcccgggccttgtacacaccgcccgtcacaccatgggagttggttctacccg
acgacgctgcgctaaccttcggggggcaggcggccacggtaggatcagcgactggggtgaagtcgtaacaaggtagccgt
aggggaacctgcggctg
>EF105671.1.1426
tcagattgaacgctggtggcatgcttaacacatgcaagtcgaacggtaacaggcagactttgtctgtgctgacgagtggc
gaacgggtgagtaacgcgtagggacctgccttacagagggggataaccattggaaacgatggctaataccgcatgatgcc
taagggtgaaagggtggccttggtgctgccgctgtaagatggacctgcgttagattagcttgttggtggggtaatggcct
gccaaggcgatgatctatagctgttttgagaggaagatcagccacactgggactgagacacggcccagactcctacggga
ggcagcagtggggaatattggacaatgggggcaaccctgatccagcaatgccacgtgtgtgaagaaggccttagggttgt
aaagcacttttagtcaggaggaagttcattggcttaacaggctgatggaattgacgttactgacagaaaaagcaccggct
aactccgtgccagcagccgcggtaatacggagggtgcaagcgttaatcggaattactgggcgtaaagggttcgtaggcgg
tcagataagttagatgtgaaagccctgggctcaacctggggaattgcatttaatactgtctgactcgagtacagtagagg
agagaggaatttccagtgtagcggtgaagtgcgtagagattggaaggaacaccagtggcgaaggcgactctctggactga
tactgacgctgaggaacgaaagcttgggtagcaaacaggattagataccctggtagtccaagccgtaaacgatgagtact
agctgttgggcctggtgtaataggtctcgtagcgaaactaacgcgctaagtactccgcctggggactacggccgcaaggc
taaaactcaaaggaattgacggggacccgcacaagcggtggagcatgtggtttaattcgatgcaacgcgaagaaccttac
ctgcccttgacatgccaggaactatccagagatggatgggtgcctacgggagcctggacacaggtgctgcatggctgtcg
tcagctcgtgtcgtgagatgttgggttaagtcccgtaacgagcggaacccttattgccagttgccatcattaagttgggg
actctggtgagactgccgtggctaacacggaggaaggtggggacgacgtcaagtcatcatggccttacgggcagggctac
acacgtgctacaatggctactacagagggaagcgaaggggcgacctggagcgaaacccttaaaggtagtcttagtccgga
ttgatctctgcaactcgggatcatgaagccggaatcgctagtaatcgcagatcagcatgctgcggtgaatacgttcccgg
gtcttgtacacaccgcccgtcacaccacggaagtgggctgcaccagaagtggctagctgaacttcg
```

And a sample code to reproduce the error:

```
#include <seqan3/argument_parser/all.hpp>     // includes all necessary headers
#include <seqan3/io/alignment_file/all.hpp>
#include <seqan3/io/sequence_file/all.hpp>
#include <seqan3/core/debug_stream.hpp>  // our custom output stream
#include <seqan3/std/filesystem>          // use std::filesystem::path

using namespace seqan3;

struct cmd_arguments
{
    std::filesystem::path input_path{};
    std::filesystem::path reference_path{};
};

void initialize_argument_parser(argument_parser & parser, cmd_arguments & args)
{
    parser.add_option(args.input_path, 'i', "input-sam", "Input SAM/BAM file",
                      option_spec::REQUIRED, input_file_validator{{"sam","bam"}});
    
    parser.add_option(args.reference_path, 'r', "reference", "Reference fasta file",
                      option_spec::REQUIRED, input_file_validator{{"fa","fasta"}});
}

struct reference_traits : public sequence_file_input_default_traits_dna
{
    template <typename _sequence_container>
    using sequence_container_container = std::vector<_sequence_container>;
};

void run_ovgraphbuild(std::filesystem::path & input_path, std::filesystem::path & reference_path)
{
    // Read the reference file
    debug_stream << "INFO: reading reference file" << std::endl;
    
    sequence_file_input<reference_traits> reference_file{reference_path};
    concatenated_sequences<std::string> ref_ids = get<field::ID>(reference_file);
    std::vector<std::vector<dna5>> ref_seqs = get<field::SEQ>(reference_file);
    
    debug_stream << "INFO: finished reading reference file (" << ref_seqs.size() << " records)" << std::endl;
    
    alignment_file_input input_file{input_path,
                                    ref_ids,
                                    ref_seqs,
                                    fields<field::ID,
                                           field::SEQ,
                                           field::OFFSET,
                                           field::REF_OFFSET,
                                           field::ALIGNMENT,
                                           field::CIGAR,
                                           field::REF_ID>{}};
    
    for (auto & [id, seq, offset, ref_offset, alignment, cigar, ref_id] : input_file)
    {
        debug_stream << std::endl;
        debug_stream << "read id:    " << id << std::endl;
        debug_stream << "ref id:     " << ref_id << std::endl;
        debug_stream << "ref offset: " << ref_offset << std::endl;
        debug_stream << "cigar:      " << cigar << std::endl;
        debug_stream << "alignment:  " << alignment << std::endl;
        debug_stream << "read seq:   " << seq << std::endl;
        debug_stream << "seq offset: " << offset << std::endl;
        debug_stream << "#################" << std::endl;
    }
}

int main(int argc, char ** argv)
{
    argument_parser myparser{"OvGraphBuild", argc, argv, false};        // initialise myparser // turn off version check

    cmd_arguments args{};
    
    initialize_argument_parser(myparser, args);
    
    try
    {
         myparser.parse();                                          // trigger command line parsing
    }
    catch (parser_invalid_argument const & ext)                     // catch user errors
    {
        debug_stream << "[Argument parsing error] " << ext.what() << "\n"; // customise your error message
        return -1;
    }
    
    // parsing was successful !
    // we can start running our program
    run_ovgraphbuild(args.input_path, args.reference_path);
    
    debug_stream << "Hello world\n";
    return 0;
}
```

This code was compiled using the CMakeFile suggested in the SeqAn3 tutorial.

The program can then be run like this:

`./test_program -i sample_bug.sam -r sample_bug.ref.fa`

### Expected behaviour

Print all fields for all SAM records

### Actual behaviour

It will output the expected output fields for the first 2 records in the SAM file before crashing with the following error:

```
INFO: reading reference file
INFO: finished reading reference file (2 records)

read id:    ECO_X80725-396/2
ref id:     0
ref offset: 72
cigar:      [99M,1S]
alignment:  (GATGACCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGC,ATGACCAGCAACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGTAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGC)
read seq:   GATGACCAGCAACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGTAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCG
seq offset: 1
#################

read id:    SSO_FR870445-352/2
ref id:     0
ref offset: 352
cigar:      [2S,98M]
alignment:  (CAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTC,CAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTC)
read seq:   CCCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTC
seq offset: 2
#################
terminate called after throwing an instance of 'std::invalid_argument'
  what():  end_pos argument to seqan3::views::slice must be >= the begin_pos argument.
Aborted (core dumped)
```

You can run the code without error by simply removing field::ALIGNMENT from the alignment_file_input fields.

### PR DESCRIPTION
**Pull request by smehringer**
Resolves #1327

### CODE REVIEW

File: include/seqan3/io/alignment_file/format_sam.hpp [hunk 1]
```diff
@@ -559,13 +559,15 @@ class alignment_file_input_format_REMOVEME<format_sam>
...
+        else if (cigar_vector.size() > 1 && 'H'_cigar_op == cigar_vector[0] && 'S'_cigar_op == cigar_vector[1])
             sc_begin = get<0>(cigar_vector[1]);
 
         // check for soft clipping at the last two positions
         if (cigar_vector.size() > 1 && 'S'_cigar_op == cigar_vector[cigar_vector.size() - 1])
             sc_end = get<0>(cigar_vector[cigar_vector.size() - 1]);
-        else if (cigar_vector.size() > 2 && 'S'_cigar_op == cigar_vector[cigar_vector.size() - 2])
+        else if (cigar_vector.size() > 2 &&
+                 'H'_cigar_op == cigar_vector[cigar_vector.size() - 1] &&
+                 'S'_cigar_op == cigar_vector[cigar_vector.size() - 2])
```
Comment (rrahn) [inline include/seqan3/io/alignment_file/format_sam.hpp]: not sure but can you check that if the condition block spans more than one line whether we have to wrap the expression in `{}` or not? I had the impression that when ever a if/for etc. expression spans multiple lines to wrap it in braces.

Comment (smehringer) [reply include/seqan3/io/alignment_file/format_sam.hpp]: I don't find this specific. What would you like?

Comment (smehringer) [reply include/seqan3/io/alignment_file/format_sam.hpp]: @rrahn ping

Comment (rrahn) [reply include/seqan3/io/alignment_file/format_sam.hpp]:
```cpp
if (expression too
     long)
{
  // make braces
}
```

Comment (smehringer) [reply include/seqan3/io/alignment_file/format_sam.hpp]: I made the expression short by caching the vector size. take a look. I think this is even more readable.

File: include/seqan3/io/alignment_file/format_sam.hpp [hunk 2]
```diff
@@ -556,17 +556,19 @@ class alignment_file_input_format_REMOVEME<format_sam>
      */
     void transfer_soft_clipping_to(std::vector<cigar> const & cigar_vector, int32_t & sc_begin, int32_t & sc_end) const
     {
+        auto v_size = cigar_vector.size();
```
Comment (rrahn) [inline include/seqan3/io/alignment_file/format_sam.hpp]: well it is much better. Since it is a fix. We merge it right now. I will make another PR to clean the code a little up.

**Comment by rrahn** [comment]
Sorry, I totally forgot to request a test for the fix. Can you please add a test as well, that fails with the old behavior and is fixed with the new one. For the future we should look that we don't commit fixes without tests. It was my bad, that I didn't realised it earlier. Sorry for that.

**Comment by rrahn** [comment]
Oh, ok I did not see that there was a test for it. Sorry
