### PR TITLE
[FIX] Make char_is_valid member function public for alphabet_variant.

### LINKED ISSUE #1972: [Bug] seqan3::is_in_alphabet has wrong results with gapped alphabets
## Platform

  - SeqAn version: 3.0.2
  - Operating system: macOS 10.15.5
  - Compiler: gcc9

## Description

The implementation for `seqan3::is_in_alphabet` is not correct for gapped alphabets.
I would expect to see the correct results or a compiler error if this case is not implemented.

Hint for a possible solution: There is a function `bool char_is_valid(char_type const chr)` in `alphabet_variant.hpp:578` which is supposed to do the job, but it is actually never called.

### How to repeat the problem

Simply paste the lines below in a snippet like this:

```cpp
using namespace seqan3;
std::cout << std::boolalpha << (is_in_alphabet<gapped<rna5>>('a')) << std::endl;
```

### Expected behaviour

```cpp
is_in_alphabet<gapped<rna5>>('a')    // true
is_in_alphabet<gapped<rna5>>('c')    // true
is_in_alphabet<gapped<rna5>>('g')    // true
is_in_alphabet<gapped<rna5>>('u')    // true
is_in_alphabet<gapped<rna5>>('-')    // true
is_in_alphabet<gapped<rna5>>('n')    // true
is_in_alphabet<gapped<rna5>>('s')    // false
```

### Actual behaviour

```cpp
is_in_alphabet<gapped<rna5>>('a')    // false
is_in_alphabet<gapped<rna5>>('c')    // false
is_in_alphabet<gapped<rna5>>('g')    // false
is_in_alphabet<gapped<rna5>>('u')    // false
is_in_alphabet<gapped<rna5>>('-')    // true
is_in_alphabet<gapped<rna5>>('n')    // false
is_in_alphabet<gapped<rna5>>('s')    // false
```

### PR DESCRIPTION
**Pull request by smehringer**
Fixes #1972 

Note that `char_is_valid` is public in all other alphabets. I double checked.

### CODE REVIEW

File: include/seqan3/alphabet/composite/alphabet_variant.hpp [hunk 1]
```diff
@@ -433,6 +433,20 @@ class alphabet_variant : public alphabet_base<alphabet_variant<alternative_types
     }
     //!\}
 
+    //!\brief Validate whether a character is valid in the by any of the combined alphabet.
```
Comment (joergi-w) [inline include/seqan3/alphabet/composite/alphabet_variant.hpp:436]:
```suggestion
    //!\brief Validate whether a character is valid in the combined alphabet.
```

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 2]
```diff
@@ -13,6 +13,7 @@
 #include <seqan3/alphabet/composite/alphabet_variant.hpp>
 #include <seqan3/alphabet/gap/gap.hpp>
 #include <seqan3/alphabet/nucleotide/all.hpp>
+#include <seqan3/core/char_operations/predicate.hpp>
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:16]: Why do we need this?

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 3]
```diff
@@ -332,3 +333,41 @@ TEST(alphabet_variant_test, two_different_variants)
...
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('N'));
+    EXPECT_FALSE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('S'));
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('a'));
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('c'));
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('g'));
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('u'));
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('t'));
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('-'));
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('n'));
+    EXPECT_FALSE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('s'));
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:353]:
```suggestion
    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('A')); // valid seqan3::rna5 char 
    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('-')); // valid seqan3::gap char 
    
    EXPECT_FALSE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('S')); // neither seqan3::rna5 nor seqan3::gap
```

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 4]
```diff
@@ -332,3 +333,41 @@ TEST(alphabet_variant_test, two_different_variants)
...
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('N'));
+    EXPECT_FALSE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('S'));
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('a'));
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('c'));
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('g'));
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('u'));
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('t'));
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('-'));
+    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('n'));
+    EXPECT_FALSE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('s'));
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:372]:
```suggestion
    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('A')); // valid seqan3::rna5 char
    EXPECT_TRUE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('-')); // valid seqan3::gap char
 
    EXPECT_FALSE(seqan3::is_in_alphabet<seqan3::gapped<seqan3::rna5>>('S')); // neither seqan3::rna5 nor seqan3::gap
```

Comment (joergi-w) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:372]: We should have also lowercase characters in the test, because it seems to make a difference, as stated [here](https://github.com/seqan/seqan3/issues/1972#issuecomment-655297777).

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 2 above)
Comment (smehringer) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:16]: Because `seqan3::is_in_alphabet` is defined in this header

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 4 above)
Comment (smehringer) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp]: I replaced them with a for loop over every possible char

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 5]
```diff
@@ -336,38 +336,28 @@ TEST(alphabet_variant_test, two_different_variants)
...
-    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('t'));
-    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('-'));
-    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('n'));
-    EXPECT_FALSE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('s'));
+    using char_t = seqan3::alphabet_char_t<seqan3::gapped<seqan3::rna5>>;
+
+    char_t i = std::numeric_limits<char_t>::min();
+    char_t j = std::numeric_limits<char_t>::max();
+
+    for (; i < j; ++i)
```
Comment (joergi-w) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:344]: Nice idea! 
One remark: With `i < j` the value of `max()` is excluded from the loop.

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 6]
```diff
@@ -332,3 +333,31 @@ TEST(alphabet_variant_test, two_different_variants)
...
+    {
+        EXPECT_EQ(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>(i),
+                  seqan3::char_is_valid_for<seqan3::gap>(i) || seqan3::char_is_valid_for<seqan3::rna5>(i));
+    }
+}
+
+TEST(alphabet_variant_test, is_in_alphabet)
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:351]: Move me into `char_predicate_test`.

Also have a second test that tests the specific equivalent classes.

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 7]
```diff
@@ -332,3 +333,31 @@ TEST(alphabet_variant_test, two_different_variants)
     seqan3::alphabet_variant<seqan3::rna4, seqan3::gap> r2{'A'_rna4};
     EXPECT_EQ(l, r2); // this works because rna4 and dna4 are implicitly convertible to each other
 }
+
+TEST(alphabet_variant_test, char_is_valid_for)
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:337]: Can you re-add the specific tests of the equivalent classes? I would always prefer if we have a generic implementation and one that validates that for specific values. Thank you :)

```c++
    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('A')); // valid seqan3::rna5 char 
    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('-')); // valid seqan3::gap char 
    EXPECT_FALSE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('S')); // neither seqan3::rna5 nor seqan3::gap
```

Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:337]: It would be really awesome if we could use TYPED_TEST here, we would only need to somehow extract all bases.

EDIT://

Oh, we have that `::seqan3_required_types`, which is a `type_list<alphabets...>`

Maybe we should make this a public property :thinking:

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 2 above)
Comment (smehringer) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:16]: I disagree :( Because this issue was not because `seqan3::is_in_alphabet` in predicate was wrong but because the alphabet_variant implementation had a flaw. So this is an issue of the alphabet_variant and should therefore be in its test.
Since `seqan3::is_in_alphabet` is only using `seqan3::char_is_valid_for` the test for the latter would suffice and we could remove the dependency on `predicate.hpp`. But we should nor make the predicate test depends on `alphabet_variant.hpp`, `dna4.hpp` and `gapped.hpp`.

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 7 above)
Comment (smehringer) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:337]: this can be part of another PR?

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 5 above)
Comment (smehringer) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:344]: The char_type is fixed here and its not 32 or 64 bits so I thought it's fine without the max iterations.

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 6 above)
Comment (smehringer) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:357]: > Move me into char_predicate_test.

See https://github.com/seqan/seqan3/pull/1973#discussion_r452115051

> Also have a second test that tests the specific equivalent classes.

What do you mean by that?

Comment (marehr) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:357]: This is a regression test for `seqan3::is_in_alphabet` and that lives in `test/unit/core/char_operations/char_predicate_test.cpp`

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 8]
```diff
@@ -332,3 +333,43 @@ TEST(alphabet_variant_test, two_different_variants)
...
+
+    char_t i = std::numeric_limits<char_t>::min();
+    char_t end = std::numeric_limits<char_t>::max();
+
+    // note that without the cast i <= end would result in an ininite loop
+    for (; static_cast<int64>(i) <= static_cast<int64>(end); ++i)
+    {
+        EXPECT_EQ(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>(i),
+                  seqan3::char_is_valid_for<seqan3::gap>(i) || seqan3::char_is_valid_for<seqan3::rna5>(i));
+    }
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:354]:
```suggestion
    using gapped_alphabet_t = TypeParam;
    using gapped_alphabet_bases_t = typename gapped_alphabet_t::seqan3_required_types;
    using char_t = seqan3::alphabet_char_t<gapped_alphabet_t>;

    char_t i = std::numeric_limits<char_t>::min();
    char_t end = std::numeric_limits<char_t>::max();

    // note that without the cast i <= end would result in an ininite loop
    for (; static_cast<int64>(i) <= static_cast<int64>(end); ++i)
    {
        // is thar char valid for any of the bases?
        bool is_valid{};
        seqan3::detail::for_each<gapped_alphabet_bases_t>([&is_valid, i](auto id)
        {
             using type = typename decltype(id)::type;
             is_valid = is_valid || seqan3::char_is_valid_for<type>(i);
        });

        EXPECT_EQ(seqan3::char_is_valid_for<gapped_alphabet_t>(i), is_valid);
    }
```

Shouldn't this work? And we can make the test case a typed test?

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 2 above)
Comment (marehr) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:16]: * What is that regression about? Oh, yeah about  `seqan3::is_in_alphabet` which belongs to the "test/unit/core/char_operations/char_predicate_test.cpp"
* Which test already includes *all* alphabets?
   hint:
   https://github.com/seqan/seqan3/blob/d06f9acae65e01375109f43f0bfa5202520a534f/test/unit/core/char_operations/char_predicate_test.cpp#L11-L14

The regression should be added where the regression belongs to.
Imagine someone who uses `seqan3::is_in_alphabet`, where will he look for tests? Sure, he will look in the `gapped` test, because it is obvious.

Please change this. Thank you!

File: test/unit/alphabet/composite/alphabet_variant_test.cpp (hunk 8 above)
Comment (smehringer) [reply test/unit/alphabet/composite/alphabet_variant_test.cpp:354]: I'll remind you of this conversation when I request a change and you insist that it is not the scope of the current PR

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 9]
```diff
@@ -332,3 +333,38 @@ TEST(alphabet_variant_test, two_different_variants)
     seqan3::alphabet_variant<seqan3::rna4, seqan3::gap> r2{'A'_rna4};
     EXPECT_EQ(l, r2); // this works because rna4 and dna4 are implicitly convertible to each other
 }
+
+TEST(alphabet_variant_test, char_is_valid_for)
+{ // see issue https://github.com/seqan/seqan3/issues/1972
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('A')); // valid seqan3::rna5 char
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:339]:
```suggestion
TEST(alphabet_variant_test, char_is_valid_for)
{
    // see issue https://github.com/seqan/seqan3/issues/1972
    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('A')); // valid seqan3::rna5 char
```

File: test/unit/alphabet/composite/alphabet_variant_test.cpp [hunk 10]
```diff
@@ -332,3 +333,38 @@ TEST(alphabet_variant_test, two_different_variants)
...
+    EXPECT_TRUE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('-')); // valid seqan3::gap char
+    EXPECT_FALSE(seqan3::char_is_valid_for<seqan3::gapped<seqan3::rna5>>('S')); // neither seqan3::rna5 nor seqan3::gap
+}
+
+template <typename T>
+using alphabet_variant_typed_test = ::testing::Test;
+
+TYPED_TEST_SUITE(alphabet_variant_typed_test, alphabet_variant_types, );
+
+TYPED_TEST(alphabet_variant_typed_test, char_is_valid_for)
```
Comment (marehr) [inline test/unit/alphabet/composite/alphabet_variant_test.cpp:350]:
```suggestion
TYPED_TEST(alphabet_variant_test, char_is_valid_for)
```

File: test/unit/core/char_operations/char_predicate_test.cpp [hunk 11]
```diff
@@ -439,3 +440,42 @@ TEST(char_predicate_, char_types)
         EXPECT_FALSE(seqan3::is_in_alphabet<seqan3::dna5>(char16_t{256}));
     }
 }
+
+TEST(char_predicate_, is_in_alphabet_alphabet_variant)
+{ // see issue https://github.com/seqan/seqan3/issues/1972
```
Comment (marehr) [inline test/unit/core/char_operations/char_predicate_test.cpp:445]:
```suggestion

// see issue https://github.com/seqan/seqan3/issues/1972
TEST(char_predicate_, issue1972)
{
```

File: test/unit/core/char_operations/char_predicate_test.cpp [hunk 12]
```diff
@@ -439,3 +440,42 @@ TEST(char_predicate_, char_types)
...
+    {
+        bool is_valid{};
+        seqan3::detail::for_each<gapped_alphabet_bases_t>([&is_valid, i](auto id)
+        {
+             using type = typename decltype(id)::type;
+             is_valid = is_valid || seqan3::is_in_alphabet<type>(i);
+        });
+        EXPECT_EQ(seqan3::is_in_alphabet<gapped_alphabet_t>(i), is_valid);
+    }
+}
```
Comment (marehr) [inline test/unit/core/char_operations/char_predicate_test.cpp:481]:
```suggestion
```
