### PR TITLE
Fixes #1598: pairwise alignment does not work for some ranges

### LINKED ISSUE #1598: Pairwise Alignment with ranges and `with_alignment` doesn't compile
## Platform
  - SeqAn version: 87317771
  - Operating system: `Linux schenker 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux`
  - Compiler: `gcc (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130`

## Description

I followed the pairwise alignment tutorial http://docs.seqan.de/seqan/3-master-user/tutorial_pairwise_alignment.html but instead of `std::vector<dna4>` I use ranges. The code doesn't compile when I set `seqan3::align_cfg::result{seqan3::with_alignment}`.

### How to repeat the problem
The Code below reproduces the error.
If you remove `seqan3::align_cfg::result{seqan3::with_alignment}` it compiles.
If instead of a range I just use a `std::vector<dna4>` for s2 it also compiles.

```
#include <seqan3/alignment/pairwise/align_pairwise.hpp>
#include <seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp>
#include <seqan3/alphabet/nucleotide/dna4.hpp>

int main() {
    using seqan3::operator""_dna4;
    auto s1 = "TTACGTACGGACTAGCTACAACATTACGGACTAC"_dna4;
    auto g  = "GGACGACATGACGTACGACTTTACGTACGACTAGC"_dna4;
    auto s2 = g | std::views::drop(2);

    // Configure the alignment kernel.
    auto config = seqan3::align_cfg::mode{seqan3::global_alignment} |
                   seqan3::align_cfg::scoring{seqan3::nucleotide_scoring_scheme{}} |
                   seqan3::align_cfg::result{seqan3::with_alignment};

     // Invoke the pairwise alignment which returns a lazy range over alignment results.
     auto results = seqan3::align_pairwise(std::tie(s1, s2), config);
}
```


### Expected behaviour
I expect align_pairwise to work with ranges in all configurations.

### Actual behaviour
I fails with a compile error:
```
IIn file included from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_result_selector.hpp:32,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:24,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:26,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:24,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/home/gene/Coding/seqan3/include/seqan3/range/decorator/gap_decorator.hpp: In instantiation of ‘void seqan3::assign_unaligned(seqan3::gap_decorator<inner_type>&, unaligned_seq_t&&) [with unaligned_seq_t = std::span<seqan3::dna4, -1>; inner_type = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>]’:
/home/gene/Coding/seqan3/include/seqan3/alignment/matrix/alignment_trace_algorithms.hpp:125:21:   required from ‘alignment_t seqan3::detail::alignment_trace(database_t&&, query_t&&, trace_matrix_t&&, seqan3::alignment_coordinate, seqan3::alignment_coordinate) [with alignment_t = std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >; database_t = std::vector<seqan3::dna4>&; query_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>&; trace_matrix_t = const seqan3::detail::edit_distance_trace_matrix_full<long unsigned int, false, false>&]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp:1070:64:   required from ‘seqan3::alignment_result<typename edit_traits::result_value_type> seqan3::detail::edit_distance_unbanded<database_t, query_t, align_config_t, traits_t>::operator()(size_t) [with database_t = std::vector<seqan3::dna4>&; query_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>&; align_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; edit_traits = seqan3::detail::default_edit_distance_trait_type<std::vector<seqan3::dna4>&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>&, seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, std::integral_constant<bool, false>, long unsigned int>; typename edit_traits::result_value_type = seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*>; size_t = long unsigned int]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/edit_distance_algorithm.hpp:115:20:   required from ‘constexpr auto seqan3::detail::edit_distance_algorithm<config_t, traits_t>::compute_single_pair(size_t, first_range_t&&, second_range_t&&) [with first_range_t = std::vector<seqan3::dna4>&; second_range_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>&; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; traits_t = seqan3::detail::alignment_configurator::configure_edit_distance(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:64)> [with auto:64 = std::integral_constant<bool, false>]::edit_traits_type; size_t = long unsigned int]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/edit_distance_algorithm.hpp:92:13:   required from ‘constexpr auto seqan3::detail::edit_distance_algorithm<config_t, traits_t>::operator()(indexed_sequence_pairs_t&&) [with indexed_sequence_pairs_t = ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; traits_t = seqan3::detail::alignment_configurator::configure_edit_distance(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:64)> [with auto:64 = std::integral_constant<bool, false>]::edit_traits_type]’
/usr/include/c++/9.2.1/type_traits:2336:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = seqan3::detail::edit_distance_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::alignment_configurator::configure_edit_distance(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:64)> [with auto:64 = std::integral_constant<bool, false>]::edit_traits_type>&; _Args = {ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >}]’
/usr/include/c++/9.2.1/type_traits:2347:55:   [ skipping 6 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:362:59:   required from ‘seqan3::detail::alignment_configurator::configure_edit_distance(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:64)> [with auto:64 = std::integral_constant<bool, false>]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:370:45:   required from ‘seqan3::detail::alignment_configurator::configure_edit_distance(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:65)> [with auto:65 = std::integral_constant<bool, false>]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:393:42:   required from ‘static constexpr function_wrapper_t seqan3::detail::alignment_configurator::configure_edit_distance(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:310:89:   required from ‘static constexpr auto seqan3::detail::alignment_configurator::configure(const config_t&) [with sequences_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:169:104:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:148:26:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&>; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/testOSS2/testOSS.cpp:18:68:   required from here
/home/gene/Coding/seqan3/include/seqan3/range/decorator/gap_decorator.hpp:297:13: error: no match for ‘operator=’ (operand types are ‘seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >’ and ‘std::span<seqan3::dna4, -1>’)
  297 |         dec = unaligned;
      |         ~~~~^~~~~~~~~~~
In file included from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_result_selector.hpp:32,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:24,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:26,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:24,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/home/gene/Coding/seqan3/include/seqan3/range/decorator/gap_decorator.hpp:84:7: note: candidate: ‘seqan3::gap_decorator<inner_type>& seqan3::gap_decorator<inner_type>::operator=(const seqan3::gap_decorator<inner_type>&) [with inner_type = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>]’
   84 | class gap_decorator
      |       ^~~~~~~~~~~~~
/home/gene/Coding/seqan3/include/seqan3/range/decorator/gap_decorator.hpp:125:41: note:   no known conversion for argument 1 from ‘std::span<seqan3::dna4, -1>’ to ‘const seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >&’
  125 |     constexpr gap_decorator & operator=(gap_decorator const &) = default;
      |                                         ^~~~~~~~~~~~~~~~~~~~~
/home/gene/Coding/seqan3/include/seqan3/range/decorator/gap_decorator.hpp:84:7: note: candidate: ‘seqan3::gap_decorator<inner_type>& seqan3::gap_decorator<inner_type>::operator=(seqan3::gap_decorator<inner_type>&&) [with inner_type = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>]’
   84 | class gap_decorator
      |       ^~~~~~~~~~~~~
/home/gene/Coding/seqan3/include/seqan3/range/decorator/gap_decorator.hpp:129:58: note:   no known conversion for argument 1 from ‘std::span<seqan3::dna4, -1>’ to ‘seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >&&’
  129 |     constexpr gap_decorator & operator=(gap_decorator && rhs) = default;
      |                                         ~~~~~~~~~~~~~~~~~^~~
In file included from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:26,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:24,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp: In instantiation of ‘constexpr auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::make_alignment_result(index_t, sequence1_t&, sequence2_t&) [with index_t = long unsigned int; sequence1_t = std::vector<seqan3::dna4>; sequence2_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}]’:
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:302:67:   required from ‘constexpr auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::compute_single_pair(size_t, sequence1_t&&, sequence2_t&&) [with sequence1_t = std::vector<seqan3::dna4>&; sequence2_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>&; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}; size_t = long unsigned int]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:191:13:   required from ‘auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::operator()(indexed_sequence_pairs_t&&) [with indexed_sequence_pairs_t = ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}]’
/usr/include/c++/9.2.1/type_traits:2336:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type> >&; _Args = {ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >}]’
/usr/include/c++/9.2.1/type_traits:2347:55:   required from ‘struct std::__result_of_impl<false, false, seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type> >&, ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> > >’
/usr/include/c++/9.2.1/type_traits:2352:12:   required from ‘struct std::__invoke_result<seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type> >&, ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> > >’
/usr/include/c++/9.2.1/bits/std_function.h:375:9:   [ skipping 9 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:543:46:   required from ‘seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:68)> [with auto:68 = std::integral_constant<bool, false>]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:560:44:   required from ‘static constexpr function_wrapper_t seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:500:91:   required from ‘static constexpr function_wrapper_t seqan3::detail::alignment_configurator::configure_scoring_scheme(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:324:74:   required from ‘static constexpr auto seqan3::detail::alignment_configurator::configure(const config_t&) [with sequences_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:169:104:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:148:26:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&>; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/testOSS2/testOSS.cpp:18:68:   required from here
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:632:31: error: no match for ‘operator=’ (operand types are ‘std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >’ and ‘std::remove_reference<std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >&>::type’ {aka ‘std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >’})
  632 |                 res.alignment = std::move(trace_res.alignment);
      |                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9.2.1/functional:54,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:15,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/usr/include/c++/9.2.1/tuple:1205:7: note: candidate: ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(typename std::conditional<__assignable<const _T1&, const _T2&>(), const std::tuple<_T1, _T2>&, const std::__nonesuch_no_braces&>::type) [with _T1 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >; _T2 = seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >; typename std::conditional<__assignable<const _T1&, const _T2&>(), const std::tuple<_T1, _T2>&, const std::__nonesuch_no_braces&>::type = const std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&]’
 1205 |       operator=(typename conditional<__assignable<const _T1&, const _T2&>(),
      |       ^~~~~~~~
/usr/include/c++/9.2.1/tuple:1207:45: note:   no known conversion for argument 1 from ‘std::remove_reference<std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >&>::type’ {aka ‘std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >’} to ‘std::conditional<true, const std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&, const std::__nonesuch_no_braces&>::type’ {aka ‘const std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&’}
 1205 |       operator=(typename conditional<__assignable<const _T1&, const _T2&>(),
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1206 |          const tuple&,
      |          ~~~~~~~~~~~~~                       
 1207 |          const __nonesuch_no_braces&>::type __in)
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/usr/include/c++/9.2.1/tuple:1215:7: note: candidate: ‘std::tuple<_T1, _T2>& std::tuple<_T1, _T2>::operator=(typename std::conditional<__assignable<_T1, _T2>(), std::tuple<_T1, _T2>&&, std::__nonesuch_no_braces&&>::type) [with _T1 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >; _T2 = seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >; typename std::conditional<__assignable<_T1, _T2>(), std::tuple<_T1, _T2>&&, std::__nonesuch_no_braces&&>::type = std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&&]’
 1215 |       operator=(typename conditional<__assignable<_T1, _T2>(),
      |       ^~~~~~~~
/usr/include/c++/9.2.1/tuple:1217:40: note:   no known conversion for argument 1 from ‘std::remove_reference<std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >&>::type’ {aka ‘std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >’} to ‘std::conditional<true, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&&, std::__nonesuch_no_braces&&>::type’ {aka ‘std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&&’}
 1215 |       operator=(typename conditional<__assignable<_T1, _T2>(),
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1216 |          tuple&&,
      |          ~~~~~~~~                       
 1217 |          __nonesuch_no_braces&&>::type __in)
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/usr/include/c++/9.2.1/tuple:1226:2: note: candidate: ‘template<class _U1, class _U2> std::__enable_if_t<__assignable<const _U1&, const _U2&>(), std::tuple<_T1, _T2>&> std::tuple<_T1, _T2>::operator=(const std::tuple<_U1, _U2>&) [with _U1 = _U1; _U2 = _U2; _T1 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >; _T2 = seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >]’
 1226 |  operator=(const tuple<_U1, _U2>& __in)
      |  ^~~~~~~~
/usr/include/c++/9.2.1/tuple:1226:2: note:   template argument deduction/substitution failed:
In file included from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:26,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:24,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:632:31: note:   ‘std::remove_reference<std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >&>::type’ {aka ‘std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >’} is not derived from ‘const std::tuple<_T1, _T2>’
  632 |                 res.alignment = std::move(trace_res.alignment);
      |                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9.2.1/functional:54,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:15,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/usr/include/c++/9.2.1/tuple:1235:2: note: candidate: ‘template<class _U1, class _U2> std::__enable_if_t<__assignable<_U1, _U2>(), std::tuple<_T1, _T2>&> std::tuple<_T1, _T2>::operator=(std::tuple<_U1, _U2>&&) [with _U1 = _U1; _U2 = _U2; _T1 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >; _T2 = seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >]’
 1235 |  operator=(tuple<_U1, _U2>&& __in)
      |  ^~~~~~~~
/usr/include/c++/9.2.1/tuple:1235:2: note:   template argument deduction/substitution failed:
In file included from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:26,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:24,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:632:31: note:   ‘std::remove_reference<std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >&>::type’ {aka ‘std::pair<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<std::span<seqan3::dna4, -1> > >’} is not derived from ‘std::tuple<_T1, _T2>’
  632 |                 res.alignment = std::move(trace_res.alignment);
      |                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9.2.1/functional:54,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:15,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/usr/include/c++/9.2.1/tuple:1244:2: note: candidate: ‘template<class _U1, class _U2> std::__enable_if_t<__assignable<const _U1&, const _U2&>(), std::tuple<_T1, _T2>&> std::tuple<_T1, _T2>::operator=(const std::pair<_U1, _U2>&) [with _U1 = _U1; _U2 = _U2; _T1 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >; _T2 = seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >]’
 1244 |  operator=(const pair<_U1, _U2>& __in)
      |  ^~~~~~~~
/usr/include/c++/9.2.1/tuple:1244:2: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/9.2.1/bits/move.h:55,
                 from /usr/include/c++/9.2.1/bits/stl_function.h:60,
                 from /usr/include/c++/9.2.1/functional:49,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:15,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/usr/include/c++/9.2.1/type_traits: In substitution of ‘template<bool _Cond, class _Tp> using __enable_if_t = typename std::enable_if::type [with bool _Cond = std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >::__assignable<const seqan3::gap_decorator<std::span<seqan3::dna4, -1> >&, const seqan3::gap_decorator<std::span<seqan3::dna4, -1> >&>(); _Tp = std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&]’:
/usr/include/c++/9.2.1/tuple:1244:2:   required by substitution of ‘template<class _U1, class _U2> std::__enable_if_t<__assignable<const _U1&, const _U2&>(), std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&> std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >::operator=<_U1, _U2>(const std::pair<_T1, _T2>&) [with _U1 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >; _U2 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:632:31:   required from ‘constexpr auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::make_alignment_result(index_t, sequence1_t&, sequence2_t&) [with index_t = long unsigned int; sequence1_t = std::vector<seqan3::dna4>; sequence2_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:302:67:   required from ‘constexpr auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::compute_single_pair(size_t, sequence1_t&&, sequence2_t&&) [with sequence1_t = std::vector<seqan3::dna4>&; sequence2_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>&; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}; size_t = long unsigned int]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:191:13:   required from ‘auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::operator()(indexed_sequence_pairs_t&&) [with indexed_sequence_pairs_t = ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}]’
/usr/include/c++/9.2.1/type_traits:2336:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type> >&; _Args = {ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >}]’
/usr/include/c++/9.2.1/type_traits:2347:55:   [ skipping 11 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:543:46:   required from ‘seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:68)> [with auto:68 = std::integral_constant<bool, false>]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:560:44:   required from ‘static constexpr function_wrapper_t seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:500:91:   required from ‘static constexpr function_wrapper_t seqan3::detail::alignment_configurator::configure_scoring_scheme(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:324:74:   required from ‘static constexpr auto seqan3::detail::alignment_configurator::configure(const config_t&) [with sequences_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:169:104:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:148:26:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&>; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/testOSS2/testOSS.cpp:18:68:   required from here
/usr/include/c++/9.2.1/type_traits:2405:11: error: no type named ‘type’ in ‘struct std::enable_if<false, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >&>’
 2405 |     using __enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~~~
In file included from /usr/include/c++/9.2.1/functional:54,
                 from /home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:15,
                 from /home/gene/Coding/testOSS2/testOSS.cpp:2:
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp: In instantiation of ‘constexpr auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::make_alignment_result(index_t, sequence1_t&, sequence2_t&) [with index_t = long unsigned int; sequence1_t = std::vector<seqan3::dna4>; sequence2_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}]’:
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:302:67:   required from ‘constexpr auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::compute_single_pair(size_t, sequence1_t&&, sequence2_t&&) [with sequence1_t = std::vector<seqan3::dna4>&; sequence2_t = ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized>&; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}; size_t = long unsigned int]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_algorithm.hpp:191:13:   required from ‘auto seqan3::detail::alignment_algorithm<config_t, algorithm_policies_t>::operator()(indexed_sequence_pairs_t&&) [with indexed_sequence_pairs_t = ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >; algorithm_policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type>}]’
/usr/include/c++/9.2.1/type_traits:2336:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type> >&; _Args = {ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >}]’
/usr/include/c++/9.2.1/type_traits:2347:55:   required from ‘struct std::__result_of_impl<false, false, seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type> >&, ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> > >’
/usr/include/c++/9.2.1/type_traits:2352:12:   required from ‘struct std::__invoke_result<seqan3::detail::alignment_algorithm<seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >, seqan3::detail::deferred_crtp_base<seqan3::detail::alignment_matrix_policy, seqan3::detail::alignment_score_matrix_one_column<int>, seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_policy, int, std::integral_constant<bool, false> >, seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>, seqan3::detail::deferred_crtp_base<seqan3::detail::find_optimum_policy, seqan3::detail::alignment_configurator::configure_free_ends_optimum_search(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::deferred_crtp_base<seqan3::detail::affine_gap_init_policy, seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:66, auto:67)> [with auto:66 = std::integral_constant<bool, false>; auto:67 = std::integral_constant<bool, false>]::policy_trait_type>}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:69, auto:70)> [with auto:69 = std::integral_constant<bool, false>; auto:70 = std::integral_constant<bool, false>]::policy_trait_type> >&, ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> > >’
/usr/include/c++/9.2.1/bits/std_function.h:375:9:   [ skipping 9 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:543:46:   required from ‘seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]::<lambda(auto:68)> [with auto:68 = std::integral_constant<bool, false>]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:560:44:   required from ‘static constexpr function_wrapper_t seqan3::detail::alignment_configurator::configure_free_ends_initialisation(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; policies_t = {seqan3::detail::deferred_crtp_base<seqan3::detail::scoring_scheme_policy, seqan3::nucleotide_scoring_scheme<signed char> >}; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:500:91:   required from ‘static constexpr function_wrapper_t seqan3::detail::alignment_configurator::configure_scoring_scheme(const config_t&) [with function_wrapper_t = std::function<std::vector<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> >, std::allocator<seqan3::alignment_result<seqan3::detail::alignment_result_value_type<unsigned int, int, seqan3::alignment_coordinate, seqan3::alignment_coordinate, std::tuple<seqan3::gap_decorator<std::span<seqan3::dna4, -1> >, seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized> > >, std::nullopt_t*, std::nullopt_t*> > > >(ranges::take_view<ranges::subrange<ranges::basic_iterator<ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::cursor<false> >, ranges::iter_zip_with_view<ranges::detail::indirect_zip_fn_, ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >, ranges::iota_view<int, ranges::unreachable_sentinel_t> >::sentinel<false>, ranges::subrange_kind::unsized> >)>; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/alignment_configurator.hpp:324:74:   required from ‘static constexpr auto seqan3::detail::alignment_configurator::configure(const config_t&) [with sequences_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:169:104:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = ranges::single_view<std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&> >; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/seqan3/include/seqan3/alignment/pairwise/align_pairwise.hpp:148:26:   required from ‘constexpr auto seqan3::align_pairwise(sequence_t&&, const alignment_config_t&) [with sequence_t = std::tuple<std::vector<seqan3::dna4, std::allocator<seqan3::dna4> >&, ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4, std::allocator<seqan3::dna4> > >, ranges::subrange_kind::sized>&>; alignment_config_t = seqan3::configuration<seqan3::align_cfg::mode<seqan3::detail::global_alignment_type>, seqan3::align_cfg::scoring<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::align_cfg::result<seqan3::detail::with_alignment_type, int> >]’
/home/gene/Coding/testOSS2/testOSS.cpp:18:68:   required from here
/usr/include/c++/9.2.1/tuple:1254:2: note: candidate: ‘template<class _U1, class _U2> std::__enable_if_t<__assignable<_U1, _U2>(), std::tuple<_T1, _T2>&> std::tuple<_T1, _T2>::operator=(std::pair<_U1, _U2>&&) [with _U1 = _U1; _U2 = _U2; _T1 = seqan3::gap_decorator<std::span<seqan3::dna4, -1> >; _T2 = seqan3::gap_decorator<ranges::subrange<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, ranges::subrange_kind::sized> >]’
 1254 |  operator=(pair<_U1, _U2>&& __in)
      |  ^~~~~~~~
/usr/include/c++/9.2.1/tuple:1254:2: note:   template argument deduction/substitution failed:
make[2]: *** [CMakeFiles/testOSS.dir/build.make:63: CMakeFiles/testOSS.dir/testOSS.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/testOSS.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

### PR DESCRIPTION
**Pull request by marehr**
Fixes #1598: pairwise alignment does not work for some ranges

### CODE REVIEW

File: include/seqan3/alignment/pairwise/align_result_selector.hpp [hunk 1]
```diff
@@ -95,21 +74,15 @@ struct align_result_selector
...
-            // Due to an error with gcc8 we define these types beforehand.
-            using first_gapped_seq_type = gapped<value_type_t<first_range_t>>;
-            using second_gapped_seq_type = gapped<value_type_t<second_range_t>>;
-
-            // We use vectors of gapped sequence if the gap decorator cannot be used.
-            using fallback_t = std::tuple<std::vector<first_gapped_seq_type>, std::vector<second_gapped_seq_type>>;
-
-            // If the ranges are RandomAccess and Sized we can use the Gap Decorator, otherwise fallback_t.
-            using decorator_t = alignment_type<first_range_t, second_range_t>;
+            // TODO: type `(first|second)_range_t &` is a hack to make the sequences viewable_ranges
```
Comment (eseiler) [inline include/seqan3/alignment/pairwise/align_result_selector.hpp]: if 
https://github.com/seqan/seqan3/blob/034810f0c16069321670f84be6ca9cb52a8f88a7/include/seqan3/alignment/pairwise/alignment_algorithm.hpp#L182

was `range_reference_type`, you could require `viewable_range_ here?

Can this somehow backfire because you'll later use this type to create a reference to something that is, e.g., temporary?

Comment (marehr) [reply include/seqan3/alignment/pairwise/align_result_selector.hpp]: This might be the way to solve this, we use `value_type` on multiple occurrences in the alignment code, so we might want to fix this on multiple occasions, but maybe in another PR.

Comment (smehringer) [reply include/seqan3/alignment/pairwise/align_result_selector.hpp]: but then the above maybe shouldn't be part of this PR at all? It feels like we introduce a fragile workaround while we know there is more to fix.

File: include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp [hunk 2]
```diff
@@ -57,12 +57,37 @@ struct make_aligned_sequence_type
     // seqan3::gap_decorator. Ranges that do not model std::random_access_range for instance cannot be augmented with
     // the gap_decorator and need to be copied instead.
 
+    //!\brief The unaligned sequence type that will be used to assign a sequence to seqan3::assign_unaligned.
+    using unaligned_sequence_type = decltype(std::declval<range_t>() | views::type_reduce | views::slice(0, 1));
```
Comment (rrahn) [inline include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp]: do you really want expose this type? Is that somewhere used?

File: include/seqan3/alignment/pairwise/align_result_selector.hpp [hunk 3]
```diff
@@ -35,31 +36,9 @@
...
-             std::ranges::sized_range<second_t>
-struct alignment_type<first_t, second_t>
-{
-    //!\brief The alignment type with gap decorator.
-    using type = std::tuple<gap_decorator<type_reduce_view<first_t &>>, gap_decorator<type_reduce_view<second_t &>>>;
-};
-
 /*!\brief Helper metafunction to select the alignment result type based on the configuration.
  * \ingroup pairwise_alignment
- * \tparam first_bach_t    The type of the first sequence.
```
Comment (rrahn) [inline include/seqan3/alignment/pairwise/align_result_selector.hpp]: what's wrong with great classical composer as a name for a variable? 🤣

File: include/seqan3/alignment/pairwise/align_result_selector.hpp (hunk 1 above)
Comment (rrahn) [reply include/seqan3/alignment/pairwise/align_result_selector.hpp]: I think here are two issues. The first one is that the call of this metafunction happens on multiple places possibly making it possible to use wrong types in either place and causing some hard to track compiler errors.
https://github.com/seqan/seqan3/blob/034810f0c16069321670f84be6ca9cb52a8f88a7/include/seqan3/alignment/pairwise/alignment_configurator.hpp#L258

So the first ting we need to do is to use the result type that is defined in the configurator and pass it to the alignment algorithm object, so we avoid redefinition of the same type with possibly wrong types.

Second, the input sequence is either transformed right at the beginning of align_pairwise to always return a pair of views, e.g. like `input_range | transform([](auto && pair) { return pair{tpl.first | type_erase, pair.second | type_erase } } )` and use this throughout the alignment implementation. In this case we assume everything is a view and we don't have to worry anymore about the correct references of the types. 
Not sure if this has any runtime implications. 
Or we get the types correctly in the first place like this:
```cpp
// assuming std::ranges::viewable_range<input_range_t> is true
using std::get;
using ref_t = std::ranges::range_reference_t<input_range_t>;
using seq1_t = decltype(get<0>(std::declval<ref_t &&>()));
using seq2_t = decltype(get<1>(std::declval<ref_t &&>()));
```
Here the reference type should be correctly encoded in the `seqi_t` types and can be used inside of the meta functions.

**Comment by marehr** [comment]
@rrahn Can we go over this again tomorrow?

File: include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp (hunk 2 above)
Comment (marehr) [reply include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp]: Not sure why a struct in `seqan3::detail` needs this, but I've made that change.

**Comment by smehringer** [comment]
How did you dismiss the review?

File: include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp (hunk 2 above)
Comment (rrahn) [reply include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp]: It has nothing todo whether or not it is in detail. It is the question of whether or not the intermidate type should be exposed for usage also for the developer.

**Comment by rrahn** [comment]
> How did you dismiss the review?

I think as the owner of the PR you can dismiss a review.

**Comment by rrahn** [comment]
but since you know commented your state changed from approved to comment. I'll merge using my super powers 💪
