### PR TITLE
[FIX] iterator_tag does not handle legacy / c++ iterators correctly

### LINKED ISSUE #1963: [BUG] In g++-10 seqan3::views::complement | seqan3::views::kmer_hash forward_range property is not preserved
### Description 
Using `seqan3::views::complement | seqan3::views::kmer_hash` loses the forward_range property, it should preserve it though and with g++-version below 10 it does.

### How to repeat the problem

Compile with g++-10:
```c++
seqan3::dna5_vector text{"ACGTA"_dna5};
static_assert(std::ranges::forward_range<decltype(text | seqan3::views::complement | seqan3::views::kmer_hash(seqan3::ungapped{2}))>); // leads to a static assertion, which is not what we would expect
```

### PR DESCRIPTION
**Pull request by marehr**
This fixes #1963 and supersedes #1965.

### CODE REVIEW

File: include/seqan3/core/type_traits/iterator.hpp [hunk 1]
```diff
@@ -148,89 +148,88 @@ struct size_type<it_t>
...
+/*!\brief Exposes the
+ * [iterator_concept](https://en.cppreference.com/w/cpp/iterator/iterator_tags) from the modelled concept.
+ * \implements seqan3::transformation_trait
  * \tparam it_t The type to operate on.
- * \see seqan3::iterator_tag
  */
 template <typename it_t>
 //!\cond
-    requires requires { typename iterator_tag<it_t>::type; }
+   requires std::input_or_output_iterator<it_t>
```
Comment (marehr) [inline include/seqan3/core/type_traits/iterator.hpp:212]:
```suggestion
    requires std::input_or_output_iterator<it_t>
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 2]
```diff
@@ -0,0 +1,307 @@
...
+// -----------------------------------------------------------------------------------------------------
+
+#include <gtest/gtest.h>
+
+#include <seqan3/std/concepts>
+#include <seqan3/std/iterator>
+#include <seqan3/std/ranges>
+#include <list>
+#include <forward_list>
+#include <vector>
```
Comment (eseiler) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:15]:
```suggestion
#include <seqan3/std/concepts>
#include <forward_list>
#include <seqan3/std/iterator>
#include <list>
#include <seqan3/std/ranges>
#include <vector>
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 3]
```diff
@@ -0,0 +1,307 @@
...
+
+#include <seqan3/core/type_traits/iterator.hpp>
+
+#include <seqan3/alphabet/nucleotide/dna5.hpp>
+#include <seqan3/range/views/complement.hpp>
```
Comment (eseiler) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:20]:
```suggestion
#include <seqan3/alphabet/nucleotide/dna5.hpp>
#include <seqan3/core/type_traits/iterator.hpp>
#include <seqan3/range/views/complement.hpp>
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 4]
```diff
@@ -0,0 +1,307 @@
...
+struct inherit_iterator_tag : public base_t
+{
+    using iterator_concept = seqan3::detail::iterator_concept_tag_t<base_t>;
+};
+
+template <typename base_t>
+    requires requires()
+    {
+        typename seqan3::detail::iterator_category_tag_t<base_t>;
+    }
```
Comment (eseiler) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:47]: If you move the concept definition up, you can use the concept here.

File: include/seqan3/range/views/kmer_hash.hpp [hunk 5]
```diff
@@ -239,11 +239,11 @@ class kmer_hash_view<urng_t>::shape_iterator
...
     using reference = value_type;
     //!\brief Tag this class as input iterator.
-    using iterator_category = typename std::iterator_traits<it_t>::iterator_category;
+    using iterator_category = detail::iterator_category_tag_t<it_t>;
     //!\brief Tag this class depending on which concept `it_t` models.
     using iterator_concept = std::conditional_t<std::contiguous_iterator<it_t>,
-                                                 typename std::random_access_iterator_tag,
-                                                 iterator_tag_t<it_t>>;
+                                                typename std::random_access_iterator_tag,
+                                                detail::iterator_concept_tag_t<it_t>>;
```
Comment (eseiler) [inline include/seqan3/range/views/kmer_hash.hpp:246]: This is the bit that fixes the issue, right?
Because no we do not use the input iterator tag, but the concept.

Comment (marehr) [reply include/seqan3/range/views/kmer_hash.hpp:246]: `iterator_concept_tag_t` will return an iterator_tag, but based on the concept.

For example: If `it_t` is a `std::random_access_iterator`, `detail::iterator_concept_tag_t<it_t>` would return `std::random_access_iterator_tag`

File: test/unit/core/type_traits/type_traits_iterator_test.cpp (hunk 3 above)
Comment (marehr) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:20]:
```suggestion
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp (hunk 4 above)
Comment (marehr) [reply test/unit/core/type_traits/type_traits_iterator_test.cpp:47]: True, but this is currently within a `WORKAROUND` environment. I would need to put it before a lot of code, I can do it, should I?

Comment (eseiler) [reply test/unit/core/type_traits/type_traits_iterator_test.cpp:44]:
```cpp
template <typename iterator_t>
SEQAN3_CONCEPT iterator_traits_has_iterator_category = requires()
{
    typename std::iterator_traits<iterator_t>::iterator_category;
};

template <typename iterator_t>
SEQAN3_CONCEPT has_iterator_category_tag_t = requires()
{
    typename seqan3::detail::iterator_category_tag_t<iterator_t>;
};
```
is in no if/else block, so it could go to line 18.

Or do I miss something?

File: include/seqan3/range/views/kmer_hash.hpp (hunk 5 above)
Comment (eseiler) [reply include/seqan3/range/views/kmer_hash.hpp:246]: Yes, and before we just propagated the `iterator_category` which was wrong.

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 6]
```diff
@@ -0,0 +1,304 @@
...
+
+#include <seqan3/std/concepts>
+#include <forward_list>
+#include <seqan3/std/iterator>
+#include <list>
+#include <seqan3/std/ranges>
+#include <vector>
+
+#include <seqan3/core/type_traits/iterator.hpp>
+
```
Comment (marehr) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:18]:
```suggestion

template <typename iterator_t>
SEQAN3_CONCEPT iterator_traits_has_iterator_category = requires()
{
    typename std::iterator_traits<iterator_t>::iterator_category;
};

template <typename iterator_t>
SEQAN3_CONCEPT has_iterator_category_tag_t = requires()
{
    typename seqan3::detail::iterator_category_tag_t<iterator_t>;
};

```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 7]
```diff
@@ -0,0 +1,304 @@
...
+{
+    typename std::iterator_traits<iterator_t>::iterator_category;
+};
+
+template <typename iterator_t>
+SEQAN3_CONCEPT has_iterator_category_tag_t = requires()
+{
+    typename seqan3::detail::iterator_category_tag_t<iterator_t>;
+};
+
```
Comment (marehr) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:72]:
```suggestion
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 8]
```diff
@@ -0,0 +1,304 @@
...
+struct inherit_iterator_tag : public base_t
+{
+    using iterator_concept = seqan3::detail::iterator_concept_tag_t<base_t>;
+};
+
+template <typename base_t>
+    requires requires()
+    {
+        typename seqan3::detail::iterator_category_tag_t<base_t>;
+    }
```
Comment (marehr) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:44]:
```suggestion
template <has_iterator_category_tag_t base_t>
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp (hunk 4 above)
Comment (marehr) [reply test/unit/core/type_traits/type_traits_iterator_test.cpp]: Done

File: include/seqan3/core/type_traits/iterator.hpp [hunk 9]
```diff
@@ -148,89 +148,88 @@ struct size_type<it_t>
...
+struct iterator_category_tag
+{
+    using iterator_category = void;
+};
 
+template <typename it_t>
+    requires requires { typename std::iterator_traits<it_t>::iterator_category; }
+struct iterator_category_tag<it_t>
+{
+    using iterator_category = typename std::iterator_traits<it_t>::iterator_category;
```
Comment (rrahn) [inline include/seqan3/core/type_traits/iterator.hpp:169]:
```suggestion
    using type = typename std::iterator_traits<it_t>::iterator_category;
```
? Otherwise it is not a seqan3::transformation_trait

File: include/seqan3/core/type_traits/iterator.hpp [hunk 10]
```diff
@@ -148,89 +148,88 @@ struct size_type<it_t>
...
  */
 template <typename it_t>
-struct iterator_tag
-{
-#if SEQAN3_DOXYGEN_ONLY(1)0
-    //!\brief The [iterator_category](https://en.cppreference.com/w/cpp/iterator/iterator_tags).
-    using type = iterator_category;
-#endif
-};
+using iterator_category_tag_t = typename iterator_category_tag<it_t>::iterator_category;
```
Comment (rrahn) [inline include/seqan3/core/type_traits/iterator.hpp:182]: This is now the shortcut alias and not the actual transformation trait anymore. So I guess the documentation should be updated?

File: include/seqan3/core/type_traits/iterator.hpp [hunk 11]
```diff
@@ -148,89 +148,88 @@ struct size_type<it_t>
...
+} // namespace seqan3
+
+namespace seqan3::detail
+{
+#if SEQAN3_WORKAROUND_GCC_96070
+//!\cond
+template <typename it_t>
+struct iterator_category_tag
+{
+    using iterator_category = void;
```
Comment (rrahn) [inline include/seqan3/core/type_traits/iterator.hpp:162]: so if iterator_category is not defined we set it to void? That means this becomes not a valid iterator anymore with the concepts. So I always have to specify the iterator category for every iterator, or must make sure, that the iterator_traits is overloaded for the iterator and specifies the iterator_category. If I read the standard correctly only `ITER_CONCEPT` must derive from the respective iterator tag it models. So my read on this is that a c++20 iterator is well defined, if it defines an iterator_concept but not iterator category. Ah ok. So we always have to specify the iterator_concept for all our iterators and to make them compliant with legacy iterators we need to define iterator_category, unless it is not defined in the underlying iterator. Then the underlying iterator was already not a valid legacy iterator and we don't need to make it a valid one. Sorry for the brain dump. I just needed to understand this. Maybe you can verify or correct me if I am seeing it wrong.

File: include/seqan3/core/type_traits/iterator.hpp [hunk 12]
```diff
@@ -148,89 +148,88 @@ struct size_type<it_t>
...
+            std::conditional_t<
+                std::bidirectional_iterator<it_t>,
+                std::bidirectional_iterator_tag,
+                std::conditional_t<
+                    std::forward_iterator<it_t>,
+                    std::forward_iterator_tag,
+                    std::conditional_t<
+                        std::input_iterator<it_t>,
+                        std::input_iterator_tag,
+                        std::output_iterator_tag>>>>>;
```
Comment (rrahn) [inline include/seqan3/core/type_traits/iterator.hpp:231]: nice

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 13]
```diff
@@ -0,0 +1,300 @@
...
+#ifdef __cpp_lib_ranges // This is C++20 behaviour.
+TEST(iterator_category_tag_t, no_legacy_iterator)
+{
+    {
+        using view_t = std::ranges::basic_istream_view<char, char, std::char_traits<char>>;
+        using iterator_t = std::ranges::iterator_t<view_t>;
+#if SEQAN3_WORKAROUND_GCC_96070
+        EXPECT_TRUE((std::same_as<seqan3::detail::iterator_category_tag_t<iterator_t>, void>));
+#else // ^^^ workaround / no workaround vvv
+        EXPECT_TRUE(!has_iterator_category_tag_t<iterator_t>);
```
Comment (rrahn) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:78]: It might be just a personal preference, but I like the style to say EXPECT_FALSE instead of EXPECT_TRUE on a negated expression. Because it is easier to read and to follow: `I expect that the expression evaluates to false` rather than `I expect the negation of the expression evaluates to true`.

File: test/unit/range/views/view_kmer_hash_test.cpp [hunk 14]
```diff
@@ -222,11 +223,38 @@ TYPED_TEST(kmer_hash_ungapped_test, issue1754)
...
+{
+    TypeParam text1{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4, 'C'_dna4}; // ACGTAGC
+    result_t ungapped{57, 36, 19, 13, 54};
+    if constexpr (std::ranges::bidirectional_range<TypeParam>) // excludes forward_list
+    {
+        auto v = text1 | seqan3::views::complement | ungapped_view;
+        EXPECT_RANGE_EQ(ungapped, v);
+        EXPECT_TRUE(std::ranges::forward_range<decltype(v)>);
+    }
+
```
Comment (rrahn) [inline test/unit/range/views/view_kmer_hash_test.cpp:246]:
```suggestion
```

File: include/seqan3/core/platform.hpp [hunk 15]
```diff
@@ -266,6 +266,15 @@
 #   endif
 #endif
 
+//!\brief See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96070 and https://github.com/seqan/product_backlog/issues/151
+#ifndef SEQAN3_WORKAROUND_GCC_96070 // not yet fixed, this is a defect within the standard lib
+#   if defined(__GNUC__)
```
[the remark this answers is not in the document]
Comment (marehr) [reply include/seqan3/core/platform.hpp:271]:
```suggestion
#   if defined(__GNUC__) && (__GNUC__ == 11 && __GNUC_MINOR__ >= 1) // remind us of this issue once gcc-11 was released.
```

File: include/seqan3/core/type_traits/iterator.hpp (hunk 11 above)
Comment (marehr) [reply include/seqan3/core/type_traits/iterator.hpp:162]: See https://github.com/seqan/seqan3/issues/1963#issuecomment-653820580 for an explanation.

File: include/seqan3/core/type_traits/iterator.hpp (hunk 9 above)
Comment (marehr) [reply include/seqan3/core/type_traits/iterator.hpp:169]: Does it need to be a `transformation_trait`, though? I've no strong feelings, so I'll change it :)

File: include/seqan3/core/type_traits/iterator.hpp (hunk 10 above)
Comment (marehr) [inline include/seqan3/core/type_traits/iterator.hpp:182]:
```suggestion
using iterator_category_tag_t = typename iterator_category_tag<it_t>::type;
```

File: include/seqan3/core/type_traits/iterator.hpp (hunk 11 above)
Comment (marehr) [inline include/seqan3/core/type_traits/iterator.hpp:162]:
```suggestion
    using type = void;
```

File: include/seqan3/core/type_traits/iterator.hpp [hunk 16]
```diff
@@ -148,89 +148,88 @@ struct size_type<it_t>
...
-};
+using iterator_category_tag_t = typename iterator_category_tag<it_t>::iterator_category;
+#else // ^^^ workaround / no workaround vvv
+// TODO: Change the description / the definition of iterator_category_tag_t depending on how the standard resolves this
+// https://github.com/seqan/product_backlog/issues/151
 
-//!\cond
+/*!\brief Exposes the
+ * [iterator_category](https://en.cppreference.com/w/cpp/iterator/iterator_tags) from the modelled concept.
+ * \implements seqan3::transformation_trait
```
Comment (marehr) [inline include/seqan3/core/type_traits/iterator.hpp:189]:
```suggestion
```

File: include/seqan3/core/type_traits/iterator.hpp (hunk 12 above)
Comment (marehr) [reply include/seqan3/core/type_traits/iterator.hpp:231]: :see_no_evil:

File: test/unit/core/type_traits/type_traits_iterator_test.cpp (hunk 13 above)
Comment (marehr) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:78]:
```suggestion
        EXPECT_FALSE(has_iterator_category_tag_t<iterator_t>);
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 17]
```diff
@@ -0,0 +1,300 @@
...
+#endif // SEQAN3_WORKAROUND_GCC_96070
+        EXPECT_TRUE(!iterator_traits_has_iterator_category<iterator_t>);
```
Comment (marehr) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:80]:
```suggestion
        EXPECT_FALSE(iterator_traits_has_iterator_category<iterator_t>);
```

File: test/unit/core/type_traits/type_traits_iterator_test.cpp [hunk 18]
```diff
@@ -0,0 +1,300 @@
...
+
+    {
+        using view_t = std::ranges::basic_istream_view<char, char, std::char_traits<char>>;
+        using iterator_t = my_iterator<std::ranges::iterator_t<view_t>>;
+#if SEQAN3_WORKAROUND_GCC_96070
+        EXPECT_TRUE((std::same_as<seqan3::detail::iterator_category_tag_t<iterator_t>, void>));
+        EXPECT_TRUE((std::same_as<std::iterator_traits<iterator_t>::iterator_category, void>));
+#else // ^^^ workaround / no workaround vvv
+        EXPECT_TRUE(!has_iterator_category_tag_t<iterator_t>);
+        EXPECT_TRUE(!iterator_traits_has_iterator_category<iterator_t>);
```
Comment (marehr) [inline test/unit/core/type_traits/type_traits_iterator_test.cpp:91]:
```suggestion
        EXPECT_FALSE(has_iterator_category_tag_t<iterator_t>);
        EXPECT_FALSE(iterator_traits_has_iterator_category<iterator_t>);
```

File: include/seqan3/core/type_traits/iterator.hpp [hunk 19]
```diff
@@ -148,89 +148,87 @@ struct size_type<it_t>
...
  */
 template <typename it_t>
-struct iterator_tag
-{
-#if SEQAN3_DOXYGEN_ONLY(1)0
-    //!\brief The [iterator_category](https://en.cppreference.com/w/cpp/iterator/iterator_tags).
-    using type = iterator_category;
-#endif
-};
+using iterator_category_tag_t = typename iterator_category_tag<it_t>::type;
```
Comment (rrahn) [inline include/seqan3/core/type_traits/iterator.hpp:182]: sill this is documented as transformation trait but it is not since it does not have a member type called `type`. This is the shortcut for the actual transformation trait. Either remove the `\implements seqan3::transformation_trait` or move the documentation to the actual transformation trait and document this as the shortcut for this.

File: include/seqan3/core/type_traits/iterator.hpp [hunk 20]
```diff
@@ -148,89 +148,87 @@ struct size_type<it_t>
...
-    using type = std::random_access_iterator_tag;
-};
 //!\endcond
+using iterator_category_tag_t = typename std::iterator_traits<it_t>::iterator_category;
+#endif // SEQAN3_WORKAROUND_GCC_96070
 
-/*!\brief Return the `iterator_category` type of the input type (transformation_trait shortcut).
+/*!\brief Exposes the
+ * [iterator_concept](https://en.cppreference.com/w/cpp/iterator/iterator_tags) from the modelled concept.
+ * \implements seqan3::transformation_trait
```
Comment (rrahn) [inline include/seqan3/core/type_traits/iterator.hpp:206]:
```suggestion
```

File: include/seqan3/core/type_traits/iterator.hpp [hunk 21]
```diff
@@ -148,89 +148,87 @@ struct size_type<it_t>
...
+template <typename it_t>
+    requires requires { typename std::iterator_traits<it_t>::iterator_category; }
+struct iterator_category_tag<it_t>
+{
+    using type = typename std::iterator_traits<it_t>::iterator_category;
+};
+//!\endcond
 /*!\brief Exposes the
  * [iterator_category](https://en.cppreference.com/w/cpp/iterator/iterator_tags) from the modelled concept.
  * \implements seqan3::transformation_trait
```
Comment (rrahn) [inline include/seqan3/core/type_traits/iterator.hpp:174]:
```suggestion
```

File: include/seqan3/core/type_traits/iterator.hpp [hunk 22]
```diff
@@ -148,89 +148,85 @@ struct size_type<it_t>
...
-};
-
+//!\endcond
+/*!\brief Exposes the
+ * [iterator_category](https://en.cppreference.com/w/cpp/iterator/iterator_tags) from the modelled concept.
+ * \tparam it_t The type to operate on.
+ *
+ * \attention
+ * If [std::iterator_traits<it_t>::iterator_category](https://en.cppreference.com/w/cpp/iterator/iterator_traits)
+ * is defined for a type `it_t`, this transformation trait acts as an alias for it, if not it is `void`.
```
Comment (marehr) [inline include/seqan3/core/type_traits/iterator.hpp:178]:
```suggestion
 * is defined for a type `it_t`, this acts as an alias for it, if not it is `void`.
```
