### PR TITLE
Fix issues with missing zlib

### LINKED ISSUE #1106: [BUG] Including file io does not work without zlib
Because in line 105 of `misc_input.hpp`

```cpp
if (read_chars == magic_number.size() && contrib::_bgzfCheckHeader(magic_number.data())) // BGZF
```

the function `_bgzfCheckHeader` is used although declared in the bgzf_stream header which is **not included** if zlib is not available.

### PR DESCRIPTION
**Pull request by rrahn**
Fixes #1106 

Blocked by ~~#1224~~

### CODE REVIEW

File: include/seqan3/io/detail/magic_header.hpp [hunk 1]
```diff
@@ -13,9 +13,11 @@
 #pragma once
 
 #include <array>
+#include <string>
+#include <vector>
```
Comment (smehringer) [inline include/seqan3/io/detail/magic_header.hpp]: in the node you added, you do not use `vector` or `string` ?

File: include/seqan3/io/detail/misc_input.hpp [hunk 2]
```diff
@@ -104,14 +104,14 @@ inline auto make_secondary_istream(std::basic_istream<char_t> & primary_stream,
         extension = filename.extension().string().substr(1);
 
     // tests whether the given extension matches with one of the given compression tags.
-    auto contains_extension = [] (auto compression_tag, auto const & extension)
+    [[maybe_unused]] auto contains_extension = [] (auto compression_tag, auto const & extension)
```
Comment (smehringer) [inline include/seqan3/io/detail/misc_input.hpp]: why don't you move this inside of the first if scope to avoid the maybe_unused macro?

Comment (rrahn) [reply include/seqan3/io/detail/misc_input.hpp]: That does not work. Since it might be that zlib is not available but zstd is.

File: include/seqan3/io/detail/magic_header.hpp (hunk 1 above)
Comment (rrahn) [reply include/seqan3/io/detail/magic_header.hpp]: Yes, but I cleaned up the includes and string and vector are used inside of the file at other places.

File: include/seqan3/io/detail/magic_header.hpp [hunk 3]
```diff
@@ -85,6 +87,29 @@ struct bgzf_compression
...
+    static bool validate_header(char const * header)
+    {
+        auto unpack = [] (char const * buffer)
+        {
+            uint16_t tmp;
+            std::uninitialized_copy(buffer, buffer + sizeof(uint16_t), reinterpret_cast<char *>(&tmp));
+            return to_little_endian(tmp);
+        };
+
+        return (header[0] == static_cast<char>(magic_header[0]) &&   // GZ_ID1
```
Comment (rrahn) [inline include/seqan3/io/detail/magic_header.hpp]: remove static_cast

**Comment by rrahn** [comment]
@h-2 ping

File: include/seqan3/io/detail/magic_header.hpp [hunk 4]
```diff
@@ -85,6 +87,29 @@ struct bgzf_compression
     //  B       C       [SLEN        ]  [BSIZE       ]
         '\x42', '\x43', '\x02', '\x00', '\x00', '\x00'
     };
+
+    /*!\brief Checks if the given header is a bgzf header.
+     * \param[in] header The header to validate.
+     * \returns `true` if it is a bgzf header, otherwise `false`.
+     */
+    static bool validate_header(char const * header)
```
Comment (h-2) [inline include/seqan3/io/detail/magic_header.hpp]: Can we use `std::string_view` here? I think we should adopt that as policy everywhere instead of `char const *`...

File: include/seqan3/io/detail/misc_input.hpp (hunk 2 above)
Comment (h-2) [inline include/seqan3/io/detail/misc_input.hpp]:
```suggestion
    [[maybe_unused]] constexpr auto contains_extension = [] (auto compression_tag, auto const & extension)
```

File: include/seqan3/io/detail/magic_header.hpp (hunk 4 above)
Comment (rrahn) [reply include/seqan3/io/detail/magic_header.hpp]: Pheww, I am not sure if this is actually what you want in this context. I would rather pass it as the original std::array data.

File: include/seqan3/io/detail/misc_input.hpp (hunk 2 above)
Comment (rrahn) [reply include/seqan3/io/detail/misc_input.hpp]: Well, it this is never evaluated at compile time but I can make this change

File: include/seqan3/std/span [hunk 5]
```diff
@@ -384,14 +366,23 @@ public:
...
+constexpr auto begin(span<span_tp, extend> s) noexcept
+{
+    return s.begin();
+}
+
+template <typename span_tp, ptrdiff_t extend>
+constexpr auto end(span<span_tp, extend> s) noexcept
+{
+    return s.end();
+}
```
Comment (h-2) [inline include/seqan3/std/span]: these shouldnt be nessary, there are friends.

File: include/seqan3/std/span [hunk 6]
```diff
@@ -17,16 +17,19 @@
 //!\cond
 #pragma once
 
+#if __has_include(<span>)
```
Comment (h-2) [inline include/seqan3/std/span]: This will likely not be enough, but we can fix it later.

File: include/seqan3/std/span (hunk 5 above)
Comment (rrahn) [reply include/seqan3/std/span]: They are replacing the friends on purpose. With the friends everything breaks because of infinite recursive instantiation when evaluating std::ranges::begin :unamused:

File: include/seqan3/std/span (hunk 6 above)
Comment (rrahn) [reply include/seqan3/std/span]: agreed

**Comment by h-2** [comment]
Can you rebase now that the span is merged?

**Comment by rrahn** [comment]
@h-2 done
