### PR TITLE
[FIX] #262: gcc8 fails to compile reflection_test.cpp

### LINKED ISSUE #262: gcc8 fails to compile reflection_test.cpp
```
In file included from /seqan3/test/unit/core/detail/reflection_test.cpp:37:
/seqan3/include/seqan3/core/detail/reflection.hpp: In instantiation of ‘constexpr const size_t seqan3::detail::get_display_name_size<char>::value’:
/seqan3/include/seqan3/core/detail/reflection.hpp:107:18:   required from ‘constexpr const size_t seqan3::detail::get_display_name_size_v<char>’
/seqan3/include/seqan3/core/detail/reflection.hpp:148:26:   required from ‘constexpr const auto seqan3::detail::get_display_name<char>::get_display_name_fn’
/seqan3/include/seqan3/core/detail/reflection.hpp:145:27:   required from ‘struct seqan3::detail::get_display_name<char>’
/seqan3/include/seqan3/core/detail/reflection.hpp:175:28:   required from ‘constexpr const constexpr_string seqan3::detail::get_display_name_v<char>’
/seqan3/test/unit/core/detail/reflection_test.cpp:88:5:   required from ‘void reflection_name_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = char]’
/seqan3/test/unit/core/detail/reflection_test.cpp:86:1:   required from here
/seqan3/include/seqan3/core/detail/reflection.hpp:100:45:   in ‘constexpr’ expansion of ‘seqan3::detail::get_display_name_size<char>::get_size.seqan3::detail::get_display_name_size<char>::<lambda()>()’
/seqan3/include/seqan3/core/detail/reflection.hpp:100:29: error: array subscript value ‘56’ is outside the bounds of array type ‘const char [56]’
     static constexpr size_t value = get_size();
```

@rrahn can you resolve this?

### PR DESCRIPTION
**Pull request by marehr**
As you can see, gcc-8 changed the output of `__PRETTY_FUNCTION__`.

The `[with type = int]` part is now missing; therefore, `get_size()` skipped over all characters until after `\0`

resolves #262

### CODE REVIEW

File: test/unit/core/detail/reflection_test.cpp [hunk 1]
```diff
@@ -83,7 +85,93 @@ class reflection : public ::testing::Test
...
+
+    std::string foo_bar_char = seqan3::detail::pretty_lambda<foo::bar<char>>::as_string();
+#if defined(__clang__)
+    EXPECT_EQ(foo_bar_char, "auto seqan3::detail::pretty_lambda<foo::bar<char> >::(anonymous class)::operator()() const [type = foo::bar<char>]");
+#elif defined(__GNUC__) && __GNUC__ >= 8
+    EXPECT_EQ(foo_bar_char, "seqan3::detail::pretty_lambda<foo::bar<char> >::<lambda()>");
+#elif defined(__GNUC__)
+    EXPECT_EQ(foo_bar_char, "seqan3::detail::pretty_lambda<type>::<lambda()> [with type = foo::bar<char>]");
+#endif
+}
```
Comment (h-2) [inline test/unit/core/detail/reflection_test.cpp]: You are not testing the library here, but instead local stuff from the tests... why?

Comment (marehr) [reply test/unit/core/detail/reflection_test.cpp]: It ensures that the format of the underlying used method stays the same. Furthermore, It took me quite some time to figure out, what the output of `__PRETTY_FUNCTION__` is.

Comment (h-2) [reply test/unit/core/detail/reflection_test.cpp]: But the tests should always test the library and not "something similar" also implemented in the test. If the code tested in the test is very similar to the actual library code it shouldn't be necessary, if it is substantially different, then chances are big the code will generate false positive and/or false negative test failures.
E.g.: doing a full string comparison is much stricter than our actual library code, many changes to the string may be non-breaking.

Comment (marehr) [reply test/unit/core/detail/reflection_test.cpp]: I think we have a different feeling about test cases.

The thing is that in this case we base our functionality on some undocumented behaviour. The only way to ensure the behaviour is to actually test it and react to any change (even if it's stricter). This by design encourages false positives/negatives.

But I can remove it altogether and just leave 

```patch

+TEST(pretty_function, as_string)
+{
+    // an example how to extract the type
+    auto type_name = [](std::string pretty)
+    {
+        auto start = pretty.find("type = ") + std::string("type = ").size();
+        auto end = pretty.rfind("]");
+
+        return pretty.substr(start, end - start);
+    };
+
+    std::string int_ = seqan3::detail::pretty_function<int>::as_string();
+    EXPECT_EQ(type_name(int_), "int");
+
+    std::string foo_bar_char = seqan3::detail::pretty_function<foo::bar<char>>::as_string();
+    EXPECT_EQ(type_name(foo_bar_char), "foo::bar<char>");
+}
```

**Comment by marehr** [comment]
A different question would be, if we want to harden the parse function and explicitly test for overflows?

**Comment by h-2** [comment]
I see your point in general, but I am still weakly against it. It is up to @rrahn as the original author.

**Comment by rrahn** [comment]
I see both points, and the solution with a static_assert within the class seems also a little cumbersome, also it defeats the purpose to see what changed. I would agree to have a test, to check the PRETTY_FUNCTION output. Please add a comment on this, to make clear that no explicit library feature is tested.

File: test/unit/core/detail/reflection_test.cpp [hunk 2]
```diff
@@ -83,7 +85,65 @@ class reflection : public ::testing::Test
...
 {
     EXPECT_EQ(detail::get_display_name_v<TypeParam>.string(), this->expected_name());
 }
+
+namespace seqan3::detail
+{
+template <typename type>
+struct pretty_function
+{
+    static auto as_string()
```
Comment (rrahn) [inline test/unit/core/detail/reflection_test.cpp]: to_string would be more STL compliant.

File: test/unit/core/detail/reflection_test.cpp [hunk 3]
```diff
@@ -83,7 +85,65 @@ class reflection : public ::testing::Test
...
+    // an example how to extract the type
+    auto type_name = [](std::string pretty)
+    {
+        auto start = pretty.find("type = ") + std::string("type = ").size();
+        auto end = pretty.rfind("]");
+
+        return pretty.substr(start, end - start);
+    };
+
+    std::string int_ = seqan3::detail::pretty_function<int>::as_string();
```
Comment (rrahn) [inline test/unit/core/detail/reflection_test.cpp]: please use a different name for the `int_` variable. It confused me a second to what it represents.

File: test/unit/core/detail/reflection_test.cpp [hunk 4]
```diff
@@ -83,7 +85,65 @@ class reflection : public ::testing::Test
...
+    EXPECT_EQ(foo_bar_char, "static auto seqan3::detail::pretty_function<foo::bar<char> >::as_string() [type = foo::bar<char>]");
+#elif defined(__GNUC__)
+    EXPECT_EQ(foo_bar_char, "static auto seqan3::detail::pretty_function<type>::as_string() [with type = foo::bar<char>]");
+#endif
+}
+
+// NOTE: This does not test a seqan3 library feature, but the underlying magic
+// of how seqan3::detail::get_display_name_v works. This is needed, because
+// __PRETTY_FUNCTION__ has vendor specific output which is not standardised.
+TEST(pretty_function, as_string)
```
Comment (rrahn) [inline test/unit/core/detail/reflection_test.cpp]: I do get the reasoning for the above code. But this here is exactly the same as the original tests, isn't it?
I think this test case does not add any more information. Please, correct me if I am wrong.

**Comment by marehr** [comment]
@rrahn addressed your points
