### PR TITLE
[FIX] Fixes empty pairwise combine view.

### LINKED ISSUE #1945: pairwise_combine_view segfaults on some empty ranges.
```c++
std::forward_list<int> v{};
seqan3::detail::pairwise_combine_view view{std::views::all(v)};
view.begin();
```

## Platform

  - SeqAn version: 
  - Operating system: 
  - Compiler:

### PR DESCRIPTION
**Pull request by rrahn**
Fixes #1945

### CODE REVIEW

File: test/unit/range/views/view_pairwise_combine_test.cpp [hunk 1]
```diff
@@ -524,3 +524,11 @@ TEST(pairwise_combine_fn_test, const_source)
...
     EXPECT_EQ(*++it, (std::tuple{'c', 'd'}));
 }
+
+// https://github.com/seqan/seqan3/issues/1945
+TEST(empty_pairwise_combine_test, issue_1945)
+{
+    std::forward_list<int> v{};
+    seqan3::detail::pairwise_combine_view view{std::views::all(v)};
+    EXPECT_TRUE(std::ranges::empty(view));
+}
```
Comment (marehr) [inline test/unit/range/views/view_pairwise_combine_test.cpp:534]:
```suggestion
TYPED_TEST(pairwise_combine_test, issue_1945)
{
    TypeParam container{};
    seqan3::detail::pairwise_combine_view view{std::views::all(container)};
    EXPECT_TRUE(std::ranges::empty(view));
}
```

Comment (rrahn) [reply test/unit/range/views/view_pairwise_combine_test.cpp:534]: Yes, I think this is good.
