### PR TITLE
[FIX] Fix requires in seqan3::char_is_valid_for CPO.

### LINKED ISSUE #1518: Some alphabets do not compile with seqan3::writable_alphabet concept
Some `alphabet` that models `seqan3::alphabet` can't be tested with `seqan3::writable_alphabet`.

Example:

```c++
struct alphabet2_shim
{
    using rank_t = uint8_t;
    using char_t = char;

    rank_t to_rank() const noexcept;
    char_t to_char() const noexcept;

    constexpr static bool alphabet_size{0};

    friend bool operator<(alphabet2_shim, alphabet2_shim);
    friend bool operator<=(alphabet2_shim, alphabet2_shim);
    friend bool operator>(alphabet2_shim, alphabet2_shim);
    friend bool operator>=(alphabet2_shim, alphabet2_shim);
    friend bool operator==(alphabet2_shim, alphabet2_shim);
    friend bool operator!=(alphabet2_shim, alphabet2_shim);
};

static_assert(seqan3::semialphabet<alphabet2_shim>);
static_assert(!seqan3::writable_semialphabet<alphabet2_shim>);
static_assert(seqan3::alphabet<alphabet2_shim>);
static_assert(!seqan3::writable_alphabet<alphabet2_shim>); // does not compile
```

Error:

```
In file included from /seqan3/test/unit/alphabet/nucleotide/../alphabet_constexpr_test_template.hpp:10,
                 from /seqan3/test/unit/alphabet/nucleotide/rna4_test.cpp:8:
/seqan3/include/seqan3/alphabet/concept.hpp: In instantiation of ‘struct seqan3::detail::adl_only::char_is_valid_for_fn<alphabet2_shim>’:
/seqan3/include/seqan3/alphabet/concept.hpp:521:23:   required from ‘constexpr const auto seqan3::char_is_valid_for<alphabet2_shim>’
/seqan3/include/seqan3/alphabet/concept.hpp:891:15:   required from here
/seqan3/include/seqan3/alphabet/concept.hpp:456:35: error: no matching function for call to ‘seqan3::detail::adl_only::char_is_valid_for_fn<alphabet2_shim>::impl(seqan3::detail::priority_tag<3>, seqan3::alphabet_char_t<alphabet2_shim>&)’
  456 |             requires noexcept(impl(priority_tag<3>{}, a));
      |                               ~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from /seqan3/include/seqan3/alphabet/concept.hpp:18,
                 from /seqan3/test/unit/alphabet/nucleotide/../alphabet_constexpr_test_template.hpp:10,
                 from /seqan3/test/unit/alphabet/nucleotide/rna4_test.cpp:8:
/seqan3/include/seqan3/core/detail/customisation_point.hpp:48:33: note: candidate: ‘static constexpr decltype(auto) seqan3::detail::adl_only::char_is_valid_for_fn<alph_t>::impl(seqan3::detail::priority_tag<3>, t&&, arg_ts&& ...) requires (<requires (const seqan3::detail::priority_tag<3>&, t& v, #‘type_pack_expansion’ not supported by simple_type_specifier#... args#‘type_pack_expansion’ not supported by direct_abstract_declarator#) <valid-expression ((seqan3::detail::deferred_type<seqan3::custom::alphabet<t>, decltype(v)>::deferred_type_t::char_is_valid)(v))>> [with t = const char&; arg_ts = {}; alph_t = alphabet2_shim]’
   48 | static constexpr decltype(auto) impl(seqan3::detail::priority_tag<PRIO>,                                             \
      |                                 ^~~~
/seqan3/include/seqan3/alphabet/concept.hpp:444:5: note: in expansion of macro ‘SEQAN3_CPO_IMPL’
  444 |     SEQAN3_CPO_IMPL(3, (deferred_type_t<seqan3::custom::alphabet<alph_t>, decltype(v)>::char_is_valid(v))) // expl. cst.
      |     ^~~~~~~~~~~~~~~
/seqan3/include/seqan3/core/detail/customisation_point.hpp:48:33: note:   constraints not satisfied
   48 | static constexpr decltype(auto) impl(seqan3::detail::priority_tag<PRIO>,                                             \
      |                                 ^~~~
/seqan3/include/seqan3/alphabet/concept.hpp:444:5: note: in expansion of macro ‘SEQAN3_CPO_IMPL’
  444 |     SEQAN3_CPO_IMPL(3, (deferred_type_t<seqan3::custom::alphabet<alph_t>, decltype(v)>::char_is_valid(v))) // expl. cst.
      |     ^~~~~~~~~~~~~~~
/seqan3/include/seqan3/core/detail/customisation_point.hpp:48:33: note:     with ‘const seqan3::detail::priority_tag<3>& <anonymous>’
   48 | static constexpr decltype(auto) impl(seqan3::detail::priority_tag<PRIO>,                                             \
      |                                 ^~~~
/seqan3/include/seqan3/alphabet/concept.hpp:444:5: note: in expansion of macro ‘SEQAN3_CPO_IMPL’
  444 |     SEQAN3_CPO_IMPL(3, (deferred_type_t<seqan3::custom::alphabet<alph_t>, decltype(v)>::char_is_valid(v))) // expl. cst.
      |     ^~~~~~~~~~~~~~~
/seqan3/include/seqan3/core/detail/customisation_point.hpp:48:33: note:     with ‘const char& v’
   48 | static constexpr decltype(auto) impl(seqan3::detail::priority_tag<PRIO>,                                             \
      |                                 ^~~~
/seqan3/include/seqan3/alphabet/concept.hpp:444:5: note: in expansion of macro ‘SEQAN3_CPO_IMPL’
  444 |     SEQAN3_CPO_IMPL(3, (deferred_type_t<seqan3::custom::alphabet<alph_t>, decltype(v)>::char_is_valid(v))) // expl. cst.
      |     ^~~~~~~~~~~~~~~
/seqan3/include/seqan3/core/detail/customisation_point.hpp:48:33: note: the required expression ‘seqan3::detail::deferred_type_t<seqan3::custom::alphabet<t>, decltype (v)>::char_is_valid(v)’ would be ill-formed
   48 | static constexpr decltype(auto) impl(seqan3::detail::priority_tag<PRIO>,                                             \
      |                                 ^~~~
/seqan3/include/seqan3/alphabet/concept.hpp:444:5: note: in expansion of macro ‘SEQAN3_CPO_IMPL’
  444 |     SEQAN3_CPO_IMPL(3, (deferred_type_t<seqan3::custom::alphabet<alph_t>, decltype(v)>::char_is_valid(v))) // expl. cst.
      |     ^~~~~~~~~~~~~~~

```

### PR DESCRIPTION
**Pull request by smehringer**
Fixes #1518 

@h-2 You might also want to take a look. I don't understand my own fix... :sweat_smile: It just works now

### CODE REVIEW

**Comment by h-2** [comment]
So the problem is `constexpr bool operator()(alphabet_char_t<alph_t> const a) ` by itself is not a template, because `alph_t` is a template parameter of the enclosing class and not of the function. This results in concept checks on the function being evaluated at the time the struct is instantiated and not when function is actually used.
We need the latter, i.e. the function needs to be instantiated later in two-phase name lookup. The reason is that there are inter-dependencies, actual implementation might be defined later and so on.

To defer the instantiation, the function is "artificially" made a function template with a bogus template parameter (which is defaulted so you needn't actually provide it). Now GCC is smarter than us of course, so instead of saying "this is a template, I will perform constraint checks on it when I instantiate it", GCC instead looks into the constraint and says "this particular constraint does not actually use the template parameter, so I will check the result of it now and instantiate the IMPL functions now, as well."
But the IMPL functions aren't resolvable, yet. That's the reason we added the template in the first place. By inserting `dummy{}` into the call you force GCC to delay instantiation of the IMPLs to the second phase of name lookup, because `dummy` is only defined at the time the operator is actually instantiated. This makes everything works again.

**Comment by h-2** [comment]
See the definition of `SEQAN3_CPO_IMPL` to understand why `dummy{}` is ignored:
https://github.com/seqan/seqan3/blob/master/include/seqan3/core/detail/customisation_point.hpp#L52
It goes into `args` but since none of STRINGS passed to the macro reference `args`, the parameter is not used. On the other hand `a`, the second argument in https://github.com/seqan/seqan3/pull/1924/files#diff-c4e11b96ebc75682ef6d95d238c5ab8eR456 is turned into `v` by the macro which is referenced inside the STRINGS so this argument is used.

**Comment by h-2** [comment]
Usually the dummy is not needed because the type of `a` is already dependent on the current instantiation of the operator.

File: test/unit/alphabet/custom_alphabet4_test.cpp [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    friend bool operator>(alphabet2_shim, alphabet2_shim);
+    friend bool operator>=(alphabet2_shim, alphabet2_shim);
+    friend bool operator==(alphabet2_shim, alphabet2_shim);
+    friend bool operator!=(alphabet2_shim, alphabet2_shim);
+};
+
+static_assert(seqan3::semialphabet<alphabet2_shim>);
+static_assert(!seqan3::writable_semialphabet<alphabet2_shim>);
+static_assert(seqan3::alphabet<alphabet2_shim>);
+static_assert(!seqan3::writable_alphabet<alphabet2_shim>);
```
Comment (marehr) [inline test/unit/alphabet/custom_alphabet4_test.cpp:36]: Can we make this a proper google test?

Comment (smehringer) [reply test/unit/alphabet/custom_alphabet4_test.cpp:36]: Sure. I just wanted to push early because hannes was active and I saw my chance to get an explanation :D

File: test/unit/alphabet/custom_alphabet4_test.cpp [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+    friend bool operator<=(non_writeable_alphabet, non_writeable_alphabet);
+    friend bool operator>(non_writeable_alphabet, non_writeable_alphabet);
+    friend bool operator>=(non_writeable_alphabet, non_writeable_alphabet);
+    friend bool operator==(non_writeable_alphabet, non_writeable_alphabet);
+    friend bool operator!=(non_writeable_alphabet, non_writeable_alphabet);
+};
+
+
+TEST(non_writeable_alphabet_test, issue1518)
+{ // see issue https://github.com/seqan/seqan3/issues/1518
```
Comment (marehr) [inline test/unit/alphabet/custom_alphabet4_test.cpp:32]:
```suggestion

// see issue https://github.com/seqan/seqan3/issues/1518
TEST(non_writeable_alphabet_test, issue1518)
{
```
