### PR TITLE
[FIX] Handle unsupported tags

### LINKED ISSUE #2600: [BUG] SAM does not allow user-defined tags in header
While testing iGenVar with real data (PacBio long reads from https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_10kb/alignment/) I ran into some errors:

```bash
terminate called after throwing an instance of 'seqan3::format_error'
  what():  Illegal SAM header tag in @HG starting with: p
```
from header file:
```sam
@HD	VN:1.5	SO:coordinate	pb:3.0.1
```
and without the `pb:3.0.1`
```bash
terminate called after throwing an instance of 'seqan3::format_error'
  what():  Illegal SAM header tag starting with: I
```
from a header line like
```sam
@RG	ID:35690b08	SM:HG002	PU:m54238_180628_014238	DS:READTYPE=CCS;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-400;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000	PL:PACBIO	PM:SEQUEL
```

## Platform

  - SeqAn version: 3.0.3
  - Operating system: Debian GNU/Linux 10
  - Compiler: gcc (Debian 8.3.0-6) 8.3.0

### How to repeat the problem

```bash
git clone https://github.com/seqan/iGenVar.git
git submodule update --recursive --init
cmake ../../Repos/iGenVar/ -Weverything
make -j 16

wget https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_10kb/alignment/HG002.Sequel.10kb.pbmm2.hs37d5.whatshap.haplotag.RTG.10x.trio.bam -nv

./build/iGenVar/bin/iGenVar -j HG002.Sequel.10kb.pbmm2.hs37d5.whatshap.haplotag.RTG.10x.trio.bam -o output.vcf
```

### Expected behaviour

iGenVar should run without errors

### Actual behaviour

`format_sam_base` throws `seqan3::format_error`

### PR DESCRIPTION
**Pull request by Irallia**
Resolves #2600

### CODE REVIEW

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 1]
```diff
@@ -589,11 +595,14 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
                             break;
 
                         default:
-                            throw format_error{std::string{"Illegal SAM header tag starting with: "} + *it};
+                            seqan3::debug_stream << "Not supported SAM header tag in @PG starting with: " << *it << '\n';
                     }
 
                     parse_tag_value(*who);
                 }
+                if (!id_tag_given)
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:603]:
```suggestion
                if (tmp.id.empty())
```

Then you do not need the `id_tag_given`

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 2]
```diff
@@ -22,8 +22,7 @@
 
 #include <seqan3/alphabet/views/char_to.hpp>
 #include <seqan3/alphabet/views/to_char.hpp>
-#include <seqan3/core/debug_stream/detail/to_string.hpp>
-#include <seqan3/core/detail/debug_stream_range.hpp>
+#include <seqan3/core/debug_stream.hpp>
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:25]: Can we get rid of this include?

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 3]
```diff
@@ -481,9 +480,9 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
                         else
                             throw format_error{std::string{"Illegal SAM header tag: S"} + *it};
                     }
-                    else if (!is_char<'G'>(*it))                        // GO (grouping) tag
+                    else                                                // GO (grouping) tag, pb (PacBio) version, etc
                     {
-                        throw format_error{std::string{"Illegal SAM header tag in @HG starting with: "} + *it};
+                        seqan3::debug_stream << "Not supported SAM header tag in @HD starting with: " << *it << '\n';
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:485]:
```suggestion
                        std::cerr << "Not supported SAM header tag in @HD starting with: " << *it << '\n';
```

? debug_stream is a bit overkill since it includes half the library and we don't need to format stuff here

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 4]
```diff
@@ -557,16 +556,23 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
             {
                 typename sam_file_header<ref_ids_type>::program_info_t tmp{};
 
-                parse_tag_value(tmp.id);                                // read required ID tag
+                ++it;                                                   // skip P
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:559]: the `RG` tag above has the same problem with `ID`

**Comment by eseiler** [comment]
We also have the problem that we assume that the required tags are the first tags, which is not true.
Since this affects multiple header lines (`HD`, `SQ`, `RG`, and `PG`), we should probably do 2 PRs and just fix the `pb` issue here

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 3 above)
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:485]: Ah, I did not know that. I thought that would be better than cerr, but no problem, I change that directly :) thanks for the tip

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 5]
```diff
@@ -481,9 +480,9 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
                         else
                             throw format_error{std::string{"Illegal SAM header tag: S"} + *it};
                     }
-                    else if (!is_char<'G'>(*it))                        // GO (grouping) tag
+                    else                                                // GO (grouping) tag, pb (PacBio) version, etc
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:483]: You changed some logic here.

* `GO` tags will now emit warnings even though they shouldn't
* unknown tags are passed to `parse_tag_value(*who);` which might not be correct?
* * Maybe we need to skip the unknown tag with `take_until_predicate` but I am not sure.

Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:483]: > - GO tags will now emit warnings even though they shouldn't

But we didn't do anything with the GO tag before, did we? So I thought I would include GO in the warning. But I can also undo that.

> - unknown tags are passed to parse_tag_value(*who); which might not be correct?
        - Maybe we need to skip the unknown tag with take_until_predicate but I am not sure.



`take_until_predicate` just skips everything until the next day? Well, since we don't support them, that sounds like the right way to go. Maybe @eldariont has a hint if it is worth to save them.

Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:483]: We can also think about making a specific distinction between upper case and lower case. Because lower case comes from the user and upper case should be in the specification, if I understood correctly.

Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:483]: > But we didn't do anything with the GO tag before, did we? So I thought I would include GO in the warning. But I can also undo that.

It was passed to `parse_tag_value(*who);` before.

> `take_until_predicate` just skips everything until the next day? 

`take_until_predicate(is_char<'\t'>)` or similar syntax should work

> Well, since we don't support them, that sounds like the right way to go. Maybe @eldariont has a hint if it is worth to save them.

We should support them at some point, but this would be a new feature (and would need to use the sam_tag_dictionary). For now, we should just ignore them.

Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:483]: > We can also think about making a specific distinction between uppercase and lowercase. Because lower case comes from the user and upper case should be in the specification, if I understood correctly.

It's not forbidden to do user-defined uppercase tags, it's just that lowercase are reserved for this, and it's best practice to use lowercase.
I wouldn't make a distinction between lower/uppercase

Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:483]: Okay, than I will skip them with your given syntax and open an issue for supporting them later.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 6]
```diff
@@ -481,9 +480,9 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
                         else
                             throw format_error{std::string{"Illegal SAM header tag: S"} + *it};
```
Comment (eldariont) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:481]: We should not throw for unknown tags starting with S (e.g. SL or whatever) but just ignore them.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 5 above)
Comment (eldariont) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:483]: I have never used any of the HD tags except SO (sorting order). Nevertheless, I agree with @eseiler that seqAn should not emit a warning for tags defined in the specs, like the GO tag.

**Comment by Irallia** [comment]
I have removed a lot of headers as they are probably not needed in the file, but it would be nice if someone verifies this.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 7]
```diff
@@ -461,51 +445,125 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+                            else
+                                throw format_error{std::string{"Illegal SAM header tag: S"} + *it};
+                        } break;
+                        case 'A':                                       // read rest of the tags (AH, AS
+                        case 'D':                                       // DS,
+                        case 'M':                                       // M5,
+                        case 'T':                                       // TP,
+                        case 'U':                                       // UR)
+                        {
+                            parse_until_tab_or_newline(get<1>(info));
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:549]: This will only store the last tag if there are multiple ones because you always parse until tab and overwrite `get<1>(info)`, no?

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 8]
```diff
@@ -527,84 +585,152 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+                        case 'B':                                       // read rest of the tags (BC,
+                        case 'C':                                       // CN,
+                        case 'D':                                       // DS, DT,
+                        case 'F':                                       // FO,
+                        case 'K':                                       // KS,
+                        case 'L':                                       // LB,
+                        case 'P':                                       // PG, PI, PL, PM, PU,
+                        case 'S':                                       // SM)
+                        {
+                            parse_until_tab_or_newline(get<1>(tmp));
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:628]: Same problem with overwriting if multiple tags

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 9]
```diff
@@ -527,84 +585,152 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-                    parse_tag_value(*who);
+                    if (no_default)
+                        parse_tag_value(*who);
                 }
-                ++it;                                                   // skip newline
-
+                if (tmp.id.empty())
+                    throw format_error{std::string{"The required ID tag is missing."}};
                 hdr.program_infos.emplace_back(std::move(tmp));
+                ++it;                                                   // skip newline
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:724]: Same comments as above

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 10]
```diff
@@ -21,13 +21,13 @@ struct sam_file_read<seqan3::format_sam> : public sam_file_data
...
+@PG	ID:qc	PN:quality_control	CL:qc -f file1	DS:trim reads with low qual	VN:1.0.0	pb:usr_defined_tag
+@PG	PN:novoalign	ID:novoalign	VN:V3.02.07	CL:novoalign -d /path/hs37d5.ndx -f /path/file.fastq.gz	PP:qc
 @SQ	SN:ref	LN:249250621
-@SQ	SN:ref2	LN:243199373	AS:hs37d5
+@SQ	SN:ref2	LN:243199373	AS:hs37d5	pb:usr_defined_tag
 @RG	ID:U0a_A2_L1	PL:illumina	PU:1	LB:1	SM:NA12878
-@RG	ID:U0a_A2_L2	PL:illumina	SM:NA12878	PU:1	LB:1
+@RG	ID:U0a_A2_L2	PL:illumina	SM:NA12878	PU:1	LB:1	pb:usr_defined_tag
 @CO	Tralalalalalala this is a comment
 )"};
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:32]: Please add new test cases for the individual changes and leave the old ones as they are.
I.e. a two line header for swapping `PN` and `ID` and a two line header for adding a user defined tag

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 2 above)
Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:21]: open

File: include/seqan3/io/sam_file/format_bam.hpp [hunk 11]
```diff
@@ -13,34 +13,22 @@
...
 
-#include <seqan3/alphabet/detail/convert.hpp>
 #include <seqan3/alphabet/nucleotide/dna16sam.hpp>
-#include <seqan3/core/debug_stream/detail/to_string.hpp>
-#include <seqan3/core/detail/debug_stream_optional.hpp>
-#include <seqan3/core/detail/template_inspection.hpp>
-#include <seqan3/core/range/type_traits.hpp>
-#include <seqan3/io/detail/ignore_output_iterator.hpp>
-#include <seqan3/io/detail/misc.hpp>
+#include <seqan3/core/debug_stream.hpp>
```
Comment (eseiler) [inline include/seqan3/io/sam_file/format_bam.hpp:22]: Please include minimal debug_stream detail header instead

File: include/seqan3/io/sam_file/format_sam.hpp [hunk 12]
```diff
@@ -12,36 +12,26 @@
...
 
 #include <seqan3/alphabet/concept.hpp>
-#include <seqan3/alphabet/views/char_to.hpp>
 #include <seqan3/alphabet/views/to_char.hpp>
-#include <seqan3/core/debug_stream/detail/to_string.hpp>
-#include <seqan3/core/detail/template_inspection.hpp>
-#include <seqan3/core/range/type_traits.hpp>
-#include <seqan3/io/detail/ignore_output_iterator.hpp>
-#include <seqan3/io/detail/misc.hpp>
+#include <seqan3/core/debug_stream.hpp>
```
Comment (eseiler) [inline include/seqan3/io/sam_file/format_sam.hpp:22]: use minimal detail header

**Review by eseiler — CHANGES_REQUESTED** [review]
I commented on things I saw.

I think after amending, the next step would be to add new tests.

Some parsing should not work correctly, i.e. parsing multiple "other" tags as only the last one will be stored.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 13]
```diff
@@ -433,23 +416,24 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
         take_until_predicate(is_char<'\t'> || is_char<'\n'>);
         read_field(string_buffer, value);
     };
 
-    auto parse_until_newline = [&] (auto & value)
+    auto parse_until_tab_or_newline = [&] (auto & value)
     {
-        take_until_predicate(is_char<'\n'>);
+        take_until_predicate(is_char<'\t'> || is_char<'\n'>);
+        string_buffer.push_back('\t');
```
[the remark this answers is not in the document]
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:436]: No, without the push_back() we would get unseperated tags:
```bash
header.read_groups[0]
    Which is: ("U0a_A2_L1", "PL:illuminaPU:1LB:1SM:NA12878")
  (std::pair<std::string, std::string>{"U0a_A2_L1", "PL:illumina\tPU:1\tLB:1\tSM:NA12878"})
    Which is: ("U0a_A2_L1", "PL:illumina\tPU:1\tLB:1\tSM:NA12878")
```

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 7 above)
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:549]: No it apends the tags. Thats why I need to `push_back('\t’)`

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 8 above)
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:628]: see above answer

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:436]: Ah.

If I see it correctly, you could just do:

```
take_until_predicate(is_char<'\t'> || is_char<'\n'>);
if (is_char<'\t'>(*it))
    string_buffer.push_back('\t');
read_field(string_buffer, value);
```

After `take_until_predicate` the iterator should point to a tab or newline, and you only need a tab in your buffer if you are not at the end.

Then you can also get rid of `pop_back` further down.

**Comment by Irallia** [comment]
I have refactored a lot of the code, I hope I have seen all your comments and incorporated them correctly.

**Comment by eseiler** [comment]
> I have refactored a lot of the code, I hope I have seen all your comments and incorporated them correctly.

This one is open: https://github.com/seqan/seqan3/pull/2605/files#r631864522

**Comment by eseiler** [comment]
@Irallia I rebased on master and changed the commits a bit. There's one open review point.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:436]: That would be nice, but this doesn't work eather. When we take the example again, the sam file line looks like:
`@RG	ID:U0a_A2_L1	PL:illumina	PU:1	LB:1	SM:NA12878`
but it could also look like
`@RG	PL:illumina	PU:1	LB:1	SM:NA12878	ID:U0a_A2_L1`
The ID is not a part of the second part of the `read_groups` tuple, thus the `\n` would not be at the end of the elements of this second part and we would never avoid the `if`.

->
```bash
.../seqan3/test/unit/io/sam_file/sam_file_format_test_template.hpp:183: Failure
Expected equality of these values:
  header.read_groups[0]
    Which is: ("U0a_A2_L1", "PL:illumina\tPU:1\tLB:1\tSM:NA12878\t")
  (std::pair<std::string, std::string>{"U0a_A2_L1", "PL:illumina\tPU:1\tLB:1\tSM:NA12878"})
    Which is: ("U0a_A2_L1", "PL:illumina\tPU:1\tLB:1\tSM:NA12878")
```

[the remark this answers is not in the document]
Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:436]: Thanks for the explanation :)
Can you add this in a condensed form as comment to the lambda?

I'll take another look sometime later, but it doesn't seem like it can be simplified.

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 14]
```diff
@@ -188,24 +188,36 @@ TEST_F(sam_format, header_errors)
...
+            Not supported SAM header tag in @PG: VB
+            Not supported SAM header tag in @PG: pb
+        */
         std::string header_str
         {
-            "@HD\tVN:1.6\tSO:coordinate\tSS:coordinate:queryname\tGO:none\tpb:usr_defined_tag\n"
-            "@PG\tID:qc\tPN:quality_control\tCL:qc -f file\tDS:trim reads with low qual\tVN:1.0.0\tpb:usr_defined_tag\n"
-            "@SQ\tSN:ref2\tLN:243199373\tAS:hs37d5\tpb:usr_defined_tag\n"
-            "@RG\tID:U0a_A2_L1\tPL:illumina\tPU:1\tLB:1\tSM:NA12878\tpb:usr_defined_tag\n"
+            "@HD\tVN:1.6\tVB:usr_defined_tag\tSB:usr_defined_tag\tGB:usr_defined_tag\tpb:usr_defined_tag\n"
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:213]: Can you check if something like here works?

https://github.com/seqan/seqan3/blob/929c355bd14caeb9761996b25dc9271379da776b/test/unit/argument_parser/format_parse_test.cpp#L24-L26 (but with `EXPECT_EQ([...]GetCapturedStderr(), "Unsupported...")`

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 15]
```diff
@@ -188,24 +188,36 @@ TEST_F(sam_format, header_errors)
...
+            Not supported SAM header tag in @HD: VB
+            Not supported SAM header tag in @HD: SB
+            Not supported SAM header tag in @HD: GB
+            Not supported SAM header tag in @HD: pb
+            Not supported SAM header tag in @PG: IB
+            Not supported SAM header tag in @PG: PB
+            Not supported SAM header tag in @PG: CB
+            Not supported SAM header tag in @PG: DB
+            Not supported SAM header tag in @PG: VB
+            Not supported SAM header tag in @PG: pb
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:209]: Can you rename it to "Unsupported" ?

**Comment by Irallia** [comment]
If the CI runs through and the codecoverage looks okay again, I think this PR is ready to review.

File: test/unit/io/sam_file/format_sam_test.cpp (hunk 14 above)
Comment (Irallia) [reply test/unit/io/sam_file/format_sam_test.cpp:213]: jepp that works!

**Comment by eseiler** [comment]
Note to myself

current behaviour:
skip tags in `HD` and `PG` and warn 
do not warn in `RG` and `SQ`, tags are stored as string in tuple

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 16]
```diff
@@ -536,217 +539,237 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-                                ++it;                                       // skip I
-                                if (is_char<'D'>(*it))                      // read required ID tag
+                                if (is_char<'D'>(*it))
                                 {
                                     parse_tag_value(get<0>(tmp));
+                                    break;
                                 }
-                                else                                        // parse other user defined tag with D..
-                                {
-                                    get<1>(tmp).push_back('D');
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp]: this was wrong

**Review by eseiler — CHANGES_REQUESTED** [review]
I refactored the code a bit (with using `[[fallthrough]];` to reduce code duplication).

I think after adding tests for the remaining missing coverage, this is good to go

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 17]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
     {
         std::string header_str
         {
-            "@HD\tVN:1.0\tTT:this is not a valid tag\n"
+            "@HA\tthis is not a valid tag\n"
         };
         std::istringstream istream(header_str);
         seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
-        EXPECT_THROW(fin.begin(), seqan3::format_error);
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "Illegal SAM header tag: @HA"
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:137]:
```suggestion
        EXPECT_THROW(fin.begin(), seqan3::format_error);
```

Until we actually test the error messages (which we currently cannot), I wouldn't add the expected error message as they might change and it's quite clear what you are testing (`// unsupported @-tag tests` + `@HA this is not a valid tag`)

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 18]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
+    }
+    {
+        std::string header_str
+        {
+            "@PA\tthis is not a valid tag\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "Illegal SAM header tag: @PA"
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:156]:
```suggestion
    { // invalid header record type: @PA
        std::string header_str
        {
            "@PA\tthis is not a valid tag\n"
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_THROW(fin.begin(), seqan3::format_error);
    }
```

etc.

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 19]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
-            "@HD\tVN:1.0\n"
             "@TT\tthis is not a valid tag\n"
         };
         std::istringstream istream(header_str);
         seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
-        EXPECT_THROW(fin.begin(), seqan3::format_error);
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "Illegal SAM header tag starting with:T"
     }
+    // unusual ordering of tags
     {
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:185]:
```suggestion
    { // order of tags does not matter
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 20]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
-            "@PG\tID:prog\tTT:this is not a valid tag\n"
+            "@HD\tGO:none\tSO:coordinate\tVN:1.6\tSS:coordinate:queryname\n"
+            "@PG\tPN:novoalign\tPP:qc\tID:novoalign\tVN:V3.02.07\tCL:novoalign -d /hs37d5.ndx -f /file.fastq.gz\n"
+            "@SQ\tAS:hs37d5\tSN:ref2\tLN:243199373\n"
+            "@RG\tLB:1\tSM:NA12878\tPL:illumina\tPU:1\tID:U0a_A2_L1\n"
         };
         std::istringstream istream(header_str);
         seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
-        EXPECT_THROW(fin.begin(), seqan3::format_error);
+        EXPECT_NO_THROW(fin.begin());                       // Order of tags should not trigger errors
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:195]:
```suggestion
        EXPECT_NO_THROW(fin.begin());
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 21]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
+    }
+    // user defined tags -> cerr of unspported tags
+    {
+        // User defined tags should not trigger errors,but prints in cerr:
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp]:
```suggestion
    { // User defined tags should not trigger errors, but print warnings to cerr
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 22]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
+        std::string header_str
+        {
+            "@HD\tVN:1.6\tVB:usr_defined_tag\tSB:usr_defined_tag\tGB:usr_defined_tag\tpb:usr_defined_tag\n"
+            "@SQ\tSN:ref2\tLN:243199373\tSB:usr_defined_tag\tLB:usr_defined_tag\tpb:usr_defined_tag\n"
+            "@RG\tID:U0a_A2_L1\tIB:usr_defined_tag\tpb:usr_defined_tag\n"
+            "@PG\tID:qc\tIB:usr_defined_tag\tPB:usr_defined_tag\tCB:usr_defined_tag\tDB:usr_defined_tag\tVB:usr_defined_tag\tpb:usr_defined_tag\n"
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:205]: `usr_defined_tag` -> `user_tag`

suggestion won't let me suggest

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 23]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
+        };
+        std::string cerr_of_unspported_tags
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:207]:
```suggestion
        std::string expected_cerr
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 24]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
+    // @HD tests
+    {
+        std::string header_str
+        {
+            "@HD\n"                 // required VN tag missing
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required VN tag in @HD is missing."
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:236]:
```suggestion
    { // Required tags in HD
        std::string header_str
        {
            "@HD\n" // VN is missing
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_THROW(fin.begin(), seqan3::format_error);
    }
```

etc

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 25]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
+    {
+        std::string header_str
+        {
+            "@SQ\tSN:ref\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required LN tag in @SQ is missing or 0."
     }
     {
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:256]:
```suggestion
    { // Unknown reference name in SQ
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 26]
```diff
@@ -125,64 +125,224 @@ struct sam_format : public sam_file_data
...
-            "@HD\tVN:1.0\n"
-            "@SQ\tSN:unknown_ref\tLN:0\n"
+            "@SQ\tSN:unknown_ref\tLN:1\n"
         };
         std::istringstream istream(header_str);
         seqan3::sam_file_input fin{istream, this->ref_ids, this->ref_sequences, seqan3::format_sam{}};
-        EXPECT_THROW(fin.begin(), seqan3::format_error);
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "Unknown reference name 'unknown_ref' found in SAM header
+                                                            //  (header.ref_ids(): [ref])."
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:265]:
```suggestion
        EXPECT_THROW(fin.begin(), seqan3::format_error);
    }
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 27]
```diff
@@ -125,64 +125,223 @@ struct sam_format : public sam_file_data
...
+    {
+        std::string header_str
+        {
+            "@SQ\tSN:ref\tLN:-10\n"                          // allowed range of LN: [1,2^31−1]
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "Provided reference has unequal length as specified in
+                                                            //  the header."
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:294]: seems redundant

**Review by eseiler — CHANGES_REQUESTED** [review]
Some more comments regarding test; I added a commit that should enable the LN checks

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp]: I managed to find a way

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 28]
```diff
@@ -433,182 +416,362 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+                                                                 "header (header.ref_ids(): ", hdr.ref_ids(), ").")};
 
-                    if (id_it == hdr.ref_dict.end())
-                        throw format_error{detail::to_string("Unknown reference name '", id, "' found in SAM header ",
-                                                            "(header.ref_ids(): ", hdr.ref_ids(), ").")};
+                        auto & given_ref_info = hdr.ref_id_info[id_it->second];
 
-                    auto & given_ref_info = hdr.ref_id_info[id_it->second];
+                        if (std::get<0>(given_ref_info) != std::get<0>(info))
+                            throw format_error{"Provided reference and reference length provided in header differ."};
```
Comment (eseiler) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:599]:
```suggestion
                            throw format_error{"Provided and header-based reference length differ."};
```

**Comment by Irallia** [comment]
Thanks for your work! I changed the test documentation, as you mentioned, and added a changelog entry.

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 29]
```diff
@@ -125,49 +125,133 @@ struct sam_format : public sam_file_data
...
+    { // invalid header record type: @CA
+        std::string header_str
+        {
+            "@CA\tthis is not a valid tag\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);
+    }
+    {{ // invalid header record type: @TT
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:174]:
```suggestion
    { // invalid header record type: @TT
```

Comment (Irallia) [reply test/unit/io/sam_file/format_sam_test.cpp]: jepp already saw it :)

File: CHANGELOG.md [hunk 30]
```diff
@@ -106,6 +106,9 @@ If possible, provide tooling that performs the changes, e.g. a shell-script.
   * The processed data should experience no negative effects since `gz` and `bgzf` are **fully compatible**.
   * This bug may also cause unexpected parallelisation when reading `gz`-compressed input. This is the case when the
     `gz`-compressed input was also generated with SeqAn.
+* Parsing sam & bam files caused some errors related to their headers Now, as described in the specification, the
+  ordering of the header tags doesn't matter anymore and no error is given for unsupported tags
+  ([\#2605](https://github.com/seqan/seqan3/pull/2605)).
```
Comment (eseiler) [inline CHANGELOG.md:111]:
```suggestion
* The following requirements for parsing a SAM/BAM header where relaxed as they where in violation of the specification 
  ([\#2605](https://github.com/seqan/seqan3/pull/2605)):
  * The order of tags within the header may be arbitrary. Before, necessary tags where required to be first.
  * Unknown tags will emit a warning. Before, a error was raised.
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 31]
```diff
@@ -125,49 +125,133 @@ struct sam_format : public sam_file_data
...
+    // @SQ tests
+    {
+        std::string header_str
+        {
+            "@SQ\tLN:1\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required SN tag in @SQ is missing."
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:241]:
```suggestion
    { // missing SN tag in @SQ
        std::string header_str
        {
            "@SQ\tLN:1\n"
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_THROW(fin.begin(), seqan3::format_error);
    }
```

also for the others.

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 32]
```diff
@@ -125,49 +125,133 @@ struct sam_format : public sam_file_data
...
+        testing::internal::CaptureStderr();
+        EXPECT_NO_THROW(fin.begin());
+        EXPECT_EQ(testing::internal::GetCapturedStderr(), expected_cerr);
+    }
+    { // Required tags in HD
         std::string header_str
         {
-            "@HD\tVN:1.0\n"
-            "@PG\tID:prog\tTT:this is not a valid tag\n"
+            "@HD\n" // VN is missing
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:226]:
```suggestion
            "@HD\n"
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 33]
```diff
@@ -125,49 +125,133 @@ struct sam_format : public sam_file_data
...
+            "Unsupported SAM header tag in @PG: pb\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+
+        testing::internal::CaptureStderr();
+        EXPECT_NO_THROW(fin.begin());
+        EXPECT_EQ(testing::internal::GetCapturedStderr(), expected_cerr);
+    }
+    { // Required tags in HD
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:223]:
```suggestion
    { // missing VN tag in @HD
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 34]
```diff
@@ -125,49 +125,133 @@ struct sam_format : public sam_file_data
...
+    {
+        std::string header_str
+        {
+            "@SQ\tLN:1\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required SN tag in @SQ is missing."
+    }
     {
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:242]:
```suggestion
    { // missing LN tag in @SQ
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 35]
```diff
@@ -125,49 +125,133 @@ struct sam_format : public sam_file_data
...
         std::string header_str
         {
-            "@HD\tVN:1.0\n"
-            "@SQ\tSN:unknown_ref\tLN:0\n"
+            "@SQ\tSN:ref\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required LN tag in @SQ is missing or 0."
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:249]:
```suggestion
        EXPECT_THROW(fin.begin(), seqan3::format_error);
```

Also, this would raise an error that LN is missing since we handle that case explicitly

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 36]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
     {
         std::string header_str
         {
-            "@HD\tVN:1.0\n"
-            "@SQ\tSN:ref\tLN:0\n" /*wrong length*/
+            "@SQ\tSN:ref\tLN:0\n"                           // allowed range of LN: [1,2^31−1]
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:263]:
```suggestion
            "@SQ\tSN:ref\tLN:0\n"
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 37]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
     {
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:260]:
```suggestion
    { // LN cannot be 0
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 38]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
         std::string header_str
         {
-            "@HD\tVN:1.0\n"
-            "@SQ\tSN:ref\tLN:0\n" /*wrong length*/
+            "@SQ\tSN:ref\tLN:0\n"                           // allowed range of LN: [1,2^31−1]
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required LN tag in @SQ is missing or 0."
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:267]:
```suggestion
        EXPECT_THROW(fin.begin(), seqan3::format_error);
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 39]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
+    {
+        std::string header_str
+        {
+            "@SQ\tSN:ref\tLN:-1\n"                          // allowed range of LN: [1,2^31−1]
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "Provided reference has unequal length as specified in
+                                                            //  the header."
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:278]:
```suggestion
    { // LN cannot be negative
        std::string header_str
        {
            "@SQ\tSN:ref\tLN:-1\n"
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_THROW(fin.begin(), seqan3::format_error);
    }
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 40]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
+    {
+        std::string header_str
+        {
+            "@SQ\tSN:ref\tLN:2147483647\n"                  // = 2^31−1, allowed range of LN: [1,2^31−1]
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_NO_THROW(fin.begin());
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:287]:
```suggestion
    { // maximum LN value is 2^31-1
        std::string header_str
        {
            "@SQ\tSN:ref\tLN:2147483647\n"
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_NO_THROW(fin.begin());
    }
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 41]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
+    {
+        std::string header_str
+        {
+            "@SQ\tSN:ref\tLN:2147483648\n"                  // = 2^31, allowed range of LN: [1,2^31−1]
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "[CORRUPTED SAM FILE] Casting '2147483648' into type int
+                                                            //  would cause an overflow."
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:297]:
```suggestion
    { // LN exceeds maximum value
        std::string header_str
        {
            "@SQ\tSN:ref\tLN:2147483648\n"
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_THROW(fin.begin(), seqan3::format_error);
    }
```

File: test/unit/io/sam_file/format_sam_test.cpp (hunk 34 above)
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:242]: Can you cluster all `LN` related tests together?

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 42]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
+    {
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:298]:
```suggestion
    { // Provided and header-based reference length differ
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 43]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
+        std::string header_str
+        {
+            "@SQ\tSN:ref\tLN:4\n"
         };
         std::istringstream istream(header_str);
         seqan3::sam_file_input fin{istream, this->ref_ids, this->ref_sequences, seqan3::format_sam{}};
-        EXPECT_THROW(fin.begin(), seqan3::format_error);
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "Provided reference has unequal length as specified in
+                                                            //  the header."
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:306]:
```suggestion
        EXPECT_THROW(fin.begin(), seqan3::format_error);
```

(the message is also different now)

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 44]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
+    // @RG tests
+    {
+        std::string header_str
+        {
+            "@RG\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required ID tag in @RG is missing."
+    }
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:317]:
```suggestion
    { // missing ID tag in @RG
        std::string header_str
        {
            "@RG\n"
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_THROW(fin.begin(), seqan3::format_error);
    }
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 45]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
+    // @PG tests
+    {
+        std::string header_str
+        {
+            "@PG\n"
+        };
+        std::istringstream istream(header_str);
+        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
+        EXPECT_THROW(fin.begin(), seqan3::format_error);    // "The required ID tag in @PG is missing."
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:326]:
```suggestion
    { // missing ID tag in @PG
        std::string header_str
        {
            "@PG\n"
        };
        std::istringstream istream(header_str);
        seqan3::sam_file_input fin{istream, seqan3::format_sam{}};
        EXPECT_THROW(fin.begin(), seqan3::format_error);
```

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 46]
```diff
@@ -176,13 +260,72 @@ TEST_F(sam_format, header_errors)
...
     }
+
```
Comment (eseiler) [inline test/unit/io/sam_file/format_sam_test.cpp:328]:
```suggestion
```

**Review by eseiler — CHANGES_REQUESTED** [review]
Last bit of 💅 :)

**Comment by Irallia** [comment]
I can tidy up the history, after your approve.

**Review by eseiler — APPROVED** [review]
LGTM, please rebase/cleanup and then request second review :)

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 47]
```diff
@@ -433,182 +416,362 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+                                if (is_char<'N'>(*it)) // parse required VN (version) tag
+                                {
+                                    header_entry = std::addressof(hdr.format_version);
+                                    break;
+                                }
+                                [[fallthrough]];
+                            }
+                            case 'S':
+                            {
+                                if (is_char<'O'>(*it)) // SO (sorting) tag
```
[the remark this answers is not in the document]
Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:488]: Why even use a switch here? Wouldn't an if case in this case be better?

Why not read in the second letter in a single 2byte word (we could use a switch in that case):

```c++
    // For prove of concept: https://godbolt.org/z/ab36EzYvG
    auto make_tag = [](uint8_t char1, uint8_t char2) constexpr
    {
        return static_cast<uint16_t>(char1) | (static_cast<uint16_t>(char2) << CHAR_BIT);
    };

    char [2] raw_tag{};
    raw_tag[0] = *it;
    ++it;
    raw_tag[1] = *it;
    ++it;
    uint16_t tag = make_tag(raw_tag[0], raw_tag[1]);

    switch (tag)
    {
        case make_tag('V', 'N'): // parse required VN (version) tag
            header_entry = std::addressof(hdr.format_version);
            break;
        case make_tag('S', 'O'): // SO (sorting) tag
            header_entry = std::addressof(hdr.sorting);
            break;
        case make_tag('S', 'S'):  // SS (sub-order) tag
            header_entry = std::addressof(hdr.sorting);
            break;
        // ...
        default:
            rint_cerr_of_unspported_tag("HD", raw_tag[0], raw_tag[1]);
            break;
    }
```

I know that is asking a lot, but can we make this change to simplify this complete section?

**Review by marehr — CHANGES_REQUESTED** [review]
I think we should do the tag handling differently if we touch the file anyway.

I proposed a change to flatten the nested-ness of all if/switch.

File: CHANGELOG.md [hunk 48]
```diff
@@ -106,6 +106,10 @@ If possible, provide tooling that performs the changes, e.g. a shell-script.
   * The processed data should experience no negative effects since `gz` and `bgzf` are **fully compatible**.
   * This bug may also cause unexpected parallelisation when reading `gz`-compressed input. This is the case when the
     `gz`-compressed input was also generated with SeqAn.
+* The following requirements of parsing a SAM/BAM header where relaxed as they were in violation of the specification
+  ([\#2605](https://github.com/seqan/seqan3/pull/2605)):
+  * The order of tags within the header may be arbitrary. Before, necessary tags where required to be first.
+  * Unknown tags will emit a warning. Before, a error was raised.
```
[the remark this answers is not in the document]
Comment (eseiler) [reply CHANGELOG.md:112]: It was an error before, but is only a warning via cerr now.

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 49]
```diff
@@ -125,64 +125,200 @@ struct sam_format : public sam_file_data
 // since BAM uses the same read header function from SAM, it only needs to be tested once
 TEST_F(sam_format, header_errors)
 {
-    {
+
+    { // invalid header record type: @HA
         std::string header_str
         {
-            "@HD\tVN:1.0\tTT:this is not a valid tag\n"
```
[the remark this answers is not in the document]
Comment (Irallia) [reply test/unit/io/sam_file/format_sam_test.cpp:131]: A header contains header lines starting with @. Each @Header Tag is optional. That means that we dont need the @HD... when we test something else. So I have simplified the example headers to include only what is necessary.

[the remark this answers is not in the document]
Comment (Irallia) [reply test/unit/io/sam_file/format_sam_test.cpp:131]: You can find the information here: https://samtools.github.io/hts-specs/SAMv1.pdf (Section 1.3)

[the remark this answers is not in the document]
Comment (Irallia) [reply test/unit/io/sam_file/format_sam_test.cpp:131]: This means the old test cases are rephrased and simplified.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 50]
```diff
@@ -63,7 +64,7 @@ class format_sam_base
     //!\brief A variable that tracks whether the content of header has been written or not.
     bool header_was_written{false};
 
-    //!\brief Tracks whether reference information (\@SR tag) were found in the SAM header
+    //!\brief Tracks whether reference information (\@SQ tag) were found in the SAM header
```
[the remark this answers is not in the document]
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:67]: Yes it was a typo. There are only the following @Header Tags existing: @HD, @SQ, @RG, @PG and @CO. And here we have a switch case for SQ.

File: test/unit/io/sam_file/format_sam_test.cpp [hunk 51]
```diff
@@ -125,64 +125,200 @@ struct sam_format : public sam_file_data
 // since BAM uses the same read header function from SAM, it only needs to be tested once
```
[the remark this answers is not in the document]
Comment (Irallia) [reply test/unit/io/sam_file/format_sam_test.cpp:125]: Yes, we will accept them and warn, that we don't process them.

> This PR will fail the api-stability test:

What does that mean? Why and what can I do about it?

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 47 above)
[the remark this answers is not in the document]
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:488]: Oha, I have not seen a way to check two char's at once. Of course, that would be much clearer. I will try it out.
The fallthrough I also did not know, that came from @eseiler. 
All these new things I get to know :)

File: test/unit/io/sam_file/format_sam_test.cpp (hunk 51 above)
[the remark this answers is not in the document]
Comment (marehr) [reply test/unit/io/sam_file/format_sam_test.cpp:125]: That means that seqan3/test/api_stability will fail. I'll help you with that 👍🏽

File: test/unit/io/sam_file/format_sam_test.cpp (hunk 49 above)
[the remark this answers is not in the document]
Comment (marehr) [reply test/unit/io/sam_file/format_sam_test.cpp:131]: Okay, but on the other side we still have `@HD` tests, right?

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 52]
```diff
@@ -433,182 +422,307 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+        std::cerr << "Unsupported SAM header tag in @" << header_tag << ": " << raw_tag[0] << raw_tag[1] << '\n';
+    };
+
     while (it != end && is_char<'@'>(*it))
     {
-        ++it;                                                           // skip @
+        ++it; // skip @
+
+        // char[2] raw_at_tag{};
+        std::array<char, 2> raw_at_tag{};
```
Comment (Irallia) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:466]: `char [2]` did not work, but `std::array<char, 2>` worked.

```bash
.../seqan3/include/seqan3/io/sam_file/detail/format_sam_base.hpp:464:14: error: expected identifier before numeric constant
  464 |         char[2] raw_at_tag{};
      |              ^
```

Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:466]:
```c++
char raw_at_tag[2]{};
```

is the correct syntax :)

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 53]
```diff
@@ -430,346 +436,291 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-    // Some tags are not parsed individually. Instead, these are simply copied into a string.
+    // Some tags are not parsed individually. Instead, these are simply copied into a std::string.
     // Multiple tags must be separated by a `\t`, hence we prepend a tab to the string, except the first time.
     // Alternatively, we could always append a `\t`, but this would have the side effect that we might need to trim a
     // trailing tab after parsing all tags via `pop_back()`.
     // Unfortunately, we do not know when we are parsing the last tag (and in this case just not append a tab),
     // because even though we can check if the line ends in a `\n`, it is not guaranteed that the last tag of the
     // line is passed to this lambda. For example, the line might end with a tag that is properly parsed, such as `ID`.
-    auto parse_until_tab_or_newline = [&] (std::string & value, char const first_letter)
+    auto parse_until_tab_or_newline = [&] (std::string & value, std::array<char, 2> raw_tag)
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:446]: this name is somehow wrong, because it adds the raw_tag, it seems like a function that is used only in error cases?

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 52 above)
Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:466]: but we can keep the std::array

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 54]
```diff
@@ -433,182 +422,307 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+    {
+        std::cerr << "Unsupported SAM header tag in @" << header_tag << ": " << raw_tag[0] << raw_tag[1] << '\n';
+    };
+
     while (it != end && is_char<'@'>(*it))
     {
-        ++it;                                                           // skip @
+        ++it; // skip @
+
+        // char[2] raw_at_tag{};
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:465]:
```suggestion
```

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 55]
```diff
@@ -423,6 +406,12 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
     auto end = std::ranges::end(stream_view);
     std::vector<char> string_buffer{};
 
+    // For prove of concept: https://godbolt.org/z/ab36EzYvG
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:409]:
```suggestion
```

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 56]
```diff
@@ -433,182 +422,307 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-                    parse_until_newline(get<1>(info));
-                }
-                ++it;                                                   // skip newline
+                    ++it; // skip tab
+
+                    std::array<char, 2> raw_tag{};
+                    raw_tag[0] = *it;
+                    ++it;
+                    raw_tag[1] = *it;
+                    ++it;
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:547]: maybe we should put that into a function, as we do that multiple times:

```c++
auto read_tag = [](auto it, std::array<char, 2> & tag)
{
    raw_tag[0] = *it;
    ++it;
    raw_tag[1] = *it;
    ++it;
    return it;
}

std::array<char, 2> raw_tag{};
it = read_tag(it, raw_tag);
```

**Review by marehr — COMMENTED** [review]
That's definitely better! 

I would dry (=don't repeat yourself) reading in the tag and I think this PR is good.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 56 above)
Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:547]: why copy the iterator and not just capture ?

Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:547]: We can also take it via lvalue. I'm always a bit confused, because the standard often returns an iterator as copy after an operation.

Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:547]: I think I would prefer `[&it]` or `[&]` because we do it for other lambdas.
Maybe we could also have a function that directly returns the `uint16_t` tag since we need to do it anyways.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 53 above)
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:446]: I think I dont understand what you mean.
This function is used to parse tags plus their value into a string, as these tags are not handled properly. So we parse these tags until their end (tab odr newline) into this string of kind of unhandled tags.

File: test/unit/io/sam_file/format_sam_test.cpp (hunk 49 above)
[the remark this answers is not in the document]
Comment (Irallia) [reply test/unit/io/sam_file/format_sam_test.cpp:131]: yepp, the test of lines 183, 194, 226. And the tests with normal headers which i left untouched (e.g. line 24)

**Review by Irallia — COMMENTED** [review]
Found one useless code line

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 56 above)
Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp]: So you mean to put these into the lambda function aswell?

```cpp
                    std::array<char, 2> raw_tag{};
                    it = read_tag(it, raw_tag);
                    uint16_t tag = make_tag(raw_tag[0], raw_tag[1]);
```

Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp]: so the idea is:
```cpp
std::array<char, 2> raw_tag{};

uint16_t get_tag = [*it](std::array<char, 2> & raw_tag)
{
    raw_tag[0] = *it;
    ++it;
    raw_tag[1] = *it;
    ++it;
    return make_tag(raw_tag[0], raw_tag[1]); 
}

switch (get_tag())
...
```

Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp]: Yeah basically, the array could also be once in the beginning, and then you could even do

```cpp
std::array<char, 2> raw_tag{}; // <- somwhere in the beginning and used every time when parsing a tag

// the lambda
uint16_t get_tag = [&] ()
{
    raw_tag[0] = *it;
    ++it;
    raw_tag[1] = *it;
    ++it;
    return make_tag(raw_tag[0], raw_tag[1]); 
}

// when parsing a tag
switch (get_tag())
```

but let's see what Marcel thinks

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 53 above)
Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:454]: I think the name is too general as it does more than that. Why should this lambda append additional stuff from the raw_tag if it is named parse_until_tab_or_newline.

I think something like `parse_unknown_tag_value` would be more appropriate, but I'm not too sure when this function is called, so I need your help what this function actually is intended for.

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 57]
```diff
@@ -423,6 +406,20 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+    };
+
+    auto read_tag = [](auto it, std::array<char, 2> & raw_tag)
+    {
+        raw_tag[0] = *it;
+        ++it;
+        raw_tag[1] = *it;
+        ++it;
+        return it;
+    };
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:421]:
```suggestion
    auto read_tag = [&it](std::array<char, 2> & raw_tag)
    {
        raw_tag[0] = *it;
        ++it;
        raw_tag[1] = *it;
        ++it;
    };
```

okay let's do enricos suggestion

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 58]
```diff
@@ -433,182 +430,290 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
+        std::cerr << "Unsupported SAM header tag in @" << header_tag << ": " << raw_tag[0] << raw_tag[1] << '\n';
+    };
+
     while (it != end && is_char<'@'>(*it))
     {
-        ++it;                                                           // skip @
+        ++it; // skip @
+
+        std::array<char, 2> raw_at_tag{};
+        it = read_tag(it, raw_at_tag);
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:474]:
```suggestion
        read_tag(raw_at_tag);
```

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 59]
```diff
@@ -433,182 +430,290 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-                        if (is_char<'O'>(*it))                          // SO (sorting) tag
-                            who = std::addressof(hdr.sorting);
-                        else if (is_char<'S'>(*it))                     // SS (sub-order) tag
-                            who = std::addressof(hdr.subsorting);
-                        else
-                            throw format_error{std::string{"Illegal SAM header tag: S"} + *it};
-                    }
-                    else if (!is_char<'G'>(*it))                        // GO (grouping) tag
+                    std::array<char, 2> raw_tag{};
+                    it = read_tag(it, raw_tag);
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:488]:
```suggestion
                    read_tag(raw_tag);
```

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 60]
```diff
@@ -433,182 +430,290 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-                    ++it;                                               // skip tab
-                    parse_until_newline(get<1>(info));
-                }
-                ++it;                                                   // skip newline
+                    ++it; // skip tab
 
-                /* If reference information was given, the ids exist and we can fill ref_dict directly.
-                 * If not, wee need to update the ids first and fill the reference dictionary afterwards. */
+                    std::array<char, 2> raw_tag{};
+                    it = read_tag(it, raw_tag);
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:545]:
```suggestion
                    read_tag(raw_tag);
```

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 61]
```diff
@@ -433,182 +430,290 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-                if (is_char<'\t'>(*it))                                 // read rest of the tags
+                // All tags can appear in any order, SN and LN are required tags
+                while (is_char<'\t'>(*it))
                 {
-                    ++it;
-                    parse_until_newline(get<1>(tmp));
+                    ++it; // skip tab
+
+                    std::array<char, 2> raw_tag{};
+                    it = read_tag(it, raw_tag);
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:616]:
```suggestion
                    read_tag(raw_tag);
```

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 62]
```diff
@@ -433,182 +430,290 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
-                    std::string * who = &tmp.version;
+                    ++it; // skip tab
+                    std::string * program_info_entry{nullptr};
 
-                    switch (*it)
-                    {
-                        case 'P':
-                            ++it;                                       // skip P
+                    std::array<char, 2> raw_tag{};
+                    it = read_tag(it, raw_tag);
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:652]:
```suggestion
                    read_tag(raw_tag);
```

**Comment by marehr** [comment]
Why not? Looks fine to me 😁

Am 18. Mai 2021 14:49:57 MESZ schrieb Enrico Seiler ***@***.***>:
***@***.*** commented on this pull request.

File: test/unit/io/sam_file/format_sam_test.cpp (hunk 51 above)
[the remark this answers is not in the document]
Comment (marehr) [reply test/unit/io/sam_file/format_sam_test.cpp:125]: (because before something threw an exception, now it doesn't anymore)

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 56 above)
Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp]: I like that version, but I would still call it `parse_tag` to be in line with the other names.

File: test/unit/io/sam_file/format_sam_test.cpp (hunk 51 above)
[the remark this answers is not in the document]
Comment (marehr) [reply test/unit/io/sam_file/format_sam_test.cpp:125]: I added a commit that fixes the api stability

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp [hunk 63]
```diff
@@ -433,182 +432,270 @@ inline void format_sam_base::read_header(stream_view_type && stream_view,
...
 
-    auto parse_until_newline = [&] (auto & value)
+    // Some tags are not parsed individually. Instead, these are simply copied into a std::string.
+    // Multiple tags must be separated by a `\t`, hence we prepend a tab to the string, except the first time.
+    // Alternatively, we could always append a `\t`, but this would have the side effect that we might need to trim a
+    // trailing tab after parsing all tags via `pop_back()`.
+    // Unfortunately, we do not know when we are parsing the last tag (and in this case just not append a tab),
+    // because even though we can check if the line ends in a `\n`, it is not guaranteed that the last tag of the
+    // line is passed to this lambda. For example, the line might end with a tag that is properly parsed, such as `ID`.
+    auto parse_until_tab_or_newline = [&] (std::string & value, std::array<char, 2> raw_tag)
```
Comment (marehr) [inline include/seqan3/io/sam_file/detail/format_sam_base.hpp:456]:
```suggestion
    auto parse_unknown_tag_value = [&] (std::string & value, std::array<char, 2> raw_tag)
```

?

**Review by marehr — CHANGES_REQUESTED** [review]

File: include/seqan3/io/sam_file/detail/format_sam_base.hpp (hunk 63 above)
Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:456]: Maybe even `append_tag_to_string` since it does not necessarily need to be unknown, we just use this lambda in 2 places where we "dump" all tags that get no special treatment into a string

Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:456]: okay, then: parse_and_append_unknown_tag_to_string?

Comment (Irallia) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:456]: for me okay

Comment (eseiler) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:456]: Sure, but maybe we should remove the `unknown`, i.e. `parse_and_append_tag_to_string`; `unhandled` would probably be more correct...
for the really unknown tags we emit a warning, and skip them.

Comment (marehr) [reply include/seqan3/io/sam_file/detail/format_sam_base.hpp:456]: then `parse_and_append_unhandled_tag_to_string`

**Review by marehr — APPROVED** [review]
Big thank you! (Sorry for the nitpicky-ness!)

Do you want to rebase or is squash merge okay?

**Comment by marehr** [comment]
(I merged as it seems you cleaned up the history)
